### ISSUE TITLE
Bug: sam remote invoke - ModuleNotFoundError

### ISSUE THREAD

**Issue by bdksan** [aws/aws-sam-cli#5571] opened 2023-07-19 18:37 UTC
### Description:

Failure to execute sam remote invoke command

### Steps to reproduce:

Fresh Install SAM CLI 1.91.0, Windows 10 Home 19045.3208
sam init 
1 - AWS Quick Start Templates
1 - Hello World Example
y - most popular runtime (Python and zip)
N - X-ray tracing
N - Cloudwatch Application Insights
[ENTER] sam-app
cd sam-app
sam build
aws sso login --profile BKSandBox (browser login, etc.)
sam deploy --guided
[ENTER] sam-app
[ENTER] us-west-2
[ENTER] confirm changes before deploy
[ENTER] allow SAM CLI role creation
y disable rollback
y no authentication ok
[ENTER] save arguments to configuration file
[ENTER] samconfig.toml
[ENTER] default

deploy this changeset? y
creation of stack....

Successfully created/updated stack - sam-app in us-west-2

sam list endpoints --output json --profile BKSandBox
(endpoints)
curl <endpoint>/hello
{"message": "hello world"}

$ sam remote invoke HelloWorldFunction --stack-name sam-app --profile BKSandBox

Error: No module named 'mypy_boto3_lambda'
Traceback:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.p
y", line 1055, in main
    rv = self.invoke(ctx)
...

### Observed result:

$ sam remote invoke HelloWorldFunction --stack-name sam-app --profile BKSandBox --debug
2023-07-19 19:35:40,821 | Config file location:
C:\workspace\sam-bug\sam-app\samconfig.toml
2023-07-19 19:35:40,825 | Loading configuration values from [default.['remote',
'invoke'].parameters] (env.command_name.section) in config file at
'C:\workspace\sam-bug\sam-app\samconfig.toml'...
2023-07-19 19:35:40,827 | Configuration values successfully loaded.
2023-07-19 19:35:40,828 | Configuration values are: {'stack_name': 'sam-app'}
2023-07-19 19:35:41,056 | Converting provided --output option value to Enum
2023-07-19 19:35:41,067 | Using config file: samconfig.toml, config environment:
default
2023-07-19 19:35:41,068 | Expand command line arguments to:
2023-07-19 19:35:41,070 | --stack_name=sam-app --resource_id=HelloWorldFunction
--output=RemoteInvokeOutputFormat.TEXT
2023-07-19 19:35:41,079 | Telemetry endpoint configured to be
https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-07-19 19:35:41,274 | Telemetry endpoint configured to be
https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-07-19 19:35:41,275 | Sending Telemetry: {'metrics': [{'commandRun':
{'requestId': '9a9e82b1-ec02-4031-82c6-c0ff7d8512a7', 'installationId':
'94983092-482a-4ac2-a52b-88dc606ce2b8', 'sessionId':
'f5d9cbfc-0730-4ddf-971d-82a659a1397f', 'executionEnvironment': 'CLI', 'ci':
False, 'pyversion': '3.8.8', 'samcliVersion': '1.91.0', 'awsProfileProvided':
True, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam remote
invoke', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None,
'projectName':
'593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3',
'initialCommit': None}, 'duration': 11, 'exitReason': 'ModuleNotFoundError',
'exitCode': 255}}]}
2023-07-19 19:35:41,276 | Unable to find Click Context for getting session_id.
2023-07-19 19:35:41,283 | Sending Telemetry: {'metrics': [{'events':
{'requestId': '7ac2672b-013a-4f57-9e58-52cc1b77594b', 'installationId':
'94983092-482a-4ac2-a52b-88dc606ce2b8', 'sessionId':
'f5d9cbfc-0730-4ddf-971d-82a659a1397f', 'executionEnvironment': 'CLI', 'ci':
False, 'pyversion': '3.8.8', 'samcliVersion': '1.91.0',
'metricSpecificAttributes': {'events': [{'event_name': 'SamConfigFileExtension',
'event_value': '.toml', 'thread_id': '042378ace15340bda319d16bc9e295b6',
'time_stamp': '2023-07-19 18:35:40.821', 'exception_name': None}]}}}]}
2023-07-19 19:35:41,442 | Telemetry response: 200
2023-07-19 19:35:41,458 | Telemetry response: 200

Error: No module named 'mypy_boto3_lambda'
Traceback:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.p
y", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.p
y", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.p
y", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.p
y", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.p
y", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\c
li_validation\remote_invoke_options_validations.py", line 89, in wrapped
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\c
li_validation\remote_invoke_options_validations.py", line 52, in wrapped
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decora
tors.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.p
y", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\t
elemetry\metric.py", line 184, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\t
elemetry\metric.py", line 149, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\u
tils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\m
ain.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\comma
nds\_utils\command_exception_handler.py", line 88, in wrapper_command_exception_
handler
    raise ex
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\comma
nds\_utils\command_exception_handler.py", line 68, in wrapper_command_exception_
handler
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\comma
nds\remote\invoke\cli.py", line 91, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\comma
nds\remote\invoke\cli.py", line 121, in do_cli
    from samcli.commands.remote.remote_invoke_context import RemoteInvokeContext
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\comma
nds\remote\remote_invoke_context.py", line 18, in <module>
    from samcli.lib.remote_invoke.remote_invoke_executor_factory import RemoteIn
vokeExecutorFactory
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\r
emote_invoke\remote_invoke_executor_factory.py", line 7, in <module>
    from samcli.lib.remote_invoke.lambda_invoke_executors import (
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\r
emote_invoke\lambda_invoke_executors.py", line 14, in <module>
    from mypy_boto3_lambda.client import LambdaClient

An unexpected error was encountered while executing "sam remote invoke".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20
remote%20invoke%20-%20ModuleNotFoundError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3
A%20sam%20remote%20invoke%20-%20ModuleNotFoundError

### Expected result:

Expect lambda function to be executed and results displayed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

Using cygwin on windows, but same result running in Windows cmd

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```
$ sam --info
{
  "version": "1.91.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "23.0.5",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

`Add --debug flag to command you are running`

**Comment by mildaniel** [comment] 2023-07-19 19:14
Duplicate of https://github.com/aws/aws-sam-cli/issues/5566, resolving in favour of the previous issue.

**Closed by mildaniel** 2023-07-19 19:14 UTC
Labels: stage/needs-triage
