### ISSUE TITLE
`sam deploy` fails to include `node_modules` when `--template-file` is specified

### ISSUE THREAD

**Issue by hoffa** [aws/aws-sam-cli#4203] opened 2022-09-07 16:34 UTC
### Description:

(Originally reported by @sharmmoh1983 in https://github.com/aws-actions/setup-sam/issues/57)

When deploying with `sam deploy` and specifying `--template-file`, `node_modules` isn't copied to the Lambda function, hence the Lambda breaks with dependencies.

It works fine when `--template-file` is not specified.

### Steps to reproduce:

```bash
sam init --name sam-app --runtime nodejs14.x --dependency-manager npm --app-template hello-world
cd sam-app
sam build

sam deploy --guided --template-file template.yaml  # No node_modules
sam deploy --template-file template.yaml  # Still no node_modules
sam deploy  # Now node_modules is there
```

### Observed result:

```bash
% sam deploy --debug --template-file template.yaml
2022-09-07 09:30:41,143 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-09-07 09:30:41,143 | Using config file: samconfig.toml, config environment: default
2022-09-07 09:30:41,143 | Expand command line arguments to:
2022-09-07 09:30:41,143 | --template_file=/Users/rehnc/Desktop/sam-app/template.yaml --fail_on_empty_changeset --on_failure=ROLLBACK --stack_name=a --s3_bucket=xxx --s3_prefix=a --capabilities=['CAPABILITY_IAM'] 
2022-09-07 09:30:41,357 | No Parameters detected in the template
2022-09-07 09:30:41,370 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-09-07 09:30:41,370 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-09-07 09:30:41,370 | 0 stacks found in the template
2022-09-07 09:30:41,432 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-09-07 09:30:41,432 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-09-07 09:30:41,754 | File with same data already exists at a/ffcc67c4c941076384d78437332779b4, skipping upload

	Deploying with following values
	===============================
	Stack name                   : a
	Region                       : us-west-2
	Confirm changeset            : False
	Disable rollback             : False
	Deployment s3 bucket         : xxx
	Capabilities                 : ["CAPABILITY_IAM"]
	Parameter overrides          : {}
	Signing Profiles             : {}

Initiating deployment
=====================
2022-09-07 09:30:41,784 | No Parameters detected in the template
2022-09-07 09:30:41,794 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-09-07 09:30:41,794 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-09-07 09:30:41,795 | 0 stacks found in the template
2022-09-07 09:30:41,795 | No Parameters detected in the template
2022-09-07 09:30:41,806 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-09-07 09:30:41,806 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-09-07 09:30:41,807 | 2 resources found in the stack 
2022-09-07 09:30:42,350 | File with same data already exists at a/981fe074614c895beb6b67966a9eba4f.template, skipping upload

Waiting for changeset to be created..
Error: No changes to deploy. Stack a is up to date
```

```bash
% sam deploy --debug
2022-09-07 09:32:28,530 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-09-07 09:32:28,531 | Using config file: samconfig.toml, config environment: default
2022-09-07 09:32:28,531 | Expand command line arguments to:
2022-09-07 09:32:28,531 | --template_file=/Users/rehnc/Desktop/sam-app/.aws-sam/build/template.yaml --fail_on_empty_changeset --on_failure=ROLLBACK --stack_name=a --s3_bucket=xxx --s3_prefix=a --capabilities=['CAPABILITY_IAM'] 
2022-09-07 09:32:28,764 | No Parameters detected in the template
2022-09-07 09:32:28,777 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-09-07 09:32:28,777 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-09-07 09:32:28,777 | 0 stacks found in the template
2022-09-07 09:32:28,838 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-09-07 09:32:28,838 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-09-07 09:32:29,070 | File with same data already exists at a/96411c97697f150daee4a82f05f85460, skipping upload

	Deploying with following values
	===============================
	Stack name                   : a
	Region                       : us-west-2
	Confirm changeset            : False
	Disable rollback             : False
	Deployment s3 bucket         : xxx
	Capabilities                 : ["CAPABILITY_IAM"]
	Parameter overrides          : {}
	Signing Profiles             : {}

Initiating deployment
=====================
2022-09-07 09:32:29,100 | No Parameters detected in the template
2022-09-07 09:32:29,111 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-09-07 09:32:29,111 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-09-07 09:32:29,112 | 0 stacks found in the template
2022-09-07 09:32:29,112 | No Parameters detected in the template
2022-09-07 09:32:29,123 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-09-07 09:32:29,123 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-09-07 09:32:29,124 | 2 resources found in the stack 
2022-09-07 09:32:29,618 | File with same data already exists at a/abca8698c473c7669e43b734e0904d9b.template, skipping upload

Waiting for changeset to be created..
CloudFormation stack changeset
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                     LogicalResourceId                             ResourceType                                  Replacement                                 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
* Modify                                      HelloWorldFunction                            AWS::Lambda::Function                         False                                       
* Modify                                      ServerlessRestApi                             AWS::ApiGateway::RestApi                      False                                       
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-west-2:xxx:changeSet/samcli-deploy1662568349/0f45cf88-10c7-4afb-a5af-902c5d49d516


2022-09-07 09:32:40 - Waiting for stack create/update to complete

CloudFormation events from stack operations (refresh every 0.5 seconds)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                                ResourceType                                  LogicalResourceId                             ResourceStatusReason                        
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
UPDATE_IN_PROGRESS                            AWS::CloudFormation::Stack                    a                                             User Initiated                              
UPDATE_IN_PROGRESS                            AWS::Lambda::Function                         HelloWorldFunction                            -                                           
UPDATE_COMPLETE                               AWS::Lambda::Function                         HelloWorldFunction                            -                                           
UPDATE_COMPLETE_CLEANUP_IN_PROGRESS           AWS::CloudFormation::Stack                    a                                             -                                           
UPDATE_COMPLETE                               AWS::CloudFormation::Stack                    a                                             -                                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CloudFormation outputs from deployed stack
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Outputs                                                                                                                                                                             
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
xxx                                                                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Successfully created/updated stack - a in us-west-2
```

### Expected result:

Expected `node_modules` to be copied.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 12
2. `sam --version`: 1.56.0
3. AWS region: `us-west-2`

`Add --debug flag to command you are running`

**Comment by jfuss** [comment] 2022-09-08 17:12
This is expected and by design. If you provide `-t`, you are telling SAM CLI to use that template. When using `sam build`, you do not need to provide the `-t` to commands (after `sam build`) is run, as commands will auto pick that "built" template and therefore built artifacts.

Closing as this is by design

**Closed by jfuss** 2022-09-08 17:12 UTC
Labels: type/bug

**Comment by ishidakeisuke0123** [comment] 2023-08-03 08:33
@jfuss 
Why is the design such that node_modules are not reflected in Lambda if the -t parameter is added?

**Comment by sgrillon14** [comment] 2023-11-15 10:13
Hello, is it a real big problem!  My git repository contain a stack in eu-west-1 and an other in us-east-1 (lambda@edge) so I have 2 template file so I use --template-file

In Python, this case work it (requirement.txt)

**Comment by linudaar** [comment] 2024-01-12 13:31
I lost a day in my life debugging this :-(. Adding a -t argument to reference a specific template file in the command should IMHO not impact how dependencies are being handled by sam cli.
