### ISSUE TITLE
`sam deploy` does not use specified S3 bucket in samconfig.toml

### ISSUE THREAD

**Issue by xirkus** [aws/aws-sam-cli#2599] opened 2021-02-08 18:31 UTC
### Description:
Attempting to use a previously configured S3 bucket for deployments by specifying the `s3_bucket` parameter in the `samconfig.toml` does not work.

### Steps to reproduce:

1. Create an S3 bucket with the same bucket policy as the SAM CLI's dynamically created default source bucket.
1. Update your `samconfig.toml` to include this new bucket's ARN: `s3_bucket = "arn:aws:s3:::bucket-name"` (although I tried with the bucket name as well)
1. Run `sam build --guided`. 

### Observed result:

Note the `Deployment s3 bucket` in the output provided:

```
Deploying with following values
===============================
Stack name                         : process-lambda
Region                                 : us-east-1
Confirm changeset            : True
Deployment image repository  : 
                                       {
                                           "ProcessFunction": "834609584094.dkr.ecr.us-east-1.amazonaws.com/dev-scrb-process"
                                       }
Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-1w6spftg6a31d <<<<
Capabilities                           : ["CAPABILITY_IAM"]
Parameter overrides            : {}
Signing Profiles                    : {}
```

### Expected result:

The `Deployment s3 bucket` should use the supplied `s3_bucket` value configured in the `samconfig.toml` file (either `arn:aws:s3:::bucket-name` or `bucket-name`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:MacOS
2. SAM CLI, version 1.17.0
3. AWS region: us-east-1

**Comment by sriram-mv** [comment] 2021-02-17 18:18
I'm closing this issue as I could not reproduce it with the latest version of the SAM CLI. Please comment if you are still experiencing this.

**Closed by sriram-mv** 2021-02-17 18:18 UTC
Labels: area/config, area/deploy

**Comment by vincentluan** [comment] 2021-07-13 05:07
I'm still experiencing this with SAM CLI 1.26.0 on Amazon Linux 2 OS

**Comment by hakiour** [comment] 2022-07-01 08:52
The issue is still happening on SAM CLI v1.37.0

**Comment by bytesbiter** [comment] 2022-09-24 17:44
Still facing this issue with SAM CLI v1.55.0

**Comment by warrior8792** [comment] 2022-12-01 21:38
I believe this still exists in SAM CLI v1.66.0

**Comment by pedroGenio** [comment] 2023-03-29 03:06
same issue SAM CLI, version 1.73.0

**Comment by Axe--** [comment] 2024-06-30 05:51
Works fine apparently without the `--guided` flag
