### ISSUE TITLE
Docker tag is munged

### ISSUE THREAD

**Issue by xirkus** [aws/aws-sam-cli#2600] opened 2021-02-07 20:14 UTC
### Description:

I'm deploying an imaged based lambda function and specify the tag using the appropriate metadata in my `template.yaml`:

```
      DockerTag: v1
      DockerContext: ./function
      Dockerfile: Dockerfile
```

When this image is built using `sam build`, the docker image created adheres to the following name:

```
% docker images
REPOSITORY                                                TAG                     IMAGE ID            CREATED         SIZE
process                                                         v1                        4d8ff64bb5b8   20 hours ago   3.13GB
```

However, when `sam deploy --guided` is invoked, the following image name is used:

```
 % docker images
REPOSITORY                                                                                              TAG                                           IMAGE ID            CREATED        
  SIZE
8xxxxxxxxxx4.dkr.ecr.us-east-1.amazonaws.com/dev-scrb-process   process-4d8ff64bb5b8-v1   4d8ff64bb5b8   20 hours ago   3.13GB
process                                                         v1                        4d8ff64bb5b8   20 hours ago   3.13GB
```

### Steps to reproduce:

Create a Docker image function to deploy with the metadata mentioned above.

### Observed result:

See Description.

### Expected result:

Shouldn't the image push be: `8xxxxxxxxxx4.dkr.ecr.us-east-1.amazonaws.com/dev-scrb-process:v1` (which is what I was expecting? Why is the function name and another identifier prefix included in the image tag?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
2. `SAM CLI, version 1.16.0`
3. AWS region: us-east-1

**Comment by xirkus** [comment] 2021-02-08 20:04
@jfuss Sorry about that. Thought that these were related. Will do so going forward.

**Comment by jfuss** [comment] 2021-02-09 18:03
@xirkus No worries. They are slightly related but one is for the SAM Spec vs the CLI.

In regards to your issue, this behavior is by design. When we upload to ECR, we add extra data to all different functions to be in the same ECR repo. We also add part of the sha (the "other identifier") to the tag to allow redeployment on Lambda. Otherwise the image is the "same" and Lambda will not get updates. 

Closing as this is by design.

**Closed by jfuss** 2021-02-09 18:03 UTC
Labels: area/deploy, area/docker, stage/needs-investigation

**Comment by xirkus** [comment] 2021-02-09 21:32
Thanks for the clarification @jfuss !

**Comment by xirkus** [comment] 2021-02-10 19:09
@jfuss Just finished listening to the Serverless Office Hours and the issue of single vs. multiple ECR repos was discussed. It seems that Docker registries are designed to store a single image which implies that each Lambda container image should have it's own ECR repo. Instead, what you're suggesting with this use case is that a single ECR repo is being used for different Lambda function images which are referred to by tag. 

Is this correct? 

The way I understand Docker registries is that tags are used to refer to versions of the same image (in this case the Lambda function being deployed). The current SAM use case treats the ECR like a bucket for all containerized Lambda functions (even if they are different).

**Comment by EvgeniGordeev** [comment] 2021-11-12 18:47
@jfuss Are there plans to give more control over the tag creation to end users? e.g. if one deploys the same code to 5 different environments why to create 5 different images in ECR.

**Comment by CGarces** [comment] 2023-03-20 17:26
this behavior also makes more difficult to use the Lifecycle Policy.
I think that someone should reconsider this approach  and give the end users to take control of this own tags.
