### ISSUE TITLE
Improved Lambda message formatting

### ISSUE THREAD

**Issue by BVMiko** [aws/aws-sam-cli#3577] opened 2022-01-12 11:06 UTC
### Describe your idea/feature/enhancement

Debugging by using the output of `aws-sam-cli` is very difficult to parse.  Log messages are already JSON output and consist of a standard format.  I'd like for aws-sam-cli to help improve readability of these messages by adding indentation and colors.

This would be inappropriate to do within the lambda itself because:
* JSON indentation within the Lambda would increase log message sizes
* Only the aws-sam-cli layer would be able to determine if it's being outputted to a tty (due to the docker container)

### Proposal

Parsing the output from the docker container, we can split on newlines and check if each line is valid JSON.  If so, it can be modified to be indented, and colored depending on the log level of each message.

### Additional Details
I have an implementation of this already, will submit a PR shortly.

**Comment by mildaniel** [comment] 2022-01-15 01:57
Thank you for your contribution! We really appreciate it. Once a PR is submitted we weigh it against our roadmap, do regression testing, make sure it’s backwards compatible and maintainable. Please watch this channel from more updates, and feel free to reach out.

**Comment by jfuss** [comment] 2022-08-31 15:39
Closing as duplicate of https://github.com/aws/aws-sam-cli/issues/327

**Closed by jfuss** 2022-08-31 15:39 UTC
Labels: type/feature
