### ISSUE TITLE
PackageType Image: Makefile & Multiple Function Patterns

### ISSUE THREAD

**Issue by metaskills** [aws/aws-sam-cli#2459] opened 2020-12-05 17:21 UTC
Using the Zip package format along with the `BuildMethod: makefile`, I was able to use the same build artifacts for multiple functions. For example, a Rails application duplicated to a background processing function for SQS events. Where the second script simply copies the directory from the first build.

```makefile
build-RailsLambda:
	cp -r . $(ARTIFACTS_DIR)
	$(ARTIFACTS_DIR)/bin/build-rails "$(ARTIFACTS_DIR)"

build-JobsLambda:
	./bin/build-jobs "$(ARTIFACTS_DIR)"
```

```shell
#!/usr/bin/env bash
set -e
ARTIFACTS_DIR=$1
cd "$ARTIFACTS_DIR"
cp -r ../RailsLambda/. .
```

When using the `PackageType: Image` I was sad to find that the `BuildMethod: makefile` was not used. I really liked how the copy source builder setup a clean directory for me and my first request would be:

#### Can `BuildMethod: makefile` be run even when `PackageType: Image` is set?

This would allow me to set `DockerContext: ./.aws-sam/RailsLambda` and my `Dockerfile` would simply be:

```dockerfile
FROM public.ecr.aws/lambda/ruby:2.7
COPY . .
```

Cool right? Without it, I am now forced to mimic what the lambda builder was doing for me automatically. I'd like to stop doing that.

```shell
RESOURCE="RailsLambda"
SAM_TEMP=$(mktemp -d -t sam.XXXXXX)
rm -rf ./.lamby ./.aws-sam
cp -r . "$SAM_TEMP"
mkdir -p ./.lamby
cp -r "$SAM_TEMP" "./.lamby/$RESOURCE"
pushd "./.lamby/$RESOURCE"
```

Now for my second question to where I was using Makefile support to create the same deployment artifact for a jobs/worker function using the same code from the web function:

#### Has the SAM team thought about patterns to use the same container across functions?

For the beginner needing this pattern I am suggesting they use the same function for both events. Something like this:

```yaml
Events:
  HttpApiProxy:
    Type: HttpApi
    Properties:
      ApiId: !Ref RailsHttpApi
  SQSJobs:
    Type: SQS
    Properties:
      Queue: !GetAtt JobsQueue.Arn
      BatchSize: 1
```

However, I want to have patterns for both ZIP and Image to use distinct functions but for Image it would be the same ECR image. Any thoughts on how to handle this now? One **blocker* I see from the get go is that the [app_builder.py](https://github.com/aws/aws-sam-cli/blob/master/samcli/lib/build/app_builder.py#L241) sets the `docker_tag` prefix to `function_name.lower()`. 

Counterpoint, you could say that your job function likely needs it's own ECR image and that is a good pattern. I could buy that too... **but it would be much better if I had Makefile support since I could simply copy the Rails function's build directory for the Jobs without writing my own code.**  I think.

Any thoughts?

**Comment by jfuss** [comment] 2020-12-09 18:11
@metaskills 

> Can BuildMethod: makefile be run even when PackageType: Image is set?

So I think you are trying to fit a round peg into a square hole here.

When using a `PackageType:Image` the builder is a Dockerfile. There is only a single builder for a given function, what you are asking for is a multi-builder construct, which I don't fully understand why it's needed. We could come up with a way for a customer to use a Makefile to build an image, but the contract is super weird to me and at that point a Makefile is basically identical to a Dockerfile. The only main difference is that in a Makefile, you control what runs before or after an image is built. The same is achieved by running commands before or after `sam build`. I understand you and probably other customers have standardized on build workflows for zips but they really don't map to a image and why we currently only support building through a Dockerfile. This was we guarantee the output is an actually Image.

Building through Dockerfiles is much more reproducible and now you as a customer do not need to think about "does this new dependency need to be compiled within a container so it actually works on Lambda" because you are always going to be building in an environment/filesystem Lambda will run.

> Has the SAM team thought about patterns to use the same container across functions?

Personally, my take has always been isolated functions and not to try to combine things all into one. This is how SAM CLI generally operates (builds an artifact per-function and uploads an artifact per-function). To me nothing really changes between the package types. You can set the function to use the same image or build from the same dockerfile and adjust the entrypoint/command/env vars/working directory as needed.

**Comment by sriram-mv** [comment] 2021-02-18 00:03
As @jfuss has replied above, PackageType determines what your final artifact is. if you wanted to run your own commands for building when referencing `Image` PackageType, you can do so by adding that in the `Dockerfile`. I'm going to close this issue for now, lets re-open it if there are still unresolved issues from this pattern.

**Closed by sriram-mv** 2021-02-18 00:03 UTC
Labels: area/build, blocked/more-info-needed
