### ISSUE TITLE
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: X [ERROR] Could not resolve "/opt/nodejs/...

### ISSUE THREAD

**Issue by spc16670** [aws/aws-sam-cli#4424] opened 2022-11-17 07:51 UTC
### Description:

`sam build` generates the following error when trying to build a lambda function that imports TS files from a layer:

`Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: X [ERROR] Could not resolve "/opt/nodejs/app/src/service/abstract-service"`

This error is thrown only from 'sam build'. Running esbuild manually completes without any errors e.g.
`esbuild --bundle src/main.ts --platform=node --sourcemap --outdir=dist`

The tsconfig.json has the required mapping in 'paths' and the jests tests resolve /opt/nodejs starting imports correctly.

1. OS: Windows
2. `sam --version`: 1.64
3. AWS region: eu-west-1

`Add --debug flag to command you are running`

**Comment by mildaniel** [comment] 2022-11-17 23:07
Thanks for reporting the issue, I'll take a closer look. Are you able to provide a reproducible example to make it easier for us to debug?

**Comment by spc16670** [comment] 2022-11-18 07:51
Here is my project: https://github.com/spc16670/issues/raw/main/seraphin.zip

**Comment by mildaniel** [comment] 2022-11-18 19:18
Hey @spc16670, thanks for providing the project, it really helped. The issue here is that the builder moves the source code to a scratch directory before bundling, breaking the path defined in the tsconfig. We're aware of this as a limitation currently and are working towards a solution. 

Two potential workarounds are:
1. Use absolute paths in the tsconfig.json
2. In the tsconfig.json paths, do something like
```
"paths": {
        "/opt/nodejs/*": [
          "./common-js/*"
        ]
      }
```
in the package.json add a script to copy the layer contents into the codeuri before building (since we're bundling anyways, this shouldn't affect the deployed package size)
```
"cp -r ../../seraphin-common/layers/common-js . && samdev build -t ../template.yaml && rm -rf ./common-js && mv ./.aws-sam ../"
```
And then build the project from ./app using `npm run build`

**Comment by spc16670** [comment] 2022-11-19 10:27
That's great we know exactly where the issue is.

Unfortunately none of the suggestions really works :(
1) Just can't do it, every other developer would have to change this
2) Other that being super messy it just doesn't work as it presents all sorts of issues when trying to get all the tooling to work with this

Is there a ticket a ticket already that captures this issue I can track?

**Comment by mildaniel** [comment] 2022-11-21 17:06
I understand the difficulty with these workarounds. We'll create a main issue where we can track this and consolidate some similar issues that I'll link here. 

Really appreciate the feedback!

**Comment by spc16670** [comment] 2022-12-13 03:56
Hey, have you had a chance to create the issue?

**Comment by mndeveci** [comment] 2023-01-10 22:54
We haven't created the issue yet, we will update this thread once the issue is created. Thanks for your patience.

**Comment by torresxb1** [comment] 2023-01-12 22:23
Closing so that we can track in the above issue (`Feature request: Build in source`). There's multiple open issues relating to similar problems, so we want to have a central place to track.

**Closed by torresxb1** 2023-01-12 22:23 UTC
Labels: type/feature, area/build, area/esbuild
