### ISSUE TITLE
No module named 'samtranslator.utils.py27hash_fix'

### ISSUE THREAD

**Issue by underdog681** [aws/aws-sam-cli#3824] opened 2022-04-20 16:17 UTC
### Description:
After installing sam cli via brew I get the following error when running 'sam --version'
I am using these instructions https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 5, in <module>
    from samcli.cli.main import cli
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 11, in <module>
    from samcli.lib.telemetry.metric import send_installed_metric, emit_all_metrics
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 20, in <module>
    from samcli.commands._utils.experimental import get_all_experimental_statues
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/experimental.py", line 14, in <module>
    from samcli.commands._utils.options import parameterized_option
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/options.py", line 13, in <module>
    from samcli.commands._utils.template import get_template_data, TemplateNotFoundException
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/template.py", line 15, in <module>
    from samcli.yamlhelper import yaml_parse, yaml_dump
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/yamlhelper.py", line 24, in <module>
    from samtranslator.utils.py27hash_fix import Py27Dict, Py27UniStr
ModuleNotFoundError: No module named 'samtranslator.utils.py27hash_fix'

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Monterey v 12.3
2. If using SAM CLI, `sam --version`: Not available 
3. AWS region: us-west-2

`Add --debug flag to any SAM CLI commands you are running`

**Comment by moelasmar** [comment] 2022-04-20 21:35
I was not able to reproduce this issue.
can you run this command 
```
ls -lrt /usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samtranslator/utils/
```
if the output does not contain the file `py27hash_fix.py`, so it seems something wrong happened during the installation.
Can you try to uninstall the current installed SAM CLI, and reinstall it again.

**Comment by underdog681** [comment] 2022-04-20 22:18
The output of that does show the file py27hash_fix.py. I have uninstalled and reinstalled SAM CLI time following https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html

Does this currently only support python2? With macOS Monterey 12.3 python2 has been completely removed

**Comment by underdog681** [comment] 2022-05-02 17:25
When I checked what version of aws-sam-translator I was running via pip I had 1.39.0. Via pip I uninstalled aws-sam-translator and reinstalled it via pip and am now running version 1.46.0 and sam cli is working

**Comment by jfuss** [comment] 2022-07-18 13:11
Looks like the issue was resolved and is working now. Going to close the issue but if this is still a problem, feel free to re-open or create a new issue and link to this one (as we don't tend to monitor closed issues).

**Closed by jfuss** 2022-07-18 13:11 UTC
Labels: area/installation, stage/needs-investigation, stage/bug-repro, maintainer/need-followup, platform/mac/arm

**Comment by jasonterando** [comment] 2022-08-08 15:37
FWIW - ran into a similar issue.  `pip3 install aws-sam-cli --upgrade` resolved for me.
