### ISSUE TITLE
--log-file does not output to file until exit the run

### ISSUE THREAD

**Issue by guoliang** [aws/aws-sam-cli#2669] opened 2021-03-01 12:23 UTC
### Description:
I have started SAM with following command
> sam local start-api --skip-pull-image --warm-containers LAZY --log-file debug.log

It does not output to file until I exit the run. Is it suppose to work like that?
I personally would see that it output to log each every time I call it rather than the need to exit first.

### Steps to reproduce:
Start API with above command

### Observed result:
Does not output to debug.log until exit SAM

### Expected result:
Should output to log after each request.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. SAM CLI 1.15.0
3. AWS region: local

**Comment by hawflau** [comment] 2021-03-01 17:44
Transferring this issue to SAM CLI  as it's related to `sam local start-api`

**Comment by yskkin** [comment] 2021-03-04 02:57
related to #1985, reproduced on my laptop.

**Comment by jfuss** [comment] 2022-08-13 02:46
Closing as a duplicate of #1985

**Closed by jfuss** 2022-08-13 02:46 UTC
Labels: type/question, area/local/start-api, stage/pr, maintainer/need-followup
