### ISSUE TITLE
sam local invoke adds empty AWS_SESSION_TOKEN environment variable

### ISSUE THREAD

**Issue by twasink** [aws/aws-sam-cli#3118] opened 2021-07-26 13:12 UTC
### Update:

The problem is caused by the presence of an empty `AWS_SESSION_TOKEN` in the environment of the process being run in the docker container. This may or may not result in an `X-Amz-Security-Token` being added to calls to AWS services, depending on the implementation details of the SDK and version being used. In turn, an empty `X-Amz-Security-Token` may or may not get flagged as an invalid token depending on the HTTP protocol used (and possibly the service being accessed)

### Description:
Some APIs don't work with the credential provided by the `sam local invoke` (and, presumably, `sam local start-api`). The APIs seem to differ by language. This is possibly the root cause behind bugs such as #3071 and #2963. The error reported (when it is reported) is `The security token included in the request is invalid`

I've attached a sample project with two simple SAM apps. One is in Node/JavaScript, the other is in Ruby. They both contain two simple functions – one that lists all S3 buckets, and one that lists all OpsWorks stacks. In both, the S3 buckets can be listed. But only the JavaScript one retrieves the stacks – the Ruby version can't create the client correctly.

### Steps to reproduce:
1) Unpack the provided `sam_local_bug.zip` file.
2) Go into `sam_local_bug\node_version`
3) Run `sam build && sam local invoke S3Test`. This should pass.
4) Run `sam build && sam local invoke OpsworksTest`. This should pass.
5) Change to the `sam_local_bug\ruby_version`
6) Run `sam build && sam local invoke S3Test`. This should pass.
7) Run `sam build && sam local invoke OpsworksTest`. This should fail.

### Observed result:
The output should look like this:
```
2021-07-26 23:09:32,970 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-26 23:09:32,971 | Using config file: samconfig.toml, config environment: default
2021-07-26 23:09:32,971 | Expand command line arguments to:
2021-07-26 23:09:32,971 | --template_file=<mydir>/sam_local_bug/ruby_version/.aws-sam/build/template.yaml --function_logical_id=OpsworksTest --no_event --layer_cache_basedir=<mydir>/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2021-07-26 23:09:32,971 | local invoke command is called
2021-07-26 23:09:32,975 | No Parameters detected in the template
2021-07-26 23:09:32,994 | 3 stacks found in the template
2021-07-26 23:09:32,994 | No Parameters detected in the template
2021-07-26 23:09:33,010 | 3 resources found in the stack 
2021-07-26 23:09:33,010 | No Parameters detected in the template
2021-07-26 23:09:33,026 | Found Serverless function with name='S3Test' and CodeUri='S3Test'
2021-07-26 23:09:33,026 | --base-dir is not presented, adjusting uri S3Test relative to <mydir>/sam_local_bug/ruby_version/.aws-sam/build/template.yaml
2021-07-26 23:09:33,026 | Found Serverless function with name='OpsworksTest' and CodeUri='OpsworksTest'
2021-07-26 23:09:33,026 | --base-dir is not presented, adjusting uri OpsworksTest relative to <mydir>/sam_local_bug/ruby_version/.aws-sam/build/template.yaml
2021-07-26 23:09:33,033 | Found one Lambda function with name 'OpsworksTest'
2021-07-26 23:09:33,033 | Invoking opsworksTest.lambda_handler (ruby2.7)
2021-07-26 23:09:33,033 | No environment variables found for function 'OpsworksTest'
2021-07-26 23:09:33,033 | Environment variables overrides data is standard format
2021-07-26 23:09:33,033 | Loading AWS credentials from session with profile 'None'
2021-07-26 23:09:33,042 | Resolving code path. Cwd=<mydir>/sam_local_bug/ruby_version/.aws-sam/build, CodeUri=<mydir>/sam_local_bug/ruby_version/.aws-sam/build/OpsworksTest
2021-07-26 23:09:33,042 | Resolved absolute path to code is <mydir>/sam_local_bug/ruby_version/.aws-sam/build/OpsworksTest
2021-07-26 23:09:33,042 | Code <mydir>/sam_local_bug/ruby_version/.aws-sam/build/OpsworksTest is not a zip/jar file
2021-07-26 23:09:33,054 | Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-ruby2.7:rapid-1.26.0.

2021-07-26 23:09:33,054 | Mounting <mydir>/sam_local_bug/ruby_version/.aws-sam/build/OpsworksTest as /var/task:ro,delegated inside runtime container
2021-07-26 23:09:33,314 | Starting a timer for 3 seconds for function 'OpsworksTest'
START RequestId: 5707bb42-bbcf-4292-81b4-1769abc51162 Version: $LATEST
Error raised from handler method
{
  "errorMessage": "The security token included in the request is invalid.",
  "errorType": "Function<Aws::OpsWorks::Errors::UnrecognizedClientException>",
  "stackTrace": [
    "/var/runtime/gems/aws-sdk-core-3.114.3/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.114.3/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.114.3/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.114.3/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.114.3/lib/seahorse/client/plugins/request_callback.rb:71:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.114.3/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.114.3/lib/seahorse/client/plugins/response_target.rb:24:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.114.3/lib/seahorse/client/request.rb:72:in `send_request'",
    "/var/runtime/gems/aws-sdk-opsworks-1.32.0/lib/aws-sdk-opsworks/client.rb:3534:in `describe_stacks'",
    "/var/task/opsworksTest.rb:33:in `lambda_handler'"
  ]
}
END RequestId: 5707bb42-bbcf-4292-81b4-1769abc51162
REPORT RequestId: 5707bb42-bbcf-4292-81b4-1769abc51162	Init Duration: 0.10 ms	Duration: 1576.66 ms	Billed Duration: 1600 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
2021-07-26 23:09:35,062 | Cleaning all decompressed code dirs
2021-07-26 23:09:35,062 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '5fc6b3af-07d4-4594-9e80-f074b0d03661', 'installationId': '0673bfa5-1b1f-4f86-bfb2-9b8350b6c438', 'sessionId': 'b9137f15-9a01-4e18-9900-6b3f303c0457', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.11', 'samcliVersion': '1.26.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 2091, 'exitReason': 'success', 'exitCode': 0}}]}
2021-07-26 23:09:35,888 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
{"errorMessage":"The security token included in the request is invalid.","errorType":"Function<Aws::OpsWorks::Errors::UnrecognizedClientException>","stackTrace":["/var/runtime/gems/aws-sdk-core-3.114.3/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'","/var/runtime/gems/aws-sdk-core-3.114.3/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'","/var/runtime/gems/aws-sdk-core-3.114.3/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'","/var/runtime/gems/aws-sdk-core-3.114.3/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'","/var/runtime/gems/aws-sdk-core-3.114.3/lib/seahorse/client/plugins/request_callback.rb:71:in `call'","/var/runtime/gems/aws-sdk-core-3.114.3/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'","/var/runtime/gems/aws-sdk-core-3.114.3/lib/seahorse/client/plugins/response_target.rb:24:in `call'","/var/runtime/gems/aws-sdk-core-3.114.3/lib/seahorse/client/request.rb:72:in `send_request'","/var/runtime/gems/aws-sdk-opsworks-1.32.0/lib/aws-sdk-opsworks/client.rb:3534:in `describe_stacks'","/var/task/opsworksTest.rb:33:in `lambda_handler'"]}2021-07-26 23:09:35,889 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-26 23:09:35,889 | Sending Telemetry: {'metrics': [{'runtimeMetric': {'requestId': '29321452-4b76-4d24-b1d1-b1d53be778ef', 'installationId': '0673bfa5-1b1f-4f86-bfb2-9b8350b6c438', 'sessionId': 'b9137f15-9a01-4e18-9900-6b3f303c0457', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.11', 'samcliVersion': '1.26.0', 'runtimes': ['ruby2.7']}}]}
2021-07-26 23:09:36,690 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### Expected result:

Something more like this (for the JavaScript version):
```
2021-07-26 23:06:53,426 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-26 23:06:53,427 | Using config file: samconfig.toml, config environment: default
2021-07-26 23:06:53,427 | Expand command line arguments to:
2021-07-26 23:06:53,427 | --template_file=<mydir>/sam_local_bug/node_version/.aws-sam/build/template.yaml --function_logical_id=OpsworksTest --no_event --layer_cache_basedir=<mydir>/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2021-07-26 23:06:53,427 | local invoke command is called
2021-07-26 23:06:53,440 | No Parameters detected in the template
2021-07-26 23:06:53,459 | 3 stacks found in the template
2021-07-26 23:06:53,459 | No Parameters detected in the template
2021-07-26 23:06:53,476 | 3 resources found in the stack 
2021-07-26 23:06:53,476 | No Parameters detected in the template
2021-07-26 23:06:53,492 | Found Serverless function with name='S3Test' and CodeUri='S3Test'
2021-07-26 23:06:53,492 | --base-dir is not presented, adjusting uri S3Test relative to <mydir>/sam_local_bug/node_version/.aws-sam/build/template.yaml
2021-07-26 23:06:53,492 | Found Serverless function with name='OpsworksTest' and CodeUri='OpsworksTest'
2021-07-26 23:06:53,492 | --base-dir is not presented, adjusting uri OpsworksTest relative to <mydir>/sam_local_bug/node_version/.aws-sam/build/template.yaml
2021-07-26 23:06:53,499 | Found one Lambda function with name 'OpsworksTest'
2021-07-26 23:06:53,499 | Invoking src/handlers/opsworksTest.opsworksTest (nodejs14.x)
2021-07-26 23:06:53,499 | No environment variables found for function 'OpsworksTest'
2021-07-26 23:06:53,500 | Environment variables overrides data is standard format
2021-07-26 23:06:53,500 | Loading AWS credentials from session with profile 'None'
2021-07-26 23:06:53,508 | Resolving code path. Cwd=<mydir>/sam_local_bug/node_version/.aws-sam/build, CodeUri=<mydir>/sam_local_bug/node_version/.aws-sam/build/OpsworksTest
2021-07-26 23:06:53,508 | Resolved absolute path to code is <mydir>/sam_local_bug/node_version/.aws-sam/build/OpsworksTest
2021-07-26 23:06:53,508 | Code <mydir>/sam_local_bug/node_version/.aws-sam/build/OpsworksTest is not a zip/jar file
2021-07-26 23:06:53,521 | Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-nodejs14.x:rapid-1.26.0.

2021-07-26 23:06:53,521 | Mounting <mydir>/sam_local_bug/node_version/.aws-sam/build/OpsworksTest as /var/task:ro,delegated inside runtime container
2021-07-26 23:06:53,806 | Starting a timer for 60 seconds for function 'OpsworksTest'
START RequestId: 989cd964-4474-4255-bcda-c0265a9b4045 Version: $LATEST
END RequestId: 989cd964-4474-4255-bcda-c0265a9b4045
REPORT RequestId: 989cd964-4474-4255-bcda-c0265a9b4045	Init Duration: 0.14 ms	Duration: 2310.45 ms	Billed Duration: 2400 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
2021-07-26 23:06:56,283 | Cleaning all decompressed code dirs
2021-07-26 23:06:56,284 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '86949428-7492-4469-9707-be2a8509e1a0', 'installationId': '0673bfa5-1b1f-4f86-bfb2-9b8350b6c438', 'sessionId': 'e07b20e0-5658-41c0-8f52-eb49668fab2b', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.11', 'samcliVersion': '1.26.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 2856, 'exitReason': 'success', 'exitCode': 0}}]}
2021-07-26 23:06:57,058 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
{"Stacks":[...]}
2021-07-26 23:06:57,058 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-26 23:06:57,058 | Sending Telemetry: {'metrics': [{'runtimeMetric': {'requestId': 'aac28041-4f07-49c9-aad7-0b7a57fe9950', 'installationId': '0673bfa5-1b1f-4f86-bfb2-9b8350b6c438', 'sessionId': 'e07b20e0-5658-41c0-8f52-eb49668fab2b', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.11', 'samcliVersion': '1.26.0', 'runtimes': ['nodejs14.x']}}]}
2021-07-26 23:06:57,821 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.4
2. `sam --version`: SAM CLI, version 1.26.0
3. AWS region: us-east-1

`Add --debug flag to command you are running`

**Comment by twasink** [comment] 2021-07-26 13:14
[sam_local_bug.zip](https://github.com/aws/aws-sam-cli/files/6878443/sam_local_bug.zip)

**Comment by twasink** [comment] 2021-07-27 01:52
Some extra information, by turning on the wire trace – it looks like the security credentials are passed in, BUT it's not necessarily working. In particular, there's an empty security token.

Here's the POST request for the (working) S3 call (formatted for readability):
```
POST / HTTP/1.1
Content-Type: application/x-amz-json-1.1
Accept-Encoding: 
User-Agent: aws-sdk-ruby3/3.114.3 ruby/2.7.3 x86_64-linux aws-sdk-opsworks/1.32.0 exec-env/AWS_Lambda_ruby2.7
X-Amz-Target: OpsWorks_20130218.DescribeStacks
Host: opsworks.us-east-1.amazonaws.com
X-Amz-Date: 20210727T013445Z
X-Amz-Security-Token: 
X-Amz-Content-Sha256: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
Authorization: AWS4-HMAC-SHA256
    Credential=[REDACTED]/20210727/us-east-1/opsworks/aws4_request,
    SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-target,
    Signature=f6d015cec491128935d34c32a203f47746383c49751b84f531730581e7364950
Content-Length: 2
Accept: */*
```

Note the 'x-amz-security-token` header. Also note that this is a GET.

Here's the (not working) Opsworks call:
```
POST / HTTP/1.1
Content-Type: application/x-amz-json-1.1
Accept-Encoding: 
User-Agent: aws-sdk-ruby3/3.117.0 ruby/2.7.4 x86_64-darwin20 aws-sdk-opsworks/1.32.0
X-Amz-Target: OpsWorks_20130218.DescribeStacks
Host: opsworks.us-east-1.amazonaws.com
X-Amz-Date: 20210727T013647Z
X-Amz-Content-Sha256: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
Authorization: AWS4-HMAC-SHA256
    Credential=[REDACTED]/20210727/us-east-1/opsworks/aws4_request,
    SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-target,
    Signature=f36587c912f804f771ca7a8270da7c19229df55ab3d526f22586c1ee8f2b100f
Content-Length: 2
Accept: */*
```

This returns a HTTP 400 error, with an `UnrecognizedClientException`.

Now, here's a call down in the REPL:
```
$ aws-v3.rb
[1] pry(Aws)> opsworks = Aws::OpsWorks::Client.new(http_wire_trace: true)
=> #<Aws::OpsWorks::Client>
[2] pry(Aws)> opsworks.describe_stacks.stacks
opening connection to opsworks.us-east-1.amazonaws.com:443...
opened
starting SSL for opsworks.us-east-1.amazonaws.com:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "POST / HTTP/1.1
  Content-Type: application/x-amz-json-1.1
  Accept-Encoding: 
  User-Agent: aws-sdk-ruby3/3.117.0 ruby/2.7.4 x86_64-darwin20 aws-sdk-opsworks/1.32.0
  X-Amz-Target: OpsWorks_20130218.DescribeStacks
  Host: opsworks.us-east-1.amazonaws.com
  X-Amz-Date: 20210727T014757Z
  X-Amz-Content-Sha256: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
  Authorization: AWS4-HMAC-SHA256 
    Credential=[REDACTED]/20210727/us-east-1/opsworks/aws4_request,
    SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-target,
    Signature=9973ae58a5b96cb6515ec5818adf713e9b6e2232f3537d7edc0d80464c0c90f7
  Content-Length: 2
  Accept: */*
  "
-> "HTTP/1.1 200 OK\r\n"
...
```

So the difference between the working S3 and the not working Opsworks call seems to be GET vs POST, which in turn implies a difference in the authorisers on the servers (not something the SAM CLI team can deal with). But the difference between the not working local Lambda call and the working REPL call is the presence of the empty `X-Amz-Security-Token` – which is.

Suggested workaround: don't include the security token credential if it's not provided.

**Comment by twasink** [comment] 2021-07-27 02:02
As a further proof of this: adding `ENV.delete('AWS_SESSION_TOKEN')` to the lambda prior to creating the client prevents the header being added to the request, and the request then returns successfully.

Changing the title of the issue accordingly,.

**Comment by twasink** [comment] 2021-07-27 02:14
It looks like this check isn't working?  https://github.com/aws/aws-sam-cli/blame/develop/samcli/local/lambdafn/env_vars.py#L173

**Comment by sriram-mv** [comment] 2021-07-27 20:22
@twasink I retried to reproduce this, but couldn't.

I setup my credentials through env vars with AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN.

Here's the output I see when running with ruby2.7 for `OpsworksTest`

```
2021-07-27 13:18:05,289 | Using config file: samconfig.toml, config environment: default
2021-07-27 13:18:05,289 | Expand command line arguments to:
2021-07-27 13:18:05,289 | --template_file=/<mypath>/sam_local_bug/ruby_version/.aws-sam/build/template.yaml --function_logical_id=OpsworksTest --no_event --layer_cache_basedir=/Users/srirammv/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1
2021-07-27 13:18:05,289 | local invoke command is called
2021-07-27 13:18:05,295 | No Parameters detected in the template
2021-07-27 13:18:05,318 | 3 stacks found in the template
2021-07-27 13:18:05,318 | No Parameters detected in the template
2021-07-27 13:18:05,337 | 3 resources found in the stack
2021-07-27 13:18:5,337 | No Parameters detected in the template
2021-07-27 13:18:05,356 | Found Serverless function with name='S3Test' and CodeUri='S3Test'
2021-07-27 13:18:05,356 | --base-dir is not presented, adjusting uri S3Test relative to /<mypath>/sam_local_bug/ruby_version/.aws-sam/build/template.yaml
2021-07-27 13:18:05,356 | Found Serverless function with name='OpsworksTest' and CodeUri='OpsworksTest'
2021-07-27 13:18:05,356 | --base-dir is not presented, adjusting uri OpsworksTest relative to /<mypath>/sam_local_bug/ruby_version/.aws-sam/build/template.yaml
2021-07-27 13:18:05,368 | Found one Lambda function with name 'OpsworksTest'
2021-07-27 13:18:05,368 | Invoking opsworksTest.lambda_handler (ruby2.7)
2021-07-27 13:18:05,368 | No environment variables found for function 'OpsworksTest'
2021-07-27 13:18:05,368 | Environment variables overrides data is standard format
2021-07-27 13:18:05,368 | Loading AWS credentials from session with profile 'None'
2021-07-27 13:18:05,378 | Resolving code path. Cwd=/<mypath>/sam_local_bug/ruby_version/.aws-sam/build, CodeUri=/<mypath>/sam_local_bug/ruby_version/.aws-sam/build/OpsworksTest
2021-07-27 13:18:05,379 | Resolved absolute path to code is /<mypath>/sam_local_bug/ruby_version/.aws-sam/build/OpsworksTest
2021-07-27 13:18:05,379 | Code /<mypath>/sam_local_bug/ruby_version/.aws-sam/build/OpsworksTest is not a zip/jar file
2021-07-27 13:18:05,396 | Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-ruby2.7:rapid-1.27.2.

2021-07-27 13:18:05,396 | Mounting /<mypath>/sam_local_bug/ruby_version/.aws-sam/build/OpsworksTest as /var/task:ro,delegated inside runtime container
2021-07-27 13:18:05,730 | Starting a timer for 3 seconds for function 'OpsworksTest'
START RequestId: 2ae74724-554e-46e0-a16a-5d5d239cf13d Version: $LATEST
END RequestId: 2ae74724-554e-46e0-a16a-5d5d239cf13d
REPORT RequestId: 2ae74724-554e-46e0-a16a-5d5d239cf13d	Init Duration: 0.17 ms	Duration: 1473.64 ms	Billed Duration: 1500 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
2021-07-27 13:18:07,396 | Cleaning all decompressed code dirs
```

What am I missing?

**Comment by twasink** [comment] 2021-07-27 21:38
Hmm. I note that it's a different version of the docker image - 1.27.2, instead of 1.26. That may be it.  I'll update and see.

**Comment by twasink** [comment] 2021-07-27 21:49
Nope. Still happening under 1.27.2.

You said that you set up environment variables, including `AWS_SESSION_TOKEN`? That may be the problem. In my scenario, I'm getting credentials from my `~/.aws/credentials file`, and I'm not using a session token. The bug is that the Ruby program running inside the docker container then has a _blank_ `AWS_SESSION_TOKEN` environment variable, which then causes problems with how the Ruby SDK constructs credentials from environment variables.

I would expect that it works correctly if you do pass in a valid `AWS_SESSION_TOKEN`.

If you enable the wire trace, you'll see the output. Change this line in the Ruby code:

```
  opsworks = Aws::OpsWorks::Client.new()
```

to this:

```
  opsworks = Aws::OpsWorks::Client.new(http_wire_trace: true)
```

**Comment by twasink** [comment] 2021-07-27 22:47
Also, to clarify further: it looks like the docker container is being launched without an `AWS_SESSION_TOKEN` variable (e.g. it's being launched correctly), but by the time it gets into the Ruby process, the blank variable has been inserted.

**Comment by sriram-mv** [comment] 2021-08-01 22:27
@twasink That helps, thanks for the context, how have you setup your credentials in your ~/.aws/credentials file?

**Comment by twasink** [comment] 2021-08-01 22:39
That's correct.

```
[default]
aws_access_key_id=<REDACTED>
aws_secret_access_key=<REDACTED>
```

**Comment by twasink** [comment] 2021-08-01 22:44
From examining the issue more, it's almost certainly an issue with the lambci/lambda docker image. The scripts in the image kick off the mock lambda environment passing in environment variables, without checking if the environment is set or not. Thus, in the lambda's runtime, the AWS_SESSION_TOKEN is set to a null or blank value.

In turn, the different lambda runtimes treat this differently. Some insect the value for truthiness, others look for the presence of the key.

So it ends up being a multi-layered bug: the SAM CLI initiates it by switching from whatever credentials the user has to using environment variables, the lambci/lambda image makes it worse by setting environment variables in the lambda runtime that weren't passed to the Docker container, and the lambda runtime has inconsistent behaviour (across implementations) on how to deal with that.

**Comment by sriram-mv** [comment] 2021-08-01 22:45
Thanks, set up my credentials similarly and was able to reproduce it. Did some tracing through the code base, and also set up breakpoints within SAM CLI, when the container is started up and ran via SAM CLI it does **not** have AWS_SESSION_TOKEN set up. I'm starting to suspect something within the image on how the ruby runtime treats this.

**Comment by dtflowers** [comment] 2021-08-05 20:41
We've also encountered this issue. This thread was quite informative and matches what we're seeing exactly.  Thank you for the help and +1 for the need to patch this bug.

**Comment by xazhao** [comment] 2021-08-16 04:49
Thanks for posting the issue. I already added it to our backlog. Will post updates here when we start working on a fix.

**Comment by qingchm** [comment] 2021-10-08 03:47
Closing this since I believe the issue has been resolved! @twasink Thanks for all the patient communications and let me know if you still have any problems! Welcome to reopen this anytime if you encounter this again

**Closed by qingchm** 2021-10-08 03:47 UTC
Labels: type/bug, area/local/invoke
