### ISSUE TITLE
Bug: sam local invoke - StoreError

### ISSUE THREAD

**Issue by huseyinkurtvestel** [aws/aws-sam-cli#5516] opened 2023-07-14 05:53 UTC
### Description:
Sam local invoke fails to run with error "docker-credential-desktop not installed or not available in PATH"

### Steps to reproduce:

Create a template file in any lambda root folder, run sam-local-invoke.

### Observed result:

2023-07-14 08:47:30,770 | Config file location:                                                                            
/home/ubuntu2204/Huseyin/omega/iot/node/Native/Apigateway/content/countries/samconfig.toml                                 
2023-07-14 08:47:30,773 | Config file                                                                                      
'/home/ubuntu2204/Huseyin/omega/iot/node/Native/Apigateway/content/countries/samconfig.toml' does not exist                
2023-07-14 08:47:30,778 | Using SAM Template at                                                                            
/home/ubuntu2204/Huseyin/omega/iot/node/Native/Apigateway/content/countries/template.yaml                                  
2023-07-14 08:47:30,820 | Using config file: samconfig.toml, config environment: default                                   
2023-07-14 08:47:30,822 | Expand command line arguments to:                                                                
2023-07-14 08:47:30,824 |                                                                                                  
--template_file=/home/ubuntu2204/Huseyin/omega/iot/node/Native/Apigateway/content/countries/template.yaml --no_event       
--layer_cache_basedir=/home/ubuntu2204/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2023-07-14 08:47:30,827 | local invoke command is called                                                                   
2023-07-14 08:47:30,831 | No Parameters detected in the template                                                           
2023-07-14 08:47:30,862 | There is no customer defined id or cdk path defined for resource GetHomeAppliancesService, so we 
will use the resource logical id as the resource id                                                                        
2023-07-14 08:47:30,864 | 0 stacks found in the template                                                                   
2023-07-14 08:47:30,865 | No Parameters detected in the template                                                           
2023-07-14 08:47:30,889 | There is no customer defined id or cdk path defined for resource GetHomeAppliancesService, so we 
will use the resource logical id as the resource id                                                                        
2023-07-14 08:47:30,891 | 1 resources found in the stack                                                                   
2023-07-14 08:47:30,892 | Found Serverless function with name='GetHomeAppliancesService' and                               
CodeUri='./content_country.zip'                                                                                            
2023-07-14 08:47:30,894 | --base-dir is not presented, adjusting uri ./content_country.zip relative to                     
/home/ubuntu2204/Huseyin/omega/iot/node/Native/Apigateway/content/countries/template.yaml                                  
2023-07-14 08:47:30,895 | Skip building zip function: GetHomeAppliancesService                                             
2023-07-14 08:47:30,906 | Found one Lambda function with name 'GetHomeAppliancesService'                                   
2023-07-14 08:47:30,908 | Invoking ./index.handler (nodejs16.x)                                                            
2023-07-14 08:47:30,910 | Loading AWS credentials from session with profile 'None'                                         
2023-07-14 08:47:30,930 | Resolving code path.                                                                             
Cwd=/home/ubuntu2204/Huseyin/omega/iot/node/Native/Apigateway/content/countries,                                           
CodeUri=/home/ubuntu2204/Huseyin/omega/iot/node/Native/Apigateway/content/countries/content_country.zip                    
2023-07-14 08:47:30,931 | Resolved absolute path to code is                                                                
/home/ubuntu2204/Huseyin/omega/iot/node/Native/Apigateway/content/countries/content_country.zip                            
2023-07-14 08:47:30,932 | Code                                                                                             
/home/ubuntu2204/Huseyin/omega/iot/node/Native/Apigateway/content/countries/content_country.zip is not a zip/jar file      
2023-07-14 08:47:30,939 | Local image was not found.                                                                       
2023-07-14 08:47:30,940 | Removing rapid images for repo public.ecr.aws/sam/emulation-nodejs16.x                           
Building image...docker/credentials/store.py:22: UserWarning: docker-credential-desktop not installed or not available in PATH
2023-07-14 08:47:30,973 | Cleaning all decompressed code dirs                                                              
2023-07-14 08:47:30,975 | Telemetry endpoint configured to be                                                              
https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics                                                     
2023-07-14 08:47:30,986 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId':                                     
'856a8cb1-2cc4-4602-9315-5e0ab8fa3ff0', 'installationId': '8f43aabf-2454-414a-ba0b-0c647eb24f99', 'sessionId':             
'313a42ad-d1d5-46eb-953e-a5495e4938bc', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.11.3', 'samcliVersion':
'1.90.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke',         
'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName':                                       
'e45d4cbade71ec65c6bf518246dc9bd75c5bf785b19a5fc727c2c3614dced1c0', 'initialCommit': None}, 'duration': 154, 'exitReason': 
'StoreError', 'exitCode': 255}}]}                                                                                          
2023-07-14 08:47:31,767 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443):    
Read timed out. (read timeout=0.1)                                                                                         

Error: docker-credential-desktop not installed or not available in PATH
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 184, in wrapped
  File "samcli/lib/telemetry/metric.py", line 149, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 95, in wrapper
  File "samcli/commands/local/invoke/cli.py", line 100, in cli
  File "samcli/commands/local/invoke/cli.py", line 206, in do_cli
  File "samcli/commands/local/lib/local_lambda.py", line 144, in invoke
  File "samcli/lib/telemetry/metric.py", line 324, in wrapped_func
  File "samcli/local/lambdafn/runtime.py", line 189, in invoke
  File "samcli/local/lambdafn/runtime.py", line 85, in create
  File "samcli/local/docker/lambda_container.py", line 94, in __init__
  File "samcli/local/docker/lambda_container.py", line 237, in _get_image
  File "samcli/local/docker/lambda_image.py", line 231, in build
  File "samcli/local/docker/lambda_image.py", line 330, in _build_image
  File "docker/api/build.py", line 262, in build
  File "docker/api/build.py", line 309, in _set_auth_headers
  File "docker/auth.py", line 300, in get_all_credentials
  File "docker/credentials/store.py", line 70, in list
  File "docker/credentials/store.py", line 75, in _execute

An unexpected error was encountered while executing "sam local invoke".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20local%20invoke%20-%20StoreError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20local%20invoke%20-%20StoreError

### Expected result:
Expecting to get a return value from lambda.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04.1
2. `sam --version`:1.90.0
3. AWS region:eu--central-1

```
{
  "version": "1.90.0",
  "system": {
    "python": "3.11.3",
    "os": "Linux-5.19.0-46-generic-x86_64-with-glibc2.35"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.4",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by hawflau** [comment] 2023-07-14 19:28
Hi @huseyinkurtvestel, can you please provide the content of `~/.docker/config.json`? Trying to understand if there's an issue in your docker config, since the error was thrown from dockerpy.

**Comment by huseyinkurtvestel** [comment] 2023-07-16 11:02
Hello @hawflau there is no config file which made debugging extremely annoying. This error started appearing after I updated sam version to latest which is 1.90,there was no errors before. Installing docker desktop seems to fix the issue but I do not know why, since I do not even use the desktop version.

**Comment by mudassir-ahmed** [comment] 2023-07-25 10:52
Faced same issue. Check your `~/.docker/config.json` and delete `credsStore`.


Before:
```json
{
  "auths" : {},
  "credStore" : "desktop",
  "currentContext" : "desktop-linux"
}
```

After:
```json
{
  "auths" : {},
  "currentContext" : "desktop-linux"
}
```

**Comment by marc2982** [comment] 2023-08-30 22:08
Removing credStore worked for me as well, but mine was called "credsStore". I use docker desktop through wsl2 so the value was "desktop.exe".

**Comment by hawflau** [comment] 2023-08-31 17:45
This looks to me that it's a docker issue instead of a SAM CLI issue. And I also see there's a solution to resolve the problem. I'm closing the issue now. Feel free to reopen if you think the issue is not resolved.

**Closed by hawflau** 2023-08-31 17:45 UTC
Labels: type/question, blocked/more-info-needed, area/local
