### ISSUE TITLE
Bug: sam init fails on 1.53 - win 11

### ISSUE THREAD

**Issue by Yazai** [aws/aws-sam-cli#4043] opened 2022-07-09 07:19 UTC
### Description:

sam init fails on sam cli 1.53 - win 11.
using sam cli 1.52 works fine.

### Steps to reproduce:

install sam cli 1.53 - win 11.
sam init
selection: 1, 1, y , n, enter
error:
Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)        
Error: Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\xxxxx\AppData\Roaming\AWS SAM directory or file an issue at https://github.com/aws/aws-sam-cli/issues

### Observed result:

It says file not found or no permission
Permission or git version / setting is fine because it works on sam cli 1.52.

### Expected result:

init works w/o error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:win 11
2. `sam --version`:SAM CLI, version 1.53.0
3. AWS region:ap-northeast-1

`Add --debug flag to command you are running`

Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)
2022-07-09 16:07:40,341 | Configure core.longpaths=true in git clone. You might also need to enable long paths in Windows registry.
2022-07-09 16:07:44,019 | Removing old repo at C:\Users\xxx\AppData\Roaming\AWS SAM\aws-sam-cli-app-templates
2022-07-09 16:07:44,378 | Copying from C:\Users\xxx\AppData\Local\Temp\tmpi_i4242q\aws-sam-cli-app-templates to C:\Users\xxx\AppData\Roaming\AWS SAM\aws-sam-cli-app-templates
2022-07-09 16:07:48,580 | rmtree failed in <built-in function scandir> for C:\Users\xxx\AppData\Local\Temp\tmpi_i4242q\aws-sam-cli-app-templates\provided.al2\graalvm\java11\cookiecutter-aws-sam-graalvm-gradle\{{cookiecutter.project_name}}\HelloWorldFunction\src\main\resources\META-INF\native-image\com.amazonaws\aws-lambda-java-core, details: (<class 'FileNotFoundError'>, FileNotFoundError(2, '指定されたパスが見つかりません。'), <traceback object at 0x000002F3ADC164C0>)
...

**Comment by hawflau** [comment] 2022-07-09 19:23
@Yazai you need to do the prerequisite as below:

> This is work for me Open the Powershell as administrator then type:
> 
> ```
> New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
> -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
> ```

Closing as duplicate of #4031

**Closed by hawflau** 2022-07-09 19:23 UTC
Labels: type/bug, stage/needs-triage
