### ISSUE TITLE
/bin/sh: /var/runtime/bootstrap: Permission denied

### ISSUE THREAD

**Issue by faisal-hearth** [aws/aws-sam-cli#2011] opened 2020-05-28 12:13 UTC
Getting this error when when hitting the API after running:
`sam local start-api -p 4000 -n ./.env.json -t ./template-debug.yaml `

System: Ubuntu 20.04,
sam cli Version: 0.51.0

**Comment by awood45** [comment] 2020-05-28 22:58
I can't reproduce this - can you possibly share your template? Feel free to anonymize any parts of the template that may be sensitive. I'm especially interested to know which runtime you are using.

**Comment by faisal-hearth** [comment] 2020-05-28 23:39
Here's the template,
Note: '-------------------' has been used to anonymize some values.

`# SAM Template (it is been converted to CFN template by SAM)

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: --------------

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs12.x
    Timeout: 5 #minutes
    MemorySize: 128 #MB
    Layers:
      - !Ref NodeModulesLayer
    # Environment:
    #   Variables:
    #     NODE_PATH: '/opt/node_modules/'
    Tags:
      environment: !Ref MyEnvironment

Parameters:
  MyEnvironment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment for this stack of resources
    ConstraintDescription: Must be dev or prod

  Audience:
    Type: String

  JwksUri:
    Type: String

  TokenIssuer:
    Type: String

  contentfulAccessToken:
    Type: String

  contentfulSpace:
    Type: String

  elasticsearchApiKey:
    Type: String

  elasticsearchURL:
    Type: String

  MongodbURI:
    Type: String

  SuperAdmin:
    Type: String

  ESPRODUCTINDEX:
    Type: String

  ESCOMPANYINDEX:
    Type: String

  CFENV:
    Type: String

Mappings:
  EnvSpecific:
    dev:
      FnSuffix: Dev
      LambdaRole: -------------------
      contentTypeLoggerRole: ----------------------

    prod:
      FnSuffix: Prod
      LambdaRole: -----------------------------
      contentTypeLoggerRole: ---------------------------------------

  S3Roles:
    dev:
      LambdaRole: ---------------------------------
    prod:
      LambdaRole: ---------------------------------

# !FindInMap [ MappingName(EnvSpecific), keyname(dev), value(FnSuffix) ] gives out 'anyValue1'

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${MyEnvironment}-NodeModulesLayer'
      Description: !Sub 'Contains node-modules for ${MyEnvironment}'
      ContentUri: ./dependencies
      CompatibleRuntimes:
        - nodejs10.x
        - nodejs12.x
      LicenseInfo: 'Available under the ISC license.'
      RetentionPolicy: Delete

  # An API with authorizer implemented to use as a reference inside other APIs
  ApiBase:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      StageName: !Ref MyEnvironment
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        AddDefaultAuthorizerToCorsPreflight: False
        DefaultAuthorizer: TokenAuthorizer
        Authorizers:
          TokenAuthorizer:
            FunctionArn: !GetAtt LambdaTokenAuthorizer.Arn
            FunctionInvokeRole:
              !FindInMap [EnvSpecific, !Ref MyEnvironment, LambdaRole]
            Identity:
              Header: Authorization
              ValidationExpression: ^Bearer [-0-9a-zA-z\.]*$
              ReauthorizeEvery: 0 # seconds
      Tags:
        environment: !Ref MyEnvironment

  # Auth0 Token Authorizer Lambda function
  LambdaTokenAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${MyEnvironment}-LambdaTokenAuthorizer'
      Description: !Sub 'Auth0 JWT RSA Token Authorizer - ${MyEnvironment}'
      CodeUri: ./lambda-token-authorizer
      Role: !FindInMap [EnvSpecific, !Ref MyEnvironment, LambdaRole]
      Environment:
        Variables:
          AUDIENCE: !Ref Audience
          JWKS_URI: !Ref JwksUri
          TOKEN_ISSUER: !Ref TokenIssuer

  getcompany:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${MyEnvironment}-getcompany'
      Description: !Sub 'getcompany Function for - ${MyEnvironment} env'
      CodeUri: ./getcompany
      Role: !FindInMap [EnvSpecific, !Ref MyEnvironment, LambdaRole]
      Environment:
        Variables:
          contentfulSpace: !Ref contentfulSpace
          contentfulAccessToken: !Ref contentfulAccessToken
          elasticsearchApiKey: !Ref elasticsearchApiKey
          elasticsearchURL: !Ref elasticsearchURL
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref ApiBase
            Path: /company
            Method: GET

  collections:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${MyEnvironment}-collections'
      Description: !Sub 'collections Function for - ${MyEnvironment} env'
      CodeUri: ./collections
      Role: !FindInMap [EnvSpecific, !Ref MyEnvironment, LambdaRole]
      VpcConfig:
        SecurityGroupIds:
          - --------------
        SubnetIds:
          - ------------------
          - -----------------
          - ----------------
      Environment:
        Variables:
          MongodbURI: !Ref MongodbURI
          SuperAdmin: !Ref SuperAdmin
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref ApiBase
            Path: /collections
            Method: POST

  getproduct:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${MyEnvironment}-getproduct'
      Description: !Sub 'getproduct Function for - ${MyEnvironment} env'
      CodeUri: ./getproduct
      Role: !FindInMap [EnvSpecific, !Ref MyEnvironment, LambdaRole]
      Environment:
        Variables:
          contentfulSpace: !Ref contentfulSpace
          contentfulAccessToken: !Ref contentfulAccessToken
          elasticsearchApiKey: !Ref elasticsearchApiKey
          elasticsearchURL: !Ref elasticsearchURL
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref ApiBase
            Path: /product
            Method: GET

  signup:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${MyEnvironment}-signup'
      Description: !Sub 'SignUp Function for - ${MyEnvironment} env'
      CodeUri: ./signup
      Role: !FindInMap [S3Roles, !Ref MyEnvironment, LambdaRole]
      Environment:
        Variables:
          NODE_ENV: !Ref MyEnvironment
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref ApiBase
            Path: /signup
            Method: POST
            Auth:
              Authorizer: NONE

  elasticsearch:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${MyEnvironment}-elasticsearch'
      Description: !Sub 'elasticsearch Function for - ${MyEnvironment} env'
      CodeUri: ./elasticsearch
      MemorySize: 256
      Timeout: 5
      Role: !FindInMap [EnvSpecific, !Ref MyEnvironment, LambdaRole]
      Environment:
        Variables:
          contentfulSpace: !Ref contentfulSpace
          contentfulAccessToken: !Ref contentfulAccessToken
          elasticsearchApiKey: !Ref elasticsearchApiKey
          ESPRODUCTINDEX: !Ref ESPRODUCTINDEX
          ESCOMPANYINDEX: !Ref ESCOMPANYINDEX
          CFENV: !Ref CFENV
          NODE_ENV: !Ref MyEnvironment
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref ApiBase
            Path: /search
            Method: POST

  cfcontentTypelogger:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${MyEnvironment}-cfcontentTypelogger'
      Description: !Sub 'cfcontentTypelogger Function for - ${MyEnvironment} env'
      CodeUri: ./cf-contentype-logger
      Role: !FindInMap [EnvSpecific, !Ref MyEnvironment, contentTypeLoggerRole]
      Environment:
        Variables:
          contentfulSpace: !Ref contentfulSpace
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref ApiBase
            Path: /contentful-cthandle
            Method: POST
        # Api2:
        #   Type: Api
        #   Properties:
        #     RestApiId: !Ref ApiBase
        #     Path: /MyResource
        #     Method: ANY

  # LAMBDA - A Test Function with APIs protected with authorization
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${MyEnvironment}-TestFunction'
      Description: !Sub 'Test Function for - ${MyEnvironment} env'
      CodeUri: ./test-function
      Role: !FindInMap [EnvSpecific, !Ref MyEnvironment, LambdaRole]
      
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiBase
            Path: /testfunction
            Method: get
            # NOTE: Uncomment the two lines below to make `GET /` publicly accessible
            # Auth:
            #   Authorizer: NONE

Outputs:
  ApiURL:
    Description: 'API URL'
    Value: !Sub 'https://${ApiBase}.execute-api.${AWS::Region}.amazonaws.com/${MyEnvironment}/'
`

**Comment by dsmithhayes** [comment] 2020-06-04 22:09
I am trying a different command, but trying to invoke a function locally and getting the same results.

I am trying `sam local invoke`

I have three separate lambdas I get this error on, one Node.js 10.x, one Node.js 12.x, and one Python 2.7.

OS: Ubuntu 18.04. 
SAM: 0.52.0

**Comment by sriram-mv** [comment] 2020-07-20 22:19
Seems like permission issues on the folder itself, that is mounted within docker. Try adding additional permissions to the files that are mounted within.

**Comment by sriram-mv** [comment] 2020-10-01 01:52
Closing this as it seems to be permission issues, please retry with the latest version of SAM CLI.

**Closed by sriram-mv** 2020-10-01 01:52 UTC
Labels: area/docker, area/local/start-api, stage/more-info-needed
