### ISSUE TITLE
sam deploy option to write stack output to file

### ISSUE THREAD

**Issue by houbie** [aws/aws-sam-cli#2620] opened 2021-02-12 08:55 UTC
### Description
After deploying a stack, I often need to process the stack output.
The deploy command only prints the stack output as text to the console, so I have to use the AWS CLI to capture the stack output in a file.

### Proposal
add a `--output my-output.json` option to the deploy command

**Comment by sapessi** [comment] 2021-05-20 19:56
Closing as a duplicate of #2722 - we'll track the feature request there.

**Closed by sapessi** 2021-05-20 19:56 UTC
Labels: stage/pm-review, type/feature
