### ISSUE TITLE
sam build fails with "AWS quick start -> Java 11 -> Docker"

### ISSUE THREAD

**Issue by vilunet** [aws/aws-sam-cli#2551] opened 2021-01-25 04:37 UTC
### Description:

Build fails with docker build at step 8  - File Not Found

### Steps to reproduce:

Just run AWS quick start to create a sample app and run sam build.

### Observed result:

Step 7/16 : COPY gradle/lambda-build-init.gradle ./build
 ---> Using cache
 ---> bfaaeb63805a
Step 8/16 : RUN ./gradlew --project-cache-dir $SCRATCH_DIR/gradle-cache -Dsoftware.amazon.aws.lambdabuilders.scratch-dir=$SCRATCH_DIR --init-script $SCRATCH_DIR/lambda-build-init.gradle build
 ---> Running in 37994a9fdc4b
←[0m←[91m: No such file or directory
←[0m
Build Failed
Error: HelloWorldFunction failed to build: The command '/bin/sh -c ./gradlew --project-cache-dir $SCRATCH_DIR/gradle-cache -Dsoftware.amazon.aws.lambdabuilders.scratch-dir=$SCRATCH_DIR --init-script $SCRATCH_DIR/lambda-build-init.gradle build' returned a non-zero code: 127

### Expected result:

build should return no error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 - Powershell
2. `sam --version`: 1.15.0

**Comment by aahung** [comment] 2021-01-25 18:20
Update: cannot reproduce it on macOS with hello world (zip) template. Will try it on windows

**Comment by CoshUS** [comment] 2021-03-18 20:55
This issue is due to git pulling the quick start repo with `\r\n` as the line ending on Windows.
A workaround is to modify `gradlew` and replace all `\r\n` to `\n`

**Comment by CoshUS** [comment] 2021-04-07 00:19
Fixed in 1.22.0 release.

**Closed** 2021-04-07 00:19 UTC
Labels: area/init, platform/windows, stage/waiting-for-release
