### ISSUE TITLE
Function timed out after ... seconds even though Docker looks working well

### ISSUE THREAD

**Issue by momotaro98** [aws/aws-sam-cli#2710] opened 2021-03-12 11:45 UTC
### Description:

I sometimes have to face this issue. I think this is related to Docker things but I have no idea for the cause.

I'm using Golang binary to mount sam local cli.

```
$ ls -1
search_tutor
template.yml
```

`search_tutor` is my binary name.

Then I start sam local start-api

```
$ sam local start-api --host 127.0.0.1 --port 3002 --debug
2021-03-12 20:38:21,289 | 2 APIs found in the template
2021-03-12 20:38:21,314 | Mounting BookmarkTutorFunction at http://127.0.0.1:3002/{product}/bookmark/tutor [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
2021-03-12 20:38:21,314 | Mounting SearchTutorFunction at http://127.0.0.1:3002/{product}/tutors [POST]
2021-03-12 20:38:21,314 | You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2021-03-12 20:38:21,315 | Localhost server is starting up. Multi-threading = True
2021-03-12 20:38:21  * Running on http://127.0.0.1:3002/ (Press CTRL+C to quit)
```

After that, I do curl then I gets timed out error even though the 10 seconds is enough time for my app.

```
2021-03-12 20:39:36,822 | Found one Lambda function with name 'SearchTutorFunction'
2021-03-12 20:39:36,822 | Invoking search_tutor (go1.x)
2021-03-12 20:39:36,822 | Environment variables overrides data is standard format
2021-03-12 20:39:36,822 | Loading AWS credentials from session with profile 'None'
2021-03-12 20:39:36,879 | Resolving code path. Cwd=./bin, CodeUri=/Users/shintaro.ikeda/workspace/git.rarejob.com/rarejob-platform/event-search/bin/.
2021-03-12 20:39:36,879 | Resolved absolute path to code is /Users/shintaro.ikeda/workspace/git.rarejob.com/rarejob-platform/event-search/bin/.
2021-03-12 20:39:36,879 | Code /Users/shintaro.ikeda/workspace/git.rarejob.com/rarejob-platform/event-search/bin/. is not a zip/jar file
2021-03-12 20:39:36,955 | Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-go1.x:rapid-1.20.0.

2021-03-12 20:39:36,955 | Mounting /Users/shintaro.ikeda/workspace/git.rarejob.com/rarejob-platform/event-search/bin/. as /var/task:ro,delegated inside runtime container
2021-03-12 20:39:37,692 | Starting a timer for 10 seconds for function 'SearchTutorFunction'
START RequestId: 09e60e16-2d2a-40e3-8cc6-e6d75912fc0b Version: $LATEST
2021-03-12 20:39:47,697 | Function 'SearchTutorFunction' timed out after 10 seconds
2021-03-12 20:39:48,506 | Container was not created. Skipping deletion
2021-03-12 20:39:48,506 | Cleaning all decompressed code dirs
2021-03-12 20:39:48,507 | No response from invoke container for SearchTutorFunction
2021-03-12 20:39:48,507 | Invalid lambda response received: Lambda response must be valid json
2021-03-12 20:39:48 127.0.0.1 - - [12/Mar/2021 20:39:48] "POST /high/tutors HTTP/1.1" 502 -
```

### Steps to reproduce:

Same above

### Observed result:

Same above

### Expected result:

Succeed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS: 10.15.7 
2. `sam --version`: SAM CLI, version 1.20.0
3. AWS region:

**Comment by wchengru** [comment] 2021-03-12 19:40
Hi @momotaro98 , it seems like your function config set the timeout to 10 seconds.
Can you please check if you defined `Timeout` in your template file? For example: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-timeout

**Comment by momotaro98** [comment] 2021-03-13 00:41
@wchengru 

Thank you for your help.

To be honest, I have no idea how to reproduce this issue. 

The issue still occur after I restart Docker for Mac application. However, it does not after I restart Mac OS.

I'm wondering what is the trigger of this issue. After I run sam start-api command for a couple of times well, I sometimes get into this issue.

**Comment by CoshUS** [comment] 2021-03-22 05:20
@momotaro98 
Thanks for the information. Closing as this is not reproducible and seems to be related to docker or other system issues.
Feel free to leave more information on the issue and I can reopen if needed.

**Closed by CoshUS** 2021-03-22 05:20 UTC
Labels: area/local/start-api, blocked/more-info-needed, stage/bug-repro
