### ISSUE TITLE
Go quickstart hello world example fails to run

### ISSUE THREAD

**Issue by Phuurl** [aws/aws-sam-cli#2151] opened 2020-08-01 13:53 UTC
### Description

After deploying the Go Hello World quickstart example (without any modifications), the deployed Lambda fails to run, with a `file not found` error.

### Steps to reproduce

1. `sam init --runtime go1.x`
2. Select the `Hello World Example`
3. `make` the project (or `sam build`)
4. `sam deploy --guided`
5. Either hit the deployed API, or test the Lambda via the console
6. Observe the function fails to execute

### Observed result

The following error is visible in the Lambda console:
```json
{
  "errorMessage": "fork/exec /var/task/hello-world: no such file or directory",
  "errorType": "PathError"
}
```

### Expected result
The Lambda executes.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04, kernal 5.4.0-42
2. `sam --version`: SAM CLI, version 1.0.0
3. `go version`: go version go1.14.5 linux/amd64

**Comment by rts-rob** [comment] 2020-08-06 14:47
This also occurs with the following environment details:
1. OS: Windows 10, Version 1809 (OS Build 17763.1339)
2. `sam --version`: SAM CLI, version 1.0.0
3. `go version`: go1.14.6 windows/amd64

Seems to be related to executable permissions:
```
ls .aws-sam/build/HelloWorldFunction

    Directory: ~\source\foo\.aws-sam\build\HelloWorldFunction

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         8/6/2020  10:29 AM        9967550 hello-world
```

**Comment by rts-rob** [comment] 2020-08-06 14:57
However, this works as expected on macOS with the following environment details:
1. OS: macOS Catalina Version 10.15.6
2. `sam --version`: SAM CLI, version 1.0.0
3. `go version`: go1.14.6 darwin/amd64

**Comment by CoshUS** [comment] 2020-08-13 19:40
> This also occurs with the following environment details:
> 
> 1. OS: Windows 10, Version 1809 (OS Build 17763.1339)
> 2. `sam --version`: SAM CLI, version 1.0.0
> 3. `go version`: go1.14.6 windows/amd64
> 
> Seems to be related to executable permissions:
> 
> ```
> ls .aws-sam/build/HelloWorldFunction
> 
>     Directory: ~\source\foo\.aws-sam\build\HelloWorldFunction
> 
> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> -a----         8/6/2020  10:29 AM        9967550 hello-world
> ```

Duplicate with: https://github.com/awslabs/aws-sam-cli/issues/954

Original issue could a different one since the error message is path not found and I wasn't able to reproduce it yet.

**Comment by yogesnsamy** [comment] 2020-10-02 03:38
Having the same issue, is there a workaround?

- Ubuntu 20.04.1 LTS
- SAM CLI, version 1.4.0
- go version go1.14.4 linux/amd64

**Comment by rts-rob** [comment] 2020-10-02 14:01
One workaround is to provision a [Cloud9 instance](https://aws.amazon.com/cloud9/). I just tested this with the default install and everything works as expected. The smallest instance type _t2.micro_ should be fine, and may fall within the free tier depending on your account age and usage. See [Cloud9 Pricing](https://aws.amazon.com/cloud9/pricing/) for more information.

**NOTE: You must choose "Amazon Linux" as the Platform, not Ubuntu Server 18.04 LTS. It does not work on Ubuntu Server 18.04 LTS.**

Working Cloud9 info:
1. OS: Amazon Linux 2018.03
1. `sam --version`: SAM CLI, version 1.3.2
1. `go version`: go1.13.14 linux/amd64

**Comment by yogesnsamy** [comment] 2020-10-02 14:45
> One workaround is to provision a [Cloud9 instance](https://aws.amazon.com/cloud9/). I just tested this with the default install and everything works as expected. The smallest instance type _t2.micro_ should be fine, and may fall within the free tier depending on your account age and usage. See [Cloud9 Pricing](https://aws.amazon.com/cloud9/pricing/) for more information.
> 
> **NOTE: You must choose "Amazon Linux" as the Platform, not Ubuntu Server 18.04 LTS. It does not work on Ubuntu Server 18.04 LTS.**
> 
> Working Cloud9 info:
> 
> 1. OS: Amazon Linux 2018.03
> 2. `sam --version`: SAM CLI, version 1.3.2
> 3. `go version`: go1.13.14 linux/amd64

Thank you for the response. My issue occurred because I use gvm and I wasn't in the right path prior to compiling the project.

When I run `gvm use go1. X. X` then compile and deploy, the problem didn't occur.

**Comment by CoshUS** [comment] 2020-10-29 00:41
I was not able to reproduce this issue. As @yogesnsamy mentioned, this could be a setup error. 
> Thank you for the response. My issue occurred because I use gvm and I wasn't in the right path prior to compiling the project.
> When I run `gvm use go1. X. X` then compile and deploy, the problem was solved.

Regarding the Windows permission issue @rts-rob brought up, it is tracked and fixed in a separate issue. #954 

Closing this issue, feel free to reopen if anyone has more info on this matter.

**Closed by CoshUS** 2020-10-29 00:41 UTC
Labels: bug/repro, type/bug

**Comment by dcabib** [comment] 2025-10-06 13:18
I've created PR #8297 that implements .env file support for SAM local commands.

The implementation adds a  flag that loads environment variables from .env files using python-dotenv. Variables can be merged with  JSON, with JSON taking precedence.

Please review at: https://github.com/aws/aws-sam-cli/pull/8297
