### ISSUE TITLE
InlineCode not working for sam invoke

### ISSUE THREAD

**Issue by mihaa1** [aws/aws-sam-cli#2781] opened 2021-03-31 08:56 UTC
### Description:
Trying to add InlineCode (node) in the tamplate file.
Getting an error:
```
Invoking app.lambdaHandler (nodejs10.x)
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 152, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 121, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 81, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 167, in do_cli
    context.local_lambda_runner.invoke(
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 120, in invoke
    config = self.get_invoke_config(function)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 163, in get_invoke_config
    code_abs_path = resolve_code_path(self.cwd, function.codeuri)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/utils/codeuri.py", line 43, in resolve_code_path
    if not os.path.isabs(codeuri):
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/posixpath.py", line 62, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
### Steps to reproduce:
* setup hello world example with sam init
* add InlineCode property to HelloWorldFunction
Relevant part of the template:
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: hello-world/
      InlineCode: |
        exports.handler = async (event) => {
          return {
            statusCode: 200,
            headers: {'Content-Type':'application/json'},
            body: "hello"
            }
        }
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```

### Observed result:
Getting error above

### Expected result:
Function should run

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Macos 11.2.3 
2. `sam --version`: SAM CLI, version 1.21.1

**Comment by qingchm** [comment] 2021-04-01 18:52
Your handler doesn't match what you have in your inline code. Please change it to index.handler

**Comment by qingchm** [comment] 2021-04-01 18:55
Generally if you want to use inline code, please always specify your handler as "index.xxx", xxx being your handler name, thanks!

**Comment by mihaa1** [comment] 2021-04-05 16:54
@qingchm fixing the handler name didn't fix the issue. Plz see below my updated template

```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri: hello-world/
      InlineCode: |
        exports.handler = async (event) => {
          return {
            statusCode: 200,
            headers: {'Content-Type':'application/json'},
            body: "hello"
            }
        }
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```

**Comment by qingchm** [comment] 2021-04-05 17:53
taking a look

**Comment by qingchm** [comment] 2021-04-05 18:29
Sorry my bad, just confirmed that local invoke with inline code is not yet supported! Will view this as a feature request. But please keep using this style of handler for inline functions, thanks! @mihaa1

**Comment by jfuss** [comment] 2021-04-13 16:48
Duplicate of https://github.com/aws/aws-sam-cli/issues/790 Closing

**Closed by jfuss** 2021-04-13 16:48 UTC
Labels: type/feature

**Comment by mcphargus** [comment] 2022-12-01 08:44
also tripping over this issue. Hope this feature is added soon.
