### ISSUE TITLE
config file path resolved relative to the template directory

### ISSUE THREAD

**Issue by atoa** [aws/aws-sam-cli#3431] opened 2021-10-31 18:50 UTC
### Description:

Passing a template that resides in a subdirectory with the `--template` option, causes the samconfig.toml file to be resolved relative to the template directory.

### Steps to reproduce:

```shell
$ # file structure from base directory
$ tree
.
├── samconfig.toml
└── deployment
    └── template.yaml

$ # samconfig
$ cat samconfig.toml
[oatoa.build.parameters]
use_container = true
parallel = true
cached = true
skip_pull_image = true

$
```

```shell
$ # none of the following commands use the samconfig.toml when executed from base dir listed above
$ sam build --config-env oatoa --template deployment/template.yaml
$ sam build --debug --config-file samconfig.toml --config-env oatoa --template deployment/template.yaml
2021-10-31 18:37:51,664 | Using config file: samconfig.toml, config environment: oatoa
2021-10-31 18:37:51,664 | Expand command line arguments to:
2021-10-31 18:37:51,664 | --template_file=/home/ec2-user/environment/workspace/deployment/template.yaml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2021-10-31 18:37:51,768 | 'build' command is called
```

```shell
$ # passing a config-file path relative from the template resolves the parameters in samconfig.toml
$ # again running from base dir above
$ sam build --debug --config-file ../samconfig.toml --config-env oatoa --template-file deployment/template.yaml
2021-10-31 18:32:38,267 | Using config file: ../samconfig.toml, config environment: oatoa
2021-10-31 18:32:38,267 | Expand command line arguments to:
2021-10-31 18:32:38,267 | --template_file=/home/ec2-user/environment/workspace/deployment/template.yaml --use_container --parallel --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache --cached --skip_pull_image 
2021-10-31 18:32:38,369 | 'build' command is called
2021-10-31 18:32:38,369 | Starting Build use cache
2021-10-31 18:32:38,369 | Starting Build inside a container
```

### Observed result:

The sam command doesn't use the samconfig.toml config file unless you pass the full path or a path relative to the template.yaml file.

### Expected result:

It seems like the config file is set relative to the template directory but other directories (e.g. cache and build dir) are still relative to where the command is executed. I'd find it more obvious to resolve the config-file relative to the directory where the sam command is executed.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux 2
2. `sam --version`: SAM CLI, version 1.34.1
3. AWS region: us-east-1

`Add --debug flag to command you are running`

**Comment by CoshUS** [comment] 2021-11-04 07:47
Thanks for the feedback. This is the intended behavior as template file acts as the root directory of a project, but I'll bring this up with the team to discuss further on this UX issue. 
Seems like the documentation should also be updated to callout this behavior.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

**Comment by atoa** [comment] 2021-11-10 16:13
Clarifying the documentation would help (the behavior wasn't obvious to me when I was trying to figure it out).

That said, I still find it confusing that `config-file` is relative to the template and other options that take paths are relative to the current working directory (cwd). For example, the `--build-dir` and `--cache-dir` options are resolved relative to the cwd.

I'd venture to guess that most cli tools resolve path options relative to the cwd.

I think that the `--base-dir` option, which is closely related to the template file, is also resolved relative to the cwd when you override it (default to be relative to the template). The `config-file` could have a similar behavior where it defaults to look in the same directory as the template but it resolves relative to the cwd if you pass an argument.

I vote to make  `config-file` resolve relative to the cwd so that it is consistent and more obvious.

**Comment by ssenchenko** [comment] 2021-12-10 21:19
Duplicate of [#2747](https://github.com/aws/aws-sam-cli/issues/2747)

**Closed by ssenchenko** 2021-12-10 21:19 UTC
Labels: type/ux, type/documentation, maintainer/need-followup
