### ISSUE TITLE
validate requires too many permissions

### ISSUE THREAD

**Issue by vieirai** [aws/aws-sam-cli#3510] opened 2021-12-01 23:13 UTC
### Description:
Running `sam validate` requires access to `iam:ListPolicies` on `/`, which means we can't restrict deployment roles to certain namespaces.
For example, I have the following policy on my deployment role:
```yaml
{
  "Sid": "IAM",
  "Action": ["iam:*"],
  "Effect": "Allow",
  "Resource": [
    "arn:aws:iam::XXXXXXXX:role/my-namespace*"
  ]
}
```
With the above I can deploy a stack which defines roles that match the wildcard, however I can't validate the template using `sam validate`.
But I can validate the template using `aws cloudformation validate-template --template-body file://template.yaml`, which tells me that this is a bug in the SAM CLI.

### Steps to reproduce:

Create a deployment role with the policy shown above and then try to validate a `template.yml`.

### Observed result:
```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListPolicies operation: User: arn:aws:sts::XXXXXXXX:assumed-role/myDeploymentRole is not authorized to perform: iam:ListPolicies on resource: policy path /
```

### Expected result:
I can validate my template.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu
2. `sam --version`: 1.32.0
3. AWS region: eu-west-1

Note: I could add additional permissions to `iam:ListPolicies` on anything, but if it works with `aws` then surely this can be fixed in SAM?

**Comment by jfuss** [comment] 2021-12-03 21:29
@vieirai `aws cloudformation validate-template --template-body file://template.yaml` doesn't do what you expect. It does not validate the resource but makes sure the template is json and yaml: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/validate-template.html

`sam validate` needs `iam:ListPolicies` to pull IAM Managed Polices because the SAM Transform does validation with respect to AWS Managed Policies. 

This is by design and not something we can change at this time.

Closing.

**Closed by jfuss** 2021-12-03 21:29 UTC
