### ISSUE TITLE
Feature request: Application Insights should reference Resource Group

### ISSUE THREAD

**Issue by corey-cole** [aws/aws-sam-cli#4956] opened 2023-04-01 18:30 UTC
### Describe your idea/feature/enhancement

When the SAM CLI enhances a template with Application Insights, it should use the `Ref` intrinsic to get the resource group name rather than copy/pasting the `Sub` construct used to name the resource group.

### Proposal

When creating template modifications, these modifications should follow best-practice.  While a resource can be named with intrinsic functions, any references to the entity should use an appropriated `Ref` or `GetAtt` to ensure that a change to the name of the resource doesn't require multiple edits in the template.

Operationally, I have seen users create extra resources and generally make a mess of their account by forgetting to update all the `Sub` constructs that are used to keep resources in sync.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model): No.

### Additional Details

https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/init/template_modifiers/application_insights_template_modifier.py#L65

The above line would change to:
```python
                self.RESOURCE_GROUP_NAME_KEY: f"!Ref {ResourceGroupRef}",
```
This would also have the effect of removing the requirement for the `DependsOn` as CloudFormation automagically creates the dependency when `!Ref` is used.

**Comment by mildaniel** [comment] 2023-04-03 17:57
Thanks @corey-cole for the suggestion! Would you be open to contributing this feature?

**Comment by jfuss** [comment] 2023-04-03 19:34
Duplicate of https://github.com/aws/aws-sam-cli/issues/4695

Closing in favor of the first

**Closed by jfuss** 2023-04-03 19:34 UTC
Labels: type/feature
