### ISSUE TITLE
Bug: sam local invoke - Error: a bytes-like object is required, not 'str' on decompress

### ISSUE THREAD

**Issue by thiko** [aws/aws-sam-cli#5434] opened 2023-07-02 09:17 UTC
### Description:
I'm trying to debug a Quarkus Java 17 application built with `quarkus-maven-plugin:3.2.0.Final` using SAM .
The application is up and running as Lambda. I deployed it with AWS CDK 2.

In order to debug it locally, I generate a `template.yaml` for SAM using: `cdk synth --no-staging > template.yaml`

The generated file looks good as far as I can see it. Unfortunately, I'm not able to start it locally:
`sam local invoke --debug -t ../cdk-infrastructure/template.yaml`
results in:

(see full debug output: [debugoutput.log](https://github.com/aws/aws-sam-cli/files/11929085/debugoutput.log))
```
sam local invoke --debug -t ../cdk-infrastructure/template.yaml
....
2023-07-02 09:44:50,079 | Cleaning all decompressed code dirs
2023-07-02 09:44:50,098 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-07-02 09:44:50,099 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-07-02 09:44:50,100 | Unable to find Click Context for getting session_id.

Error: a bytes-like object is required, not 'str'
Traceback:
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 184, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 149, in wrapped
    return_value = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 100, in cli
    do_cli(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 206, in do_cli
    context.local_lambda_runner.invoke(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 144, in invoke
    self.local_runtime.invoke(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 324, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 189, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 85, in create
    container = LambdaContainer(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 94, in __init__
    image = LambdaContainer._get_image(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 237, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture, function_name=function_name)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 195, in build
    self._check_base_image_is_current(base_image)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 469, in _check_base_image_is_current
    if self.is_base_image_current(image_name):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 493, in is_base_image_current
    return self.get_local_image_digest(image_name) == self.get_remote_image_digest(image_name)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 509, in get_remote_image_digest
    remote_info = self.docker_client.images.get_registry_data(image_name)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/docker/models/images.py", line 356, in get_registry_data
    attrs=self.client.api.inspect_distribution(name, auth_config),
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/docker/api/image.py", line 287, in inspect_distribution
    return self._result(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/docker/errors.py", line 34, in create_api_error_from_http_exception
    if any(fragment in explanation_msg
  File "/opt/homebrew/Cellar/aws-sam-cli/1.89.0/libexec/lib/python3.8/site-packages/docker/errors.py", line 34, in <genexpr>
    if any(fragment in explanation_msg
```

### Steps to reproduce:
Having following structure:
```
.
├── README.md
├── cdk-infrastructure
│   ├── README.md
│   ├── cdk.json
│   ├── cdk.out
│   ├── pom.xml
│   ├── src
│   ├── target
│   └── template.yaml
└── simple-dbquery-backend
    ├── README.md
    ├── mvnw
    ├── mvnw.cmd
    ├── pom.xml
    ├── src
    └── target
```

* in cdk-infrastructure run: `cdk synth --no-staging > template.yaml`
* in  simple-dbquery-backend run: `mvn clean package` to build everything (especially the zip file)
* in  simple-dbquery-backend run:  `sam local invoke --debug -t ../cdk-infrastructure/template.yaml`

### Expected result:
No errors ;) 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 13.4.1 
2. `sam --version`: `SAM CLI, version 1.89.0`
3. AWS region: not important but its eu-central-1

```


❯ sam --info
{
  "version": "1.89.0",
  "system": {
    "python": "3.8.17",
    "os": "macOS-13.4.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "4.5.1",
    "aws_cdk": "2.85.0 (build 4e0d726)",
    "terraform": "1.5.1"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by hnnasit** [comment] 2023-07-03 15:31
Hi @thiko, seems like this is related to #5421 issue. Does this behavior occur with `sam cli` downloaded using PKG as well? We will be investigating this further.

**Comment by thiko** [comment] 2023-07-03 18:28
Hi @hnnasit 
oh damn - I was searching for similar issues but haven't found it. 

It might be worth mentioning I'm running podman as container engine instead docker.
I installed SAM with brew. 

So I uninstalled SAM with brew 
```
❯ brew uninstall aws/tap/aws-sam-cli
Uninstalling /opt/homebrew/Cellar/aws-sam-cli/1.89.0... (14,489 files, 262.1MB)
```

Then re-installed it using the PKG file.
```
❯ sam --version
SAM CLI, version 1.89.0
```

Unfortunately the result is pretty similar:( 
```
2023-07-03 20:27:21,608 | Unable to find Click Context for getting session_id.

Error: a bytes-like object is required, not 'str'
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 184, in wrapped
  File "samcli/lib/telemetry/metric.py", line 149, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 95, in wrapper
  File "samcli/commands/local/invoke/cli.py", line 100, in cli
  File "samcli/commands/local/invoke/cli.py", line 206, in do_cli
  File "samcli/commands/local/lib/local_lambda.py", line 144, in invoke
  File "samcli/lib/telemetry/metric.py", line 324, in wrapped_func
  File "samcli/local/lambdafn/runtime.py", line 189, in invoke
  File "samcli/local/lambdafn/runtime.py", line 85, in create
  File "samcli/local/docker/lambda_container.py", line 94, in __init__
  File "samcli/local/docker/lambda_container.py", line 237, in _get_image
  File "samcli/local/docker/lambda_image.py", line 195, in build
  File "samcli/local/docker/lambda_image.py", line 469, in _check_base_image_is_current
  File "samcli/local/docker/lambda_image.py", line 493, in is_base_image_current
  File "samcli/local/docker/lambda_image.py", line 509, in get_remote_image_digest
  File "docker/models/images.py", line 356, in get_registry_data
  File "docker/utils/decorators.py", line 34, in wrapper
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/image.py", line 287, in inspect_distribution
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 34, in create_api_error_from_http_exception
  File "docker/errors.py", line 34, in <genexpr>
```

**Comment by hnnasit** [comment] 2023-07-04 01:05
Hi @thiko, thanks for providing those details! This seems very related to the issue 5421 mentioned above. I have left a comment there explaining the root cause. As a work around, can you try running `sam local invoke --skip-pull-image` and check if it works?

**Comment by mndeveci** [comment] 2023-07-04 17:33
Thanks for all the information that you provided @thiko !

As @hnnasit mentioned this is duplicate of https://github.com/aws/aws-sam-cli/issues/5421. Resolving this issue now, let's continue discussion in the other thread.

**Closed by mndeveci** 2023-07-04 17:33 UTC
Labels: stage/needs-investigation
