### ISSUE TITLE
local invoke vs. nested stack function using layer

### ISSUE THREAD

**Issue by mbradburn** [aws/aws-sam-cli#2820] opened 2021-04-21 22:03 UTC
### Describe your idea/feature/enhancement

I think from reading this PR: https://github.com/aws/aws-sam-cli/pull/2760  .. that it's a known issue in the sam cli that you can't pass a layer reference as a parameter from the top-level stack to a function in a nested stack for the purposes of `sam local invoke`; you get a "Layer is an Invalid Layer Arn" error.

It would be deluxe to be able to define a layer in the top-level stack, share that layer with functions in nested stacks, and also be able to use `sam local invoke` for testing.  Is support for that on your roadmap at all?

### Additional Details

I put  a sample project at https://github.com/mbradburn/sam-nested-layer in case I'm unclear in my description of the issue.

**Comment by CoshUS** [comment] 2022-03-15 19:44
Duplicate of https://github.com/aws/aws-sam-cli/issues/3306
Closing.

**Closed by CoshUS** 2022-03-15 19:44 UTC
Labels: type/feature, area/nested-stacks, area/local/invoke, stage/pm-review
