### ISSUE TITLE
Bug: sam local start-api fails when using an OpenAPI specification

### ISSUE THREAD

**Issue by njsaunders** [aws/aws-sam-cli#5602] opened 2023-07-24 10:42 UTC
### Description:

Starting an API locally using an OpenAPI definition fails.

### Steps to reproduce:

1. Clone https://github.com/aws-samples/sam-accelerate-nested-stacks-demo
2. Edit https://github.com/aws-samples/sam-accelerate-nested-stacks-demo/blob/main/api/template.yaml#L42 and remove 'UPDATE'
3. `sam build`
4. `sam local start-api`

### Observed result:

```Error: An invalid OpenApi version was detected: '', must be one of 2.x or 3.x```

But when running `sam local start-api --debug`

The aws-sam-cli appears to be looking for the API definition in the wrong location:

```
2023-07-24 11:17:52,288 | Successfully parsed location from AWS::Include transform: ../../../api/definition/openapi.yaml
2023-07-24 11:17:52,289 | Trying to download Swagger from ../../../api/definition/openapi.yaml
2023-07-24 11:17:52,289 | Unable to download Swagger file. File not found at location /Users/neil/r/other/sam-accelerate-nested-stacks-demo/.aws-sam/build/../../../api/definition/openapi.yaml
```

### Expected result:

API Starts successfully.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
{
  "version": "1.93.0",
  "system": {
    "python": "3.10.12",
    "os": "macOS-13.4.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.12",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by mildaniel** [comment] 2023-07-24 18:25
Seems to be a duplicate of https://github.com/aws/aws-sam-cli/issues/5035. Can you try the suggested steps outlined in that issue and comment back in that thread if the issue persists. In the meantime, I will close this in favour of #5035

**Closed by mildaniel** 2023-07-24 18:25 UTC
Labels: stage/needs-triage
