### ISSUE TITLE
Local API Gateway: Header keys are not lowercased in Lambda payload

### ISSUE THREAD

**Issue by ofhouse** [aws/aws-sam-cli#3034] opened 2021-07-12 15:23 UTC
### Description:
When running the local API Gateway to invoke a local Lambda the payload that is sent to the Lambda differs from what is sent from API Gateway in production.

As stated in the [API Gateway docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html):

> Header names are lowercased.

But when I run the emulator locally the header keys are mostly upper-cased.

### Steps to reproduce:

I created a reproduction repo here: https://github.com/ofhouse/repro-sam-api-gateway-header-keys

Which can be started with
```sh
sam local start-api
```

### Observed result:

It then outputs the event that is sent to the Lambda, which is something like:

```json
{
  "version": "2.0",
  ...
  "headers": {
    "Host": "127.0.0.1:3000",
    "Connection": "keep-alive",
    "Pragma": "no-cache",
    "Cache-Control": "no-cache",
    "Sec-Ch-Ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"",
    "Sec-Ch-Ua-Mobile": "?0",
    "Dnt": "1",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-User": "?1",
    "Sec-Fetch-Dest": "document",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7",
    "X-Forwarded-Proto": "http",
    "X-Forwarded-Port": "3000"
  },
  ...
}
```

### Expected result:

I would expect that all keys that are provided in the `headers` section are lowercased, e.g.

```json
{
  "version": "2.0",
  ...
  "headers": {
    "host": "127.0.0.1:3000",
    "connection": "keep-alive",
    "pragma": "no-cache",
    "cache-control": "no-cache",
    ...
  },
  ...
}
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 11.4
2. `sam --version`: 1.26.0
3. AWS region: xxx

**Comment by CoshUS** [comment] 2021-07-12 17:33
Reproduced and there is a disparity between APIGW and local emulation. However, HTTP header fields should be case-insensitive as stated in [RFC-7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2) and the implementation for parsing them should also be case-insensitive.

**Comment by CoshUS** [comment] 2021-07-15 19:03
Duplicate of https://github.com/aws/aws-sam-cli/issues/1860
Closing.

**Closed by CoshUS** 2021-07-15 19:03 UTC
Labels: type/question
