### ISSUE TITLE
ModuleNotFoundError: No module named 'configparser'

### ISSUE THREAD

**Issue by iancward** [aws/aws-sam-cli#2927] opened 2021-06-03 00:06 UTC
### Description:

I downloaded and installed the SAM CLI, and when I try to validate a template, I get a "ModuleNotFound" error

### Steps to reproduce:

Download and install SAM CLI:

```shell
wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
sudo sam-installation/install
rm -rf aws-sam-cli-linux-x86_64.zip sam-installation/
```

Then attempt to validate a template:

```shell
sam validate
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1257, in invoke
  File "click/core.py", line 700, in make_context
  File "click/core.py", line 1048, in parse_args
  File "click/core.py", line 1630, in handle_parse_result
  File "click/core.py", line 123, in invoke_param_callback
  File "samcli/cli/options.py", line 59, in callback
  File "samcli/cli/context.py", line 90, in profile
  File "samcli/cli/context.py", line 178, in _refresh_session
  File "boto3/__init__.py", line 35, in setup_default_session
  File "boto3/session.py", line 80, in __init__
  File "boto3/session.py", line 120, in _setup_loader
  File "botocore/session.py", line 685, in get_component
  File "botocore/session.py", line 924, in get_component
  File "botocore/session.py", line 158, in <lambda>
  File "botocore/session.py", line 241, in get_config_variable
  File "botocore/configprovider.py", line 313, in get_config_variable
  File "botocore/configprovider.py", line 410, in provide
  File "botocore/configprovider.py", line 471, in provide
  File "botocore/session.py", line 330, in get_scoped_config
  File "botocore/session.py", line 226, in _build_profile_map
  File "botocore/session.py", line 357, in full_config
  File "botocore/configloader.py", line 106, in load_config
  File "botocore/configloader.py", line 147, in raw_config_parse
  File "botocore/vendored/six.py", line 92, in __get__
  File "botocore/vendored/six.py", line 115, in _resolve
  File "botocore/vendored/six.py", line 82, in _import_module
ModuleNotFoundError: No module named 'configparser'
[25539] Failed to execute script __main__
```

### Observed result:

```shell
sam validate
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1257, in invoke
  File "click/core.py", line 700, in make_context
  File "click/core.py", line 1048, in parse_args
  File "click/core.py", line 1630, in handle_parse_result
  File "click/core.py", line 123, in invoke_param_callback
  File "samcli/cli/options.py", line 59, in callback
  File "samcli/cli/context.py", line 90, in profile
  File "samcli/cli/context.py", line 178, in _refresh_session
  File "boto3/__init__.py", line 35, in setup_default_session
  File "boto3/session.py", line 80, in __init__
  File "boto3/session.py", line 120, in _setup_loader
  File "botocore/session.py", line 685, in get_component
  File "botocore/session.py", line 924, in get_component
  File "botocore/session.py", line 158, in <lambda>
  File "botocore/session.py", line 241, in get_config_variable
  File "botocore/configprovider.py", line 313, in get_config_variable
  File "botocore/configprovider.py", line 410, in provide
  File "botocore/configprovider.py", line 471, in provide
  File "botocore/session.py", line 330, in get_scoped_config
  File "botocore/session.py", line 226, in _build_profile_map
  File "botocore/session.py", line 357, in full_config
  File "botocore/configloader.py", line 106, in load_config
  File "botocore/configloader.py", line 147, in raw_config_parse
  File "botocore/vendored/six.py", line 92, in __get__
  File "botocore/vendored/six.py", line 115, in _resolve
  File "botocore/vendored/six.py", line 82, in _import_module
ModuleNotFoundError: No module named 'configparser'
[25539] Failed to execute script __main__
```

### Expected result:

Validaton would succeed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: `Ubuntu  20.04`, WSL2
2. `sam --version`: `SAM CLI, version 1.24.0`
3. AWS region: `us-west-2`

`Add --debug flag to command you are running`

```shell
sam validate -t template.yaml --debug
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1257, in invoke
  File "click/core.py", line 700, in make_context
  File "click/core.py", line 1048, in parse_args
  File "click/core.py", line 1630, in handle_parse_result
  File "click/core.py", line 123, in invoke_param_callback
  File "samcli/cli/options.py", line 59, in callback
  File "samcli/cli/context.py", line 90, in profile
  File "samcli/cli/context.py", line 178, in _refresh_session
  File "boto3/__init__.py", line 35, in setup_default_session
  File "boto3/session.py", line 80, in __init__
  File "boto3/session.py", line 120, in _setup_loader
  File "botocore/session.py", line 685, in get_component
  File "botocore/session.py", line 924, in get_component
  File "botocore/session.py", line 158, in <lambda>
  File "botocore/session.py", line 241, in get_config_variable
  File "botocore/configprovider.py", line 313, in get_config_variable
  File "botocore/configprovider.py", line 410, in provide
  File "botocore/configprovider.py", line 471, in provide
  File "botocore/session.py", line 330, in get_scoped_config
  File "botocore/session.py", line 226, in _build_profile_map
  File "botocore/session.py", line 357, in full_config
  File "botocore/configloader.py", line 106, in load_config
  File "botocore/configloader.py", line 147, in raw_config_parse
  File "botocore/vendored/six.py", line 92, in __get__
  File "botocore/vendored/six.py", line 115, in _resolve
  File "botocore/vendored/six.py", line 82, in _import_module
ModuleNotFoundError: No module named 'configparser'
[25777] Failed to execute script __main__
```

**Comment by iongion** [comment] 2021-06-03 04:27
Any way to mitigate this until it get solved ? I am unable to deploy anything due to it.
I get it on all sam commands, even `sam build`

**Comment by iongion** [comment] 2021-06-03 04:32
To answer my own question, downgrading to `1.23` downloaded from `https://github.com/aws/aws-sam-cli/releases/download/v1.23.0/aws-sam-cli-linux-x86_64.zip` works again

**Comment by c2tarun** [comment] 2021-06-03 19:25
I tried and couldn't reproduce the issue on a Ubuntu instance. Going to try in WSL now.

**Comment by aahung** [comment] 2021-06-03 19:25
`configparser` is built in Python 3 module. Looks like somehow the sam cli is executed with Python 2

**Comment by mgrandis** [comment] 2021-06-03 19:38
Yes I got the error on a Linux machine where `python` is python2

**Comment by mgrandis** [comment] 2021-06-03 20:53
@iancward @iongion 
What does `python --version` return on the affected machines?

**Comment by iongion** [comment] 2021-06-03 21:58
Ubuntu 20.04 in WSL, python -v, it shows 2.x not 3.x - as mentioned before,
downgrading did the job and solved my problem, I can deploy again, but of
course I would like to use the latest version, even tried the edge one,
still the same problmem unfortunately. Let me know if you need anything
else.

**Comment by iancward** [comment] 2021-06-03 22:35
> @iancward @iongion
> What does `python --version` return on the affected machines?

`python -V` shows
> Python 2.7.18

On most systems I've worked on, `python` (if it exists) goes to Python 2, while `python3` goes to Python 3. 

On my system, `python3 -V` shows
> Python 3.8.5

**Comment by n0pj** [comment] 2021-06-04 08:02
> To answer my own question, downgrading to `1.23` downloaded from `https://github.com/aws/aws-sam-cli/releases/download/v1.23.0/aws-sam-cli-linux-x86_64.zip` works again

Thank you. I was getting same error.
``` shell
curl -OL https://github.com/aws/aws-sam-cli/releases/download/v1.23.0/aws-sam-cli-linux-x86_64.zip
unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
cd sam-installation
sudo ./install --update
```
Works fine.

`python -V`

>Command 'python' not found, did you mean:...

`python -V`
>Python 3.8.5

`cat /etc/os-release`
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
...
```

**Comment by vinicius0197** [comment] 2021-06-04 18:15
I'm also getting the same issue on Ubuntu 20.04.2 LTS, where `python -V` is: `command not found: python`.

**Comment by c2tarun** [comment] 2021-06-04 23:12
> To answer my own question, downgrading to `1.23` downloaded from `https://github.com/aws/aws-sam-cli/releases/download/v1.23.0/aws-sam-cli-linux-x86_64.zip` works again

We are working on a fix for this issue, meanwhile please follow @iongion's recommendation of using version 1.23.0 as a workaround.

**Comment by mgrandis** [comment] 2021-06-07 22:09
1.24.1 was released to address this issue: https://github.com/aws/aws-sam-cli/releases/tag/v1.24.1
Can you try again and tell us if it is fixed for you?
Thanks.

**Comment by endymion** [comment] 2021-06-08 16:11
I ran into this problem today on an instance where `python --version` is 3.7.9:

    [ec2-user@ip-10-0-4-218 tmp]$ python --version
    Python 3.7.9

I can confirm that the v1.24.1 update fixes the problem.

PS: Unrelated, but it would help a lot if it were possible to install SAM on anything other than an x86 architecture.  AWS did a fantastic job with Gravitron2 but we still can't run SAM on it, even though SAM is Python code. 👎

**Comment by mgrandis** [comment] 2021-06-08 21:03
Thank you for your feedback @endymion 
For ARM, I was about to redirect you to #2713 but I see you already replied there.

**Closed by mgrandis** 2021-06-08 21:03 UTC
Labels: area/installation
