### ISSUE TITLE
local invoke parameter overrides not applied to nested-stack function

### ISSUE THREAD

**Issue by mbradburn** [aws/aws-sam-cli#2763] opened 2021-03-24 21:53 UTC
### Description:

Apologies in advance if I've missed something that should be obvious.

Usually I'm able to give `sam local invoke` a set of parameter overrides; in this example I'm setting a function's memory configuration.  Except when that function is defined in a nested application's template -- it seems that the parameter overrides are not effective for a function in a nested stack.  I should add I first noticed this with `sam local start-api`, probably the issue is the same for both commands.

### Steps to reproduce:
Create a function in a nested application template whose memory configuration is taken from a parameter value.  Invoke it with `sam local invoke Function --parameter-override='ParameterKey=Mem,ParameterValue=256'`.  There's an example set of templates and function source at https://github.com/mbradburn/sam-test if that helps.

### Observed result:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/docker/utils/utils.py", line 415, in parse_bytes
    digits = int(digits_part)
ValueError: invalid literal for int() with base 10: '/development/mem'
```

### Expected result:
I thought parameter overrides would be effective for the function configuration.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
2. `sam --version`: SAM CLI, version 1.21.1
3. AWS region: us-west-2

`Add --debug flag to command you are running`

2021-03-24 14:35:36,723 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-03-24 14:35:36,724 | Using config file: samconfig.toml, config environment: default
2021-03-24 14:35:36,724 | Expand command line arguments to:
2021-03-24 14:35:36,724 | --template_file=/Users/matthew/dev/sam-test/.aws-sam/build/template.yaml --parameter_overrides={'Mem': '256'} --function_logical_id=Function --no_event --layer_cache_basedir=/Users/matthew/.aws-sam/layers-pkg 
2021-03-24 14:35:36,724 | local invoke command is called
2021-03-24 14:35:36,726 | No Parameters detected in the template
2021-03-24 14:35:36,770 | 1 stacks found in the template
2021-03-24 14:35:36,777 | Collected default values for parameters: {'Mem': '/development/mem'}
2021-03-24 14:35:36,798 | 1 stacks found in the template
2021-03-24 14:35:36,798 | No Parameters detected in the template
2021-03-24 14:35:36,823 | 1 resources found in the stack 
2021-03-24 14:35:36,824 | Collected default values for parameters: {'Mem': '/development/mem'}
2021-03-24 14:35:36,847 | 1 resources found in the stack nested
2021-03-24 14:35:36,847 | No Parameters detected in the template
2021-03-24 14:35:36,869 | Collected default values for parameters: {'Mem': '/development/mem'}
2021-03-24 14:35:36,889 | Found Serverless function with name='Function' and CodeUri='Function'
2021-03-24 14:35:36,889 | --base-dir is presented not, adjusting uri Function relative to /Users/matthew/dev/sam-test/.aws-sam/build/nested/template.yaml
2021-03-24 14:35:36,902 | Found one Lambda function with name 'Function'
2021-03-24 14:35:36,902 | Invoking index.handler (nodejs14.x)
2021-03-24 14:35:36,902 | No environment variables found for function 'Function'
2021-03-24 14:35:36,903 | Environment variables overrides data is standard format
2021-03-24 14:35:36,903 | Loading AWS credentials from session with profile 'None'
2021-03-24 14:35:36,917 | Resolving code path. Cwd=/Users/matthew/dev/sam-test/.aws-sam/build, CodeUri=/Users/matthew/dev/sam-test/.aws-sam/build/nested/Function
2021-03-24 14:35:36,917 | Resolved absolute path to code is /Users/matthew/dev/sam-test/.aws-sam/build/nested/Function
2021-03-24 14:35:36,918 | Code /Users/matthew/dev/sam-test/.aws-sam/build/nested/Function is not a zip/jar file
2021-03-24 14:35:36,939 | Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-nodejs14.x:rapid-1.21.1.

2021-03-24 14:35:36,939 | Mounting /Users/matthew/dev/sam-test/.aws-sam/build/nested/Function as /var/task:ro,delegated inside runtime container
2021-03-24 14:35:36,939 | Cleaning all decompressed code dirs
2021-03-24 14:35:36,940 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'c12906dc-b8ab-4b9d-a998-2bbfc68b30bd', 'installationId': '1ec213d9-ab2a-4399-a21b-76682cb750da', 'sessionId': '0562563e-284a-4fc1-8867-7a8d42c87a94', 'executionEnvironment': 'CLI', 'pyversion': '3.8.8', 'samcliVersion': '1.21.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 215, 'exitReason': 'DockerException', 'exitCode': 255}}]}
2021-03-24 14:35:37,048 | Telemetry response: 200
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/docker/utils/utils.py", line 415, in parse_bytes
    digits = int(digits_part)
ValueError: invalid literal for int() with base 10: '/development/mem'

**Comment by aahung** [comment] 2021-03-24 23:03
@mbradburn thanks for reaching out. In which template you define the parameter "Mem?" root or the children templates?

**Comment by mbradburn** [comment] 2021-03-24 23:06
It's listed in the Parameters section of the child template.

**Comment by aahung** [comment] 2021-03-24 23:34
> It's listed in the Parameters section of the child template.

`--parameter-overrides` can only pass parameters to the root template (the one you specified using cli option `-t`, or the default `.aws-sam/build/template.yaml`).

Do you have such `Mem` parameter defined in your root template as well?

**Comment by mbradburn** [comment] 2021-03-24 23:44
I've added the parameter to the root template, but that doesn't change the failure for 'sam local invoke', I assume because it's in the child template that the parameter value is needed.  (I updated my sample repo for your reference.)

It seems like this might be By Design?  Is it not possible to use 'sam local invoke' on a child stack's function that depends on a parameter override?

**Comment by aahung** [comment] 2021-03-24 23:54
Thanks for providing a sample. This is a limitation of sam-cli, where we don't support resolving parameters of "SSM Parameter Types." 

> It seems like this might be By Design? Is it not possible to use 'sam local invoke' on a child stack's function that depends on a parameter override?

by design, `--parameter-overrides` act the same as the one you use in `sam deploy`, so only root template will receive that overrides. If you want to invoke a function in child stack with parameter overrides, there are two ways to do that (using your example):
1. `sam build -t nested/template.yaml` and then `sam local invoke --parameter-overrides...`
2. not to use "SSM Parameter Types." in child template, instead, pass the one in root to child:
```diff
# root
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  nested:
    Properties:
      Location: nested/template.yaml
+     Parameters:
+       Mem: !Ref Mem
    Type: AWS::Serverless::Application
Parameters:
  Mem:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /development/mem


# child
Parameters:
  Mem:
-    Type: AWS::SSM::Parameter::Value<String>
+    Type: Integer
-    Default: /development/mem
```

**Comment by mbradburn** [comment] 2021-03-24 23:59
Thanks for the clarification!  I was assuming I'd found a bug, so feel free to close this issue, or leave it open if you think you might want to offer this as a feature.

**Comment by aahung** [comment] 2021-03-25 00:02
> Thanks for the clarification! I was assuming I'd found a bug, so feel free to close this issue, or leave it open if you think you might want to offer this as a feature.

You are welcome! I am gonna close this one, it seems to be a duplicate of #1069, I also reference this issue to #1069 and #2743. Thanks again for reporting!

**Closed by aahung** 2021-03-25 00:02 UTC
Labels: area/nested-stacks, type/feature
