### ISSUE TITLE
aws sam build breaks with numpy version 1.20.3

### ISSUE THREAD

**Issue by kannanprasanna** [aws/aws-sam-cli#2882] opened 2021-05-14 18:57 UTC
### Description:
Python lambda function with numpy in the requirements file fails to build. Looks like numpy released a new version 1.20.3 on May 10 after which our sam builds are not working. If we set the numpy version to 1.20.2, it works fine. pip installs of numpy 1.20.3 works fine, but only sam builds are failing.

Numpy latest - numpy-1.20.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Numpy previous - numpy-1.20.2-cp38-cp38-manylinux2010_x86_64.whl

Looks like they added manylinux_2 in the name, could this be the problem?

### Steps to reproduce:
sam build --template template.yaml
Building codeuri: /jenkins/workspace/xxxxx/lambda/xxxxxx/source runtime: python3.8 metadata: {} functions: ['MyFunction']
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - {numpy==1.20.3(wheel)}

### Observed result:
2021-05-14 15:57:51,244 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-05-14 15:57:51,244 | Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-05-14 15:57:51,263 | Running workflow 'PythonPipBuilder'
2021-05-14 15:57:51,263 | Running PythonPipBuilder:ResolveDependencies
2021-05-14 15:57:51,290 | calling pip download -r /jenkins/workspace/xxxxxxxxx/lambda/xxxxxxx/source/requirements.txt --dest /tmp/tmpi_0u82yi

2021-05-14 15:57:55,175 | Full dependency closure: {numpy==1.20.3(wheel), boto3==1.17.72(wheel), psycopg2-binary==2.8.6(wheel), pybase64==1.1.4(wheel), chardet==4.0.0(wheel), six==1.16.0(wheel), monotonic==1.6(wheel), botocore==1.20.72(wheel), python-dateutil==2.8.1(wheel), certifi==2020.12.5(wheel), idna==2.10(wheel), jmespath==0.10.0(wheel), future-fstrings==1.2.0(wheel), s3transfer==0.4.2(wheel), urllib3==1.26.4(wheel), requests==2.25.1(wheel), lru-expiring-cache==1.1(wheel)}
2021-05-14 15:57:55,175 | initial compatible: {boto3==1.17.72(wheel), requests==2.25.1(wheel), psycopg2-binary==2.8.6(wheel), pybase64==1.1.4(wheel), chardet==4.0.0(wheel), monotonic==1.6(wheel), botocore==1.20.72(wheel), python-dateutil==2.8.1(wheel), certifi==2020.12.5(wheel), idna==2.10(wheel), jmespath==0.10.0(wheel), lru-expiring-cache==1.1(wheel), s3transfer==0.4.2(wheel), urllib3==1.26.4(wheel), future-fstrings==1.2.0(wheel), six==1.16.0(wheel)}
2021-05-14 15:57:55,175 | initial incompatible: {numpy==1.20.3(wheel)}
2021-05-14 15:57:55,175 | Downloading missing wheels: {numpy==1.20.3(wheel)}
2021-05-14 15:57:55,175 | calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp38 --dest /tmp/tmpi_0u82yi numpy==1.20.3

2021-05-14 15:57:56,152 | compatible wheels after second download pass: {boto3==1.17.72(wheel), psycopg2-binary==2.8.6(wheel), pybase64==1.1.4(wheel), chardet==4.0.0(wheel), six==1.16.0(wheel), monotonic==1.6(wheel), botocore==1.20.72(wheel), python-dateutil==2.8.1(wheel), certifi==2020.12.5(wheel), idna==2.10(wheel), jmespath==0.10.0(wheel), future-fstrings==1.2.0(wheel), s3transfer==0.4.2(wheel), urllib3==1.26.4(wheel), requests==2.25.1(wheel), lru-expiring-cache==1.1(wheel)}
2021-05-14 15:57:56,152 | Build missing wheels from sdists (C compiling True): set()
2021-05-14 15:57:56,152 | compatible after building wheels (no C compiling): {boto3==1.17.72(wheel), psycopg2-binary==2.8.6(wheel), pybase64==1.1.4(wheel), chardet==4.0.0(wheel), six==1.16.0(wheel), monotonic==1.6(wheel), botocore==1.20.72(wheel), python-dateutil==2.8.1(wheel), certifi==2020.12.5(wheel), idna==2.10(wheel), jmespath==0.10.0(wheel), future-fstrings==1.2.0(wheel), s3transfer==0.4.2(wheel), urllib3==1.26.4(wheel), requests==2.25.1(wheel), lru-expiring-cache==1.1(wheel)}
2021-05-14 15:57:56,153 | Build missing wheels from sdists (C compiling False): set()
2021-05-14 15:57:56,153 | compatible after building wheels (C compiling): {boto3==1.17.72(wheel), psycopg2-binary==2.8.6(wheel), pybase64==1.1.4(wheel), chardet==4.0.0(wheel), six==1.16.0(wheel), monotonic==1.6(wheel), botocore==1.20.72(wheel), python-dateutil==2.8.1(wheel), certifi==2020.12.5(wheel), idna==2.10(wheel), jmespath==0.10.0(wheel), future-fstrings==1.2.0(wheel), s3transfer==0.4.2(wheel), urllib3==1.26.4(wheel), requests==2.25.1(wheel), lru-expiring-cache==1.1(wheel)}
2021-05-14 15:57:56,153 | Final compatible: {psycopg2-binary==2.8.6(wheel), pybase64==1.1.4(wheel), monotonic==1.6(wheel), python-dateutil==2.8.1(wheel), certifi==2020.12.5(wheel), idna==2.10(wheel), lru-expiring-cache==1.1(wheel), urllib3==1.26.4(wheel), requests==2.25.1(wheel), boto3==1.17.72(wheel), chardet==4.0.0(wheel), botocore==1.20.72(wheel), jmespath==0.10.0(wheel), s3transfer==0.4.2(wheel), future-fstrings==1.2.0(wheel), six==1.16.0(wheel)}
2021-05-14 15:57:56,153 | Final incompatible: {numpy==1.20.3(wheel)}
2021-05-14 15:57:56,153 | Final missing wheels: {numpy==1.20.3(wheel)}

2021-05-14 15:57:56,569 | PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/tmp/conda/envs/xxxxxxxxxx/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/tmp/conda/envs/xxxxxxxxx/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/tmp/conda/envs/xxxxxxxxxxx/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {numpy==1.20.3(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/conda/envs/xxxxxxx/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/tmp/conda/envs/xxxxxxx/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {numpy==1.20.3(wheel)}

Build Failed
Error: PythonPipBuilder:ResolveDependencies - {numpy==1.20.3(wheel)}

### Expected result:
sam build should work correctly with latest numpy package

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux 2
2. `sam --version`: 1.23.0
3. AWS region: us-east-1

**Comment by wdougoveto** [comment] 2021-05-14 19:01
We are having the same issue.

**Comment by aahung** [comment] 2021-05-14 20:28
Thanks for reporting, this should be a duplicate of #2865, where we need to support PEP 600 in https://github.com/aws/aws-lambda-builders

**Closed by aahung** 2021-05-14 20:28 UTC
Labels: area/build, type/duplicate
