### ISSUE TITLE
Metadata attribute for resources

### ISSUE THREAD

**Issue by OperationalFallacy** [aws/aws-sam-cli#2547] opened 2021-01-21 15:26 UTC
Hi,

Does sam support metadata attribute for resources it creates?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html

I was looking for ways to "annotate" CF resources with the information about monitoring and notifications, so developers can define it within sam template.

Thanks!
Roman

**Comment by aahung** [comment] 2021-01-21 21:50
Yes we support it. SAM will pass this metadata directly to CFN in this case.

**Comment by OperationalFallacy** [comment] 2021-02-10 20:52
Hi @aahung 

It seems like there are some questionable design choices made which prevent sam working with metadata. 

1. It is mentioned somewhere in issues already I think, about Metadata reserved for its own purpose in sam: "The AWS::Serverless::Function resource also supports the Metadata resource attribute, so you can instruct AWS SAM to build custom runtimes that your application requires." 

I tried Metadata on "AWS::Serverless::Function" and it doesn't work - "rendered template" has nothing, and neither CF resource.

2. But Metadata works with Sqs https://docs.aws.amazon.com/lambda/latest/dg/with-sqs-example-use-app-spec.html , yet not with SimpleTable https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html

Can you consider making this more unified to allow every resource pass metadata in the CF template?

Thanks!

**Comment by elbayaaa** [comment] 2021-02-11 04:20
Hi @OperationalFallacy

You are right I am able to reproduce the issue. Metadata works fine for non SAM resources(like SQS) but for SAM resources(like SimpleTable) it doesn't work as expected; although the property is accepted as a valid one, the metadata are not shown when `aws cloudformation describe-stack-resource`.

Also Metadata property of AWS::Serverless::Function is a special one as it is conditionally required when the "PackageType" is "Image" to define docker attributes see [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build.html#build-container-image)

**Comment by OperationalFallacy** [comment] 2021-02-11 16:07
Related: https://github.com/aws/serverless-application-model/issues/264

@elbayaaa  do you think this is Cloudformation issue? CF is transforming template with "AWS::Serverless" macro according to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html

You can see how Metadata is absent in "processed template" in the console and this is not something code from this repo is doing, right?

**Comment by elbayaaa** [comment] 2021-02-11 17:30
We(SAM) own the transformation logic so it is an issue in our side.

**Comment by OperationalFallacy** [comment] 2021-03-14 03:18
Hey @elbayaaa, can you pull some strings at CloudFormation HQ?

I'm personally not developing anything atm that requires this functionality.

If somebody thinking about CF resources testing, monitoring or other similar purposes - when templates originated in SAM - they would abandon idea early.

Thanks!

**Comment by mndeveci** [comment] 2021-06-09 17:12
Closing this issue since it is been released with [SAM v1.36.0](https://github.com/aws/serverless-application-model/releases/tag/v1.36.0) and [SAM CLI v1.24.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.24.0).

You can read more about how resource level attributes are handled in SAM via our updated documentation; https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resource-attributes.html

Thanks!

**Closed by mndeveci** 2021-06-09 17:12 UTC
Labels: stage/pm-review, type/bug, type/feature, type/question

**Comment by OperationalFallacy** [comment] 2021-06-09 17:58
@mndeveci, thanks!

I run `sam validate --debug` and found metadata in the rendered template!
