### ISSUE TITLE
Poppler (custom library) layer local file path deploys differently than with zip file

### ISSUE THREAD

**Issue by AChenny** [aws/aws-sam-cli#2062] opened 2020-06-22 02:13 UTC
### Description
Deploying on SAM using a local filepath creates a different layer than deploying using a .zip file. As a result of this, this causes Poppler (possibly other custom libraries) to fail and not be found. 
I downloaded the .zip files from each method of uploading the layer and they have difference sizes zipped. Extracting the files seem to be the exact same.
[Package](https://github.com/awslabs/aws-sam-cli/files/4810821/package_from_console_upload.zip) from a console upload
[Package](https://github.com/awslabs/aws-sam-cli/files/4810827/package_from_sam_deploy_filepath.zip) from a SAM deploy upload

### Steps to reproduce

1. Create a new hello world project with SAM in python 3.8
2. Download the package.zip attached here
[package.zip](https://github.com/awslabs/aws-sam-cli/files/4810626/package.zip) 
3. Create a directory in the root of the project named poppler and extract contents from the zip folder to there.
4. Add a these line in the Resources in `template.yaml`
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PopplerLayer
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  PopplerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: poppler/
```
5. Add pdf2image to the requirements.txt in /hello_world
6. In app.py: 
```
import json
from pdf2image import convert_from_bytes
# import requests

def lambda_handler(event, context):
    convert_from_bytes(b'', poppler_path='/opt/bin/')

    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world",
        }),
    }
```

7. Build and deploy to AWS using `sam build --use-container` then `sam deploy --guided`
8. In the hello world function in AWS Console do a default test
9. Observe that with the SAM deployment, the error will be from not being able to get the poppler path. 
10. In the AWS Console, create a new version of the layer we created and upload the .zip folder
11. Update the HelloWorldFunction lambda to use the new layer version
12. Re-test the HelloWorldFunction and the error should now be the expected result

### Observed result
```
Response:
{
  "errorMessage": "Unable to get page count. Is poppler installed and in PATH?",
  "errorType": "PDFInfoNotInstalledError",
  "stackTrace": [
    "  File \"/var/task/app.py\", line 7, in lambda_handler\n    convert_from_bytes(b'', poppler_path='/opt/bin/')\n",
    "  File \"/var/task/pdf2image/pdf2image.py\", line 260, in convert_from_bytes\n    return convert_from_path(\n",
    "  File \"/var/task/pdf2image/pdf2image.py\", line 94, in convert_from_path\n    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)[\"Pages\"]\n",
    "  File \"/var/task/pdf2image/pdf2image.py\", line 441, in pdfinfo_from_path\n    raise PDFInfoNotInstalledError(\n"
  ]
}

Request ID:
"bacc5e07-b9fa-4664-99b1-0a8eb34b74d2"

Function Logs:
START RequestId: bacc5e07-b9fa-4664-99b1-0a8eb34b74d2 Version: $LATEST
[ERROR] PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
Traceback (most recent call last):
  File "/var/task/app.py", line 7, in lambda_handler
    convert_from_bytes(b'', poppler_path='/opt/bin/')
  File "/var/task/pdf2image/pdf2image.py", line 260, in convert_from_bytes
    return convert_from_path(
  File "/var/task/pdf2image/pdf2image.py", line 94, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "/var/task/pdf2image/pdf2image.py", line 441, in pdfinfo_from_path
    raise PDFInfoNotInstalledError(END RequestId: bacc5e07-b9fa-4664-99b1-0a8eb34b74d2
REPORT RequestId: bacc5e07-b9fa-4664-99b1-0a8eb34b74d2	Duration: 11.71 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 59 MB	
```

### Expected result

```
Response:
{
  "errorMessage": "Unable to get page count.\nSyntax Warning: May not be a PDF file (continuing anyway)\nSyntax Error: Couldn't find trailer dictionary\nSyntax Error: Couldn't find trailer dictionary\nSyntax Error: Couldn't read xref table\n",
  "errorType": "PDFPageCountError",
  "stackTrace": [
    "  File \"/var/task/app.py\", line 7, in lambda_handler\n    convert_from_bytes(b'', poppler_path='/opt/bin/')\n",
    "  File \"/var/task/pdf2image/pdf2image.py\", line 260, in convert_from_bytes\n    return convert_from_path(\n",
    "  File \"/var/task/pdf2image/pdf2image.py\", line 94, in convert_from_path\n    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)[\"Pages\"]\n",
    "  File \"/var/task/pdf2image/pdf2image.py\", line 445, in pdfinfo_from_path\n    raise PDFPageCountError(\n"
  ]
}

Request ID:
"bf3889f5-3d5d-4cda-bde5-8bb04cca2aaa"

Function Logs:
START RequestId: bf3889f5-3d5d-4cda-bde5-8bb04cca2aaa Version: $LATEST
[ERROR] PDFPageCountError: Unable to get page count.
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

Traceback (most recent call last):
  File "/var/task/app.py", line 7, in lambda_handler
    convert_from_bytes(b'', poppler_path='/opt/bin/')
  File "/var/task/pdf2image/pdf2image.py", line 260, in convert_from_bytes
    return convert_from_path(
  File "/var/task/pdf2image/pdf2image.py", line 94, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "/var/task/pdf2image/pdf2image.py", line 445, in pdfinfo_from_path
    raise PDFPageCountError(END RequestId: bf3889f5-3d5d-4cda-bde5-8bb04cca2aaa
REPORT RequestId: bf3889f5-3d5d-4cda-bde5-8bb04cca2aaa	Duration: 702.47 ms	Billed Duration: 800 ms	Memory Size: 128 MB	Max Memory Used: 64 MB	Init Duration: 199.83 ms	
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 Education Version 10.0.19041
2. `sam --version`: 0.53.0

**Comment by hawflau** [comment] 2020-09-03 15:47
The two zip files are not exactly the same.

Package from a console upload (leads to Expected Result):
```
Archive:  pc.zip
Zip file size: 4096115 bytes, number of entries: 28
drwxr-xr-x  3.0 unx        0 bx  0% stor 20-Jun-20 12:39 bin/
-rw-r--r--  3.0 unx     5096 bx 59% defX 20-Jun-20 12:39 bin/parseargs.o
-rw-r--r--  3.0 unx     5276 bx 60% defX 20-Jun-20 12:39 bin/libparseargs.a
-rwxr-xr-x  3.0 unx    62248 bx 65% defX 20-Jun-20 12:39 bin/pdfimages
-rwxr-xr-x  3.0 unx   114232 bx 63% defX 20-Jun-20 12:39 bin/pdftohtml
-rwxr-xr-x  3.0 unx    20848 bx 64% defX 20-Jun-20 12:39 bin/pdfdetach
-rwxr-xr-x  3.0 unx    45464 bx 60% defX 20-Jun-20 12:39 bin/pdfinfo
-rwxr-xr-x  3.0 unx    15656 bx 60% defX 20-Jun-20 12:39 bin/pdfseparate
-rwxr-xr-x  3.0 unx    27472 bx 62% defX 20-Jun-20 12:39 bin/pdftoppm
-rwxr-xr-x  3.0 unx    38384 bx 62% defX 20-Jun-20 12:39 bin/pdftotext
-rwxr-xr-x  3.0 unx    32104 bx 59% defX 20-Jun-20 12:39 bin/pdfunite
-rwxr-xr-x  3.0 unx    16984 bx 62% defX 20-Jun-20 12:39 bin/pdffonts
-rwxr-xr-x  3.0 unx    23904 bx 61% defX 20-Jun-20 12:39 bin/pdftops
-rw-r--r--  3.0 unx      878 tx 48% defX 20-Jun-20 12:39 bin/libparseargs.la
drwxr-xr-x  3.0 unx        0 bx  0% stor 20-Jun-20 12:54 lib/
-rwxr-xr-x  3.0 unx   127280 bx 51% defX 20-Jun-20 12:38 lib/libopenjpeg.so.2
-rwxr-xr-x  3.0 unx  2992832 bx 66% defX 20-Jun-20 12:39 lib/libpoppler.so.70
-rwxr-xr-x  3.0 unx   155824 bx 54% defX 20-Jun-20 12:38 lib/libpng12.so.0
-rwxr-xr-x  3.0 unx   217784 bx 52% defX 20-Jun-20 12:38 lib/libfontconfig.so.1
-rwxr-xr-x  3.0 unx    88608 bx 47% defX 20-Jun-20 12:38 lib/libz.so.1
-rwxr-xr-x  3.0 unx   276072 bx 59% defX 20-Jun-20 12:38 lib/libjpeg.so.62
-rwxr-xr-x  3.0 unx   168048 bx 64% defX 20-Jun-20 12:38 lib/libexpat.so.1
-rwxr-xr-x  3.0 unx   639184 bx 50% defX 20-Jun-20 12:38 lib/libfreetype.so.6
-rwxr-xr-x  3.0 unx   468376 bx 66% defX 20-Jun-20 12:38 lib/libtiff.so.5
-rwxr-xr-x  3.0 unx    50712 bx 57% defX 20-Jun-20 12:38 lib/libjbig.so.2.0
-rw-r--r--  3.0 unx  3732342 bx 75% defX 20-Jun-20 12:53 lib/libpoppler.a
-rwxr-xr-x  3.0 unx  2992832 bx 66% defX 20-Jun-20 12:54 lib/libpoppler.so
-rw-r--r--  3.0 unx     1028 tx 49% defX 20-Jun-20 12:54 lib/libpoppler.la
28 files, 12319468 bytes uncompressed, 4091679 bytes compressed:  66.8%
```

Package from a SAM deploy upload (leads to Observed Result)
```
Archive:  ps.zip
Zip file size: 4110892 bytes, number of entries: 26
-rw-rw-rw-  2.0 fat     5276 b- 59% defN 20-Jun-20 12:39 bin/libparseargs.a
-rw-rw-rw-  2.0 fat      878 b- 48% defN 20-Jun-20 12:39 bin/libparseargs.la
-rw-rw-rw-  2.0 fat     5096 b- 59% defN 20-Jun-20 12:39 bin/parseargs.o
-rw-rw-rw-  2.0 fat    20848 b- 64% defN 20-Jun-20 12:39 bin/pdfdetach
-rw-rw-rw-  2.0 fat    16984 b- 61% defN 20-Jun-20 12:39 bin/pdffonts
-rw-rw-rw-  2.0 fat    62248 b- 65% defN 20-Jun-20 12:39 bin/pdfimages
-rw-rw-rw-  2.0 fat    45464 b- 60% defN 20-Jun-20 12:39 bin/pdfinfo
-rw-rw-rw-  2.0 fat    15656 b- 60% defN 20-Jun-20 12:39 bin/pdfseparate
-rw-rw-rw-  2.0 fat   114232 b- 62% defN 20-Jun-20 12:39 bin/pdftohtml
-rw-rw-rw-  2.0 fat    27472 b- 62% defN 20-Jun-20 12:39 bin/pdftoppm
-rw-rw-rw-  2.0 fat    23904 b- 61% defN 20-Jun-20 12:39 bin/pdftops
-rw-rw-rw-  2.0 fat    38384 b- 61% defN 20-Jun-20 12:39 bin/pdftotext
-rw-rw-rw-  2.0 fat    32104 b- 59% defN 20-Jun-20 12:39 bin/pdfunite
-rw-rw-rw-  2.0 fat   168048 b- 63% defN 20-Jun-20 12:38 lib/libexpat.so.1
-rw-rw-rw-  2.0 fat   217784 b- 52% defN 20-Jun-20 12:38 lib/libfontconfig.so.1
-rw-rw-rw-  2.0 fat   639184 b- 50% defN 20-Jun-20 12:38 lib/libfreetype.so.6
-rw-rw-rw-  2.0 fat    50712 b- 57% defN 20-Jun-20 12:38 lib/libjbig.so.2.0
-rw-rw-rw-  2.0 fat   276072 b- 58% defN 20-Jun-20 12:38 lib/libjpeg.so.62
-rw-rw-rw-  2.0 fat   127280 b- 50% defN 20-Jun-20 12:38 lib/libopenjpeg.so.2
-rw-rw-rw-  2.0 fat   155824 b- 53% defN 20-Jun-20 12:38 lib/libpng12.so.0
-rw-rw-rw-  2.0 fat  3732342 b- 75% defN 20-Jun-20 12:53 lib/libpoppler.a
-rw-rw-rw-  2.0 fat     1028 b- 49% defN 20-Jun-20 12:54 lib/libpoppler.la
-rw-rw-rw-  2.0 fat  2992832 b- 66% defN 20-Jun-20 12:54 lib/libpoppler.so
-rw-rw-rw-  2.0 fat  2992832 b- 66% defN 20-Jun-20 12:39 lib/libpoppler.so.70
-rw-rw-rw-  2.0 fat   468376 b- 65% defN 20-Jun-20 12:38 lib/libtiff.so.5
-rw-rw-rw-  2.0 fat    88608 b- 47% defN 20-Jun-20 12:38 lib/libz.so.1
26 files, 12319468 bytes uncompressed, 4108080 bytes compressed:  66.7%
```

We might need to investigate on how the zip files are prepared during `sam deploy`.

**Comment by hawflau** [comment] 2020-09-03 23:49
@AChenny It turned out that the Observed Result was due to non-executable binaries in `PopplerLayer`, as you can see there is no `x`(executable) in the second list above. After adding back the permissions and updating the `LayerVersion`, I achieved the Expected Result.

I also reproduced the results on Windows, and found that the `x` permissions were stripped in the created `LayerVersion`. However, when I directly referenced `package.zip` for `contentUri` in `template.yaml`, the `x` permissions are preserved and it led the expected result. It appears that Windows strips the `x` permissions during the unzip and re-zip process, independently of SAM CLI. 

Our recommendation is, if you have the zip file already for the layer, you could directly reference it like this:
```
Resources:
  PopplerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: path/to/package.zip
```
In such way, you could avoid any unwanted change in the permissions.
I will close the issue for now. If the fix doesn't work for you, please reopen the issue and we will come back to it :)

**Closed by hawflau** 2020-09-03 23:49 UTC
Labels: bug/repro, contributors/good-first-issue, stage/needs-investigation
