### ISSUE TITLE
brew upgrade is not working fine

### ISSUE THREAD

**Issue by moelasmar** [aws/aws-sam-cli#2352] opened 2020-11-03 20:57 UTC
### Description
The upgrade process for SAM CLI on a fresh Cloud9 instance doesn't work:
```
admin:~/environment $ sam --version
SAM CLI, version 1.6.2
admin:~/environment $ brew upgrade aws-sam-cli
Initialized empty Git repository in /home/linuxbrew/.linuxbrew/.git/
Updating Homebrew...
...
...
admin:~/environment $ sam --version
bash: /home/linuxbrew/.linuxbrew/bin/sam: No such file or directory
admin:~/environment $ /home/linuxbrew/.linuxbrew/bin/sam
bash: /home/linuxbrew/.linuxbrew/bin/sam: No such file or directory
```

Only (uninstalling and) installing SAM CLI again is going to help:
```
admin:~/environment $ brew uninstall aws-sam-cli
Uninstalling /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0.reinstall... (4,092 files, 99MB)
admin:~/environment $ brew install aws-sam-cli
==> Installing aws-sam-cli from aws/tap
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.7.0//aws-sam-cli-1.7.0.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ec2-user/.cache/Homebrew/downloads/73b77c89ff09cb1e6c3be4873b4ae41e0d89904748fb5ba192d95d9ee3525612--aws-sam-cli-1.7.0.x86_64_linux.bottle.tar.gz
==> Pouring aws-sam-cli-1.7.0.x86_64_linux.bottle.tar.gz
  /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0: 4,092 files, 99MB
admin:~/environment $ sam --version
SAM CLI, version 1.7.0
```

### Expected result

sam cli should be upgraded successfully to the latest version

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Cloud9 (EC2 Amazon Linux instance)
2. `sam --version`: 1.6.2 

`Add --debug flag to command you are running`

**Comment by hawflau** [comment] 2020-11-03 23:38
Looks like the same problem as this [issue](https://github.com/aws/aws-sam-cli/issues/2320)

**Comment by hawflau** [comment] 2020-11-10 00:05
A workaround is to run `brew install aws-sam-cli` twice.
Closing as this is a duplicate of #2320

**Closed by hawflau** 2020-11-10 00:05 UTC
Labels: area/installation, stage/needs-investigation, type/bug
