### ISSUE TITLE
sam local start-api --log-file not write full message

### ISSUE THREAD

**Issue by ngovanviet90** [aws/aws-sam-cli#2142] opened 2020-07-29 07:05 UTC
Description
Hi AWS team!
I run sam local start-api with:

> Layer runtime custom [php](https://www.php.net) language, 

> Framework [Yii](https://www.yiiframework.com)

> Write log with library apache [log4php](https://logging.apache.org/log4php) 

Command line: sam local start-api --host 192.168.56.200 -l /tmp/sam.log
When i run sam local with log type console is OK.
But run with write log type file (--log-file) then has issue write log in requestId not full.
With message log >1000 byte then write log file is stop, sam not write log next step in request. Until the next request, the log of the previous request is added.

Example:
**First request:**
START RequestId: bf3889f5-3d5d-4cda-bde5-8bb04cca2aaa Version: $LATEST
log_step_1
log_step_222222222222222222222222222222222222222222222222222222222222222222.... (1000 character)
(sam stop write log...)

**Second request:**
log_step_3
REPORT RequestId: bf3889f5-3d5d-4cda-bde5-8bb04cca2aaa	Duration: 702.47 ms	Billed Duration: 800 ms	Memory Size: 128 MB	Max Memory Used: 64 MB	Init Duration: 199.83 ms	

START RequestId: cf6719f5-355d-4c2a-bde4-6bb01cc22ser Version: $LATEST
log_step_1
log_step_2
log_step_3
REPORT RequestId: cf6719f5-355d-4c2a-bde4-6bb01cc22ser	Duration: 701.42 ms	Billed Duration: 810 ms	Memory Size: 124 MB	Max Memory Used: 62 MB	Init Duration: 191.83 ms

**Comment by mgrandis** [comment] 2021-05-31 18:27
Are you still having the issue?
Just tested with the latest SAM CLI version and a Javacript project and I had no issue outputting a 2000 characters log message to the file. 
Could it be a limitation/configuration on the Yii or log4php side?
It seems the [documentation](https://www.yiiframework.com/doc/api/2.0/yii-log-dispatcher#setFlushInterval()-detail) is mentioning a 1000 value but more related to the number of messages to flush rather than their length.

**Comment by CoshUS** [comment] 2021-07-12 09:54
Closing as there is no new information and seems to be caused by other libraries.

**Closed by CoshUS** 2021-07-12 09:54 UTC
Labels: area/local/start-api, blocked/more-info-needed, stage/bug-repro, type/bug
