### ISSUE TITLE
Bug: Can't run sam validate or sam list endpoints when CORS is added to API Gateway with OpenAPI

### ISSUE THREAD

**Issue by andmoredev** [aws/aws-sam-cli#4661] opened 2023-02-04 17:56 UTC
### Description:
Get the following error whenever I run `sam validate` or `sam list endpoints` when I have a 'AWS::Serverless::Api' resource using the DefinitionBody from an OpenAPI (please see attached example of failing template + openapi)

Error: [InvalidResourceException('TaskServiceApi', "Unable to add Cors configuration because 'DefinitionBody' does not contain a valid Swagger definition.")] ('TaskServiceApi', "Unable to add Cors configuration because 'DefinitionBody' does not contain a valid Swagger definition.")

When I remove the CORS section of the API Gateway resource it works correctly.

### Steps to reproduce:
[test-service.zip](https://github.com/aws/aws-sam-cli/files/10609298/test-service.zip)
Run `sam validate` using the template+open api provided.

### Observed result:
| Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-02-04 11:53:18,319 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '9c829f2a-782e-4af1-acfa-9ae73045e952', 'installationId': '969a5535-7dbf-4555-aeeb-925db0311bae', 'sessionId': 'da39cb5a-2229-4d6e-85e6-b07e1614fd1a', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.72.0', 'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam list endpoints', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '665653223b1e8bfa2d462b3adb06d49f8984052e5df03d7fd2365293a102fce8', 'initialCommit': None}, 'duration': 3580, 'exitReason': 'InvalidSamTemplateException', 'exitCode': 1}}]}
2023-02-04 11:53:18,752 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: [InvalidResourceException('TaskServiceApi', "Unable to add Cors configuration because 'DefinitionBody' does not contain a valid Swagger definition.")] ('TaskServiceApi', "Unable to add Cors configuration because 'DefinitionBody' does not contain a valid Swagger definition.")

### Expected result:
Validation to work correctly

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 11
2. `sam --version`: 1.72.0
3. AWS region: us-east-1

```
{
  "version": "1.72.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.22621-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}

**Comment by jfuss** [comment] 2023-02-06 20:31
@andmoredev This is indented (to my understanding). The issue you are having is your OpenApi Spec is defined in another file. When you deploy, that file is put into S3 (by `sam package`) and deploy will fail with the same error. This is because the SAM Transform that runs in AWS will not have access to your OpenApi Spec. You either need to inline the OpenApi spec in the template or add the CORS to the OpenAPI directly yourself.

**Comment by jfuss** [comment] 2023-02-13 22:30
Closing. As described above this is intended behavior.

**Closed by jfuss** 2023-02-13 22:30 UTC

**Comment by Logan-Dang** [comment] 2025-04-10 06:21
> I don't quite understand why this is intended. I have used the same template and deploying there is no error but only in validate or list endpoints.

I would also like it if SAM could import the spec in these commands, but it could be costly to implement. At least it would be nice if SAM could show a message about using AWS::Include in DefinitionBody, or if the [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-definitionbody) could mention it, so there's less confusion about whether or not the openapi3 document is actually invalid.
