### ISSUE TITLE
Bug: ResourceDetailedStatus never returns as part of a cloudformation event

### ISSUE THREAD

**Issue by Shtutnik** [aws/aws-sam-cli#7378] opened 2024-08-19 15:14 UTC
### Description:
While looking at the code I noticed that `ResourceDetailedStatus` is checked in deployer.py (see for example [here](https://github.com/aws/aws-sam-cli/blob/89a29b806b73f2a583bd97dc9cfea8bee830e5c7/samcli/lib/deploy/deployer.py#L428))

From what I can tell, that key is never returned as part of a stack event, but rather there is `DetailedStatus` (see [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation/client/describe_stack_events.html))

**Comment by sidhujus** [comment] 2024-08-20 16:21
Hi @Shtutnik , thanks for finding this issue. I've confirmed that this is due to us using an older version of boto3 and once thats merged I will open a PR to use the correct event name

**Comment by Shtutnik** [comment] 2024-08-20 17:16
Oh right! My bad! I should have cross-checked with the requirements, I see it is referencing 1.29.2
👍

**Closed** 2024-09-11 23:24 UTC
Labels: type/bug, stage/waiting-for-release
