### ISSUE TITLE
[Sam Local start api] Error 500 on _X_AMZN_TRACE_ID missing since upgrading to 1.0

### ISSUE THREAD

**Issue by matdumsa** [aws/aws-sam-cli#2137] opened 2020-07-28 14:01 UTC
### Description

Since upgrading to Sam 1.0.0 my local start api command is failing each NodeJS lambda request that's using X-ray, this was not a problem before

### Steps to reproduce
running sam local start-api -p 3000 -t template.yaml -s packages/website/build

```javascript
const AWSXRay = require('aws-xray-sdk-core');
const aws = AWSXRay.captureAWS(require('aws-sdk'));
const s3 = new aws.S3();
```

### Observed result

 Expected _X_AMZN_TRACE_ID to be set.\n    at Object.contextMissingRuntimeError [as contextMissing] (/var/task/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)\n    at Segment.resolveLambdaTraceData (/var/task/node_modules/aws-xray-sdk-core/lib/env/aws_lambda.js:93:43)\n    at Object.getSegment (/var/task/node_modules/aws-xray-sdk-core/lib/context_utils.js:94:17)\n    at Object.resolveSegment (/var/task/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)\n    at features.constructor.captureAWSRequest [as customRequestHandler] (/var/task/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:66:29)\n    at features.constructor.addAllRequestListeners (/var/task/node_modules/aws-sdk/lib/service.js:283:12)\n    at features.constructor.makeRequest (/var/task/node_modules/aws-sdk/lib/service.js:203:10)\n    at features.constructor.svc.<computed> [as getObject] (/var/task/node_modules/aws-sdk/lib/service.js:677:23)

### Expected result

Works as in the past

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OS X Catalina 10.15.6 (19G73)
2. `sam --version`: 1.0.0

Could be mitigated by adding _X_AMZN_TRACE_ID: 1234 to my template.yaml  Api Env Var section

**Comment by matdumsa** [comment] 2021-02-04 15:55
Found a work around,

Add this to your YAML
```
Globals:
    Function:
        Environment:
            Variables:
                AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
                AWS_XRAY_LOG_LEVEL: silent
```

**Comment by jfuss** [comment] 2023-02-08 19:36
This looks like a duplicate of https://github.com/aws/aws-sam-cli/issues/217. I am going to close this in favor of that one.

**Closed by jfuss** 2023-02-08 19:36 UTC
Labels: type/bug, stage/needs-investigation, maintainer/need-response
