### ISSUE TITLE
Bug: MAC Installer incorrectly installs SAM - Symbol not found: _preadv

### ISSUE THREAD

**Issue by Kieran-Bacon** [aws/aws-sam-cli#4559] opened 2023-01-11 12:26 UTC
### Description:

After running the GUI all installer ([aws-sam-cli-macos-x86_64.pkg](https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-macos-x86_64.pkg)) for SAM as described [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html) leads to a broken state where the CLI cannot be called at all.

### Steps to reproduce:

1. Download installer
2. Verify installer
3. Run installer
4. Verify CLI running `sam --version`
5. Profit

### Observed result:

```
kieran@Kierans-MacBook-Pro ~ % sam --version
[11611] Error loading Python lib '/usr/local/aws-sam-cli/libpython3.8.dylib': dlopen: dlopen(/usr/local/aws-sam-cli/libpython3.8.dylib, 10): Symbol not found: _preadv
  Referenced from: /usr/local/aws-sam-cli/libpython3.8.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libSystem.B.dylib
```

### Expected result:

```
SAM CLI, version 1.66.0
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

OS: Mac - Catalina 10.15.7
AWS CLi: aws-cli/2.9.8 Python/3.9.11 Darwin/19.6.0 exe/x86_64 prompt/off
Region: eu-west-1

**Comment by hnnasit** [comment] 2023-01-11 16:28
Hi, thanks for reporting this issue, we will be investigating it further. Could you check if running this command `/usr/local/bin/sam --version` works?

**Comment by turar** [comment] 2023-01-19 18:44
@hnnasit I have the same issue and `/usr/local/bin/sam --version` results in the same error

**Comment by Kieran-Bacon** [comment] 2023-01-19 20:29
Sorry for taking so long to respond - yes I get the same result

```bash
kieran@Kierans-MacBook-Pro ~ % /usr/local/bin/sam --version
[25125] Error loading Python lib '/usr/local/aws-sam-cli/libpython3.8.dylib': dlopen: dlopen(/usr/local/aws-sam-cli/libpython3.8.dylib, 10): Symbol not found: _preadv
  Referenced from: /usr/local/aws-sam-cli/libpython3.8.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by shubha26** [comment] 2023-02-14 14:15
Is this issue resolved? I still get the same error on MAC Catalina

MacBook-Air:Downloads shubh$ /usr/local/bin/sam --version
[9509] Error loading Python lib '/usr/local/aws-sam-cli/libpython3.8.dylib': dlopen: dlopen(/usr/local/aws-sam-cli/libpython3.8.dylib, 10): Symbol not found: _preadv
  Referenced from: /usr/local/aws-sam-cli/libpython3.8.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by workprodukt-stephon** [comment] 2023-02-16 20:20
I am also stuck on this issue.  Has there been a resolution?

**Comment by rmackovic** [comment] 2023-02-26 17:06
I have encountered the same problem and resolved it by installing SAM CLI via Homebrew instead of using provided installer pkg which is not compatible with Catalina.
Just ensure that you delete the previously created symlink with 

`rm '/usr/local/bin/sam'`

after that run

`brew install aws/tap/aws-sam-cli`

and it should do the job

**Comment by super132** [comment] 2023-03-17 17:51
We confirmed that the installer binary that we produce supports MacOS 11.0.1 and above. For customers would have an older version of MacOS than 11.0.1, we suggest to install SAM CLI through `brew`. We will update the documentation to reflect the limitation. Thanks.

**Closed** 2023-03-17 23:57 UTC
Labels: stage/needs-investigation, pyinstaller/mac/x86

**Comment by dvbarnz** [comment] 2024-01-26 08:37
If you already have pip (Python package installer) then `pip install aws-sam-cli`  works in a few minutes.  On my Macbook I gave up with the brew install after it had been running for 4 hours - it had got to compiling LLVM so still had a long way to go.

**Comment by toondeboer** [comment] 2025-01-11 11:44
> If you already have pip (Python package installer) then `pip install aws-sam-cli` works in a few minutes. On my Macbook I gave up with the brew install after it had been running for 4 hours - it had got to compiling LLVM so still had a long way to go.

Thanks a lot, this works for me too! I am using a macbook 2016 running Monterey 12.7.6. As this MacOS version is not supported anymore by Apple and brew (They only support the latest 3 MacOS versions), I suggest to not use brew anymore. Installing with python and pip worked perfectly for me! 😄

**Comment by rodrigobb** [comment] 2025-01-14 09:13
> If you already have pip (Python package installer) then `pip install aws-sam-cli` works in a few minutes. On my Macbook I gave up with the brew install after it had been running for 4 hours - it had got to compiling LLVM so still had a long way to go.

This works for me too! But using `pip3`. I am using a macbook 2015 running Monterey 12.7.6, don't have `brew` installed.
I had to use `sudo pip3 install aws-sam-cli`
