### ISSUE TITLE
Unable to "sam local start-api" of any CloudFormation templates after upgrading to 1.22.0

### ISSUE THREAD

**Issue by jankammerath** [aws/aws-sam-cli#2825] opened 2021-04-22 17:19 UTC
### Description:
Previously used 1.15.0 to launch my CloudFormation template with an API Gateway defined. After upgrading to 1.22.0, I get an error message stating: "The resource AWS::Lambda::Function 'ApiLambdaFunction' has specified S3 location for Code. It will not be built and SAM CLI does not support invoking it locally."

I launch the SAM CLI with:
sam local start-api --profile frontendtest --region eu-central-1 --port 8081 --host 192.168.1.132

### Steps to reproduce:
Upgrade to 1.22.0 and launch SAM CLI with CF template containing an API gateway

### Observed result:
Application crashes:

```
$ sam local start-api --profile frontendtest --region eu-central-1 --port 8081 --host 192.168.1.132
The resource AWS::Lambda::Function 'ApiLambdaFunction' has specified S3 location for Code. It will not be built and SAM CLI does not support invoking it locally.

Mounting None at http://192.168.1.132:8081/ [GET, POST]

Mounting None at http://192.168.1.132:8081/{proxy+} [GET, POST]

You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template

2021-04-22 19:17:15  * Running on http://192.168.1.132:8081/ (Press CTRL+C to quit)

Exception on / [GET]

Traceback (most recent call last):

  File "/usr/local/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()

  File "/usr/local/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)

  File "/usr/local/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)

  File "/usr/local/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value

  File "/usr/local/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()

  File "/usr/local/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)

  File "/usr/local/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 317, in _request_handler

    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/usr/local/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 101, in invoke
    function = self.provider.get(function_identifier)

  File "/usr/local/Cellar/aws-sam-cli/1.22.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 73, in get
    raise ValueError("Function name is required")

ValueError: Function name is required

2021-04-22 19:17:17 192.168.1.132 - - [22/Apr/2021 19:17:17] "GET / HTTP/1.1" 502 -
```

### Expected result:
Behaviour as in 1.15.0, SAM invokes local application file with the configuration from the template.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS Big Sur 11.2.3
2. `sam --version`: 1.22.0
3. AWS region: eu-central-1

**Comment by aahung** [comment] 2021-04-22 17:27
Looks like your `ApiLambdaFunction` has a CodeUri (or `Code`) pointing to a S3 location, where `sam local` does not support at this time. Is it intended to point to a S3 location or something wrong resulting in it?

**Comment by jankammerath** [comment] 2021-04-22 17:55
> Looks like your `ApiLambdaFunction` has a CodeUri (or `Code`) pointing to a S3 location, where `sam local` does not support at this time. Is it intended to point to a S3 location or something wrong resulting in it?

aws-sam-cli 1.15.0 did support it and it is only broken since I upgraded to 1.22.0 a few minutes ago. I just broke by only upgrading to 1.22.0 and worked perfectly with 1.15.0. Is there any guidance on how to downgrade to 1.15.0?

**Comment by aahung** [comment] 2021-04-22 18:11
@jakemayeux #2802 is about CDK are you using CDK?

> aws-sam-cli 1.15.0 did support it and it is only broken since I upgraded to 1.22.0 a few minutes ago. It just broke by upgrading to 1.22.0 and worked perfectly with 1.15.0. Is there any guidance on how to downgrade to 1.15.0?

depending on how you installed it, if it is using brew, [maybe this helps](https://stackoverflow.com/questions/39187812/homebrew-how-to-install-older-versions)

It will be great if you can also upload the log running `sam local start-api` in 1.15.0 and make a request to `http://192.168.1.132:8081/`. It will help us to understand what is going on. Thanks!

**Comment by aahung** [comment] 2021-04-22 18:16
Besides, you mentioned that

> I need to create a dedicated SAM template in addition to my CF templates

can you provide some details about how your template looks like? including:
- template anatomy including details of the "ApiLambdaFunction" and the function you want to invoke (if it is different from ApiLambdaFunction)
- if you have nested template, include them as well

**Comment by jankammerath** [comment] 2021-04-22 18:20
> @jakemayeux #2802 is about CDK are you using CDK?

No, I am only using aws-sam-cli.

> > aws-sam-cli 1.15.0 did support it and it is only broken since I upgraded to 1.22.0 a few minutes ago. It just broke by upgrading to 1.22.0 and worked perfectly with 1.15.0. Is there any guidance on how to downgrade to 1.15.0?
> 
> depending on how you installed it, if it is using brew, [maybe this helps](https://stackoverflow.com/questions/39187812/homebrew-how-to-install-older-versions)

That would take me approx. a week to install which I don't have at the moment. The breaking changes in 1.22.0 completely caught me off guard and I need to rework my entire development workflow now.

> It will be great if you can also upload the log running `sam local start-api` in 1.15.0 and make a request to `http://192.168.1.132:8081/`. It will help us to understand what is going on. Thanks!

Unfortunately impossible as I cannot downgrade and aws/tap does not include previous versions for aws-sam-cli, so any user upgrading to a version that breaks his or her workflow can't downgrade.


> Besides, you mentioned that
> 
> > I need to create a dedicated SAM template in addition to my CF templates
> 
> can you provide some details about how your template looks like? including:
> 
>     * template anatomy including details of the "ApiLambdaFunction" and the function you want to invoke (if it is different from ApiLambdaFunction)

It is an extremely simple template with just a single Lambda function:

```
    ApiLambdaFunction:
        DependsOn:
        - ApiLambdaRole
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: !Ref LambdaFunctionName
            Handler: 'app.lambdaHandler'
            Role: !GetAtt ApiLambdaRole.Arn
            Runtime: 'nodejs12.x'
            MemorySize: 1536
            Timeout: 90
            Code:
                S3Bucket: !Ref LambdaCodeBucket
                S3Key: 'lambda-code.zip'
            TracingConfig:
                Mode: 'Active'

    RestApiMainResource:
        Type: AWS::ApiGateway::Resource
        Properties:
            ParentId: !GetAtt RestApi.RootResourceId
            PathPart: '{proxy+}'
            RestApiId: !Ref RestApi

    RestApiRootPOSTMethod:
        Type: AWS::ApiGateway::Method
        DependsOn:
        - LambdaInvokePermission
        Properties:
            AuthorizationType: NONE
            HttpMethod: POST
            ResourceId: !GetAtt RestApi.RootResourceId
            RestApiId: !Ref RestApi
            Integration:
                IntegrationHttpMethod: POST
                Type: AWS_PROXY
                Uri: !Sub
                    - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiLambdaFunctionArn}/invocations"
                    - ApiLambdaFunctionArn: !GetAtt ApiLambdaFunction.Arn
```

>     * if you have nested template, include them as well

I do not have any nested templates.

**Comment by aahung** [comment] 2021-04-22 18:27
Thanks for the info, one more piece of info needed:
can you also share what is your project directory like? does it (the project root) contains `package.json` and `app.js`?

**Comment by jankammerath** [comment] 2021-04-22 19:58
> Thanks for the info, one more piece of info needed:
> can you also share what is your project directory like? does it (the project root) contains `package.json` and `app.js`?

this is my directory structure:
app.js
template.yaml

this is my app.js:
```

exports.lambdaHandler = async (event, context) => {
    return await BlaBlaClass.execute(event);
}
```

**Comment by jankammerath** [comment] 2021-04-23 08:32
As a workaround for anyone affected by the breaking change that prevents from loading deployment-ready CF templates with AWS SAM CLI since version 1.22.0, you'd have to build a SAM template with an 'AWS::Serverless::Function' that exactly represents your CF template's 'AWS::Lambda::Function'. It is painful, but at least after 3 hours I managed to get back into development. 

This workflow is a significant disadvantage over v1.15.0 which was easily able to just load API Gateway specs with Lambda functions from the CF template and local code files by omitting the Bucket specs for the code file and just use the contents from ".". I have not figured out where exactly this change was introduced, but it should've come with a warning label as it practically broke numerous workflows/use-cases. 

Anyone using "aws-sam-cli" for development only (no build or deployment) and do the deployment with CF templates or stack sets, will now have to build a SAM template purely for development as well which is pretty much only a duplicate of the CF template in some form.

```
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
        Handler: app.lambdaHandler
        Runtime: nodejs12.x
        MemorySize: 1536
        Timeout: 90
        Policies: 
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogGroup'
                    - 'logs:CreateLogStream'
                    - 'logs:PutLogEvents'
                  Resource: 'arn:aws:logs:*:*:*'
                - Effect: Allow
                  Action:
                    - 'xray:PutTraceSegments'
                    - 'xray:PutTelemetryRecords'
                  Resource: '*'
        Tracing: 'Active'
        Events:
            HttpPost:
                Type: Api
                Properties:
                    Path: '/{proxy+}'
                    Method: get
        Environment:
            Variables:
                CANNOT_POST_MY_PARAMS_ON_GITHUB: "no, you can't post them"
                AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
                _X_AMZN_TRACE_ID: 0
                DISABLE_XRAY_TRACING: 1
```

Again, I think the change to not allow using CF templates with local files should've come with a warning flag to prevent users from upgrading that used this workflow. I would have loved to figure out the changes and commits for it, but I am very sorry as my time does not allow this at the moment.

**Comment by aahung** [comment] 2021-04-23 08:51
> > Thanks for the info, one more piece of info needed:
> > can you also share what is your project directory like? does it (the project root) contains `package.json` and `app.js`?
> 
> this is my directory structure:
> app.js
> template.yaml
> 
> this is my app.js:
> 
> ```
> 
> exports.lambdaHandler = async (event, context) => {
>     return await BlaBlaClass.execute(event);
> }
> ```

I am a bit confused about your workflow:

Normally, when you have your function code locally (in this case, it is `.`), your template should look like this (the key is `CodeUri: .`:
```yaml
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
        Handler: app.lambdaHandler
        Runtime: nodejs12.x
        MemorySize: 1536
        CodeUri: .
        Timeout: 90
        Policies: 
        - PolicyName: root
        - ...
```

Then you should be able to do `sam local *` and when you need to deploy, run `sam deploy`.

But it looks like you have a different workflow where you deploy your lambda code yourself to S3 bucket and use S3 location as `CodeUri`.

In 1.15.0, `sam local` worked for you case not by design but rather a coincident, where 1.15.0 used `.` as `CodeUri` by default if it couldn't resolve the `CodeUri` path. And in your case, your `app.js` happens to be located in `.` so `sam local` managed to pick up your function. This behavior was implicit so we removed it.

**Comment by jankammerath** [comment] 2021-04-23 09:31
> In 1.15.0, `sam local` worked for you case not by design but rather a coincident, where 1.15.0 used `.` as `Code` by default if it couldn't resolve the `Code` path. And in your case, your `app.js` happens to be located in `.` so `sam local` managed to pick up your function. This behavior was implicit so we removed it.

Thank you for your information. Shall I open a feature request to reintroduce this behaviour?

> I hope above explains what is going on with your use case. And as for solution, `sam local` is not designed to take in "deployment-ready" CFN template. For your use case, I have a few options:

It however worked like a charm in 1.15 and I really did like it. It played absolutely wonderful with my BitBucket pipeline.

>  1. SAM CLI is designed to take care of the entire build, local invokes, package and deploy workflow. You don't need to prepare a "deployment-ready" template yourself. Use `.` as the `Code` property and deploy using `sam deploy` command. (you don't seem to have a `package.json` so you can skip the `sam build`.

I tried SAM CLI deployment and build, but was not satisfied with it and unable to safely integrate it into my pipeline. This is personal taste and the nature of my applications and not a general statement, but my personal opinion that does not resemble any judgement of the deployment or functionality of the SAM CLI.

>  2. (not recommended) prepare a separate template file that set `Code: .`. Then you can start api with `sam local start-api -t alternative_template_name.yaml`

This is what I am doing at the moment and unless the functionality of SAM CLI to run CFN templates is restored, I'll continue doing so as SAM templates do not provide the necessary functionality I need to run my pipeline. This "new workflow" for me also comes along tons of X-Ray error log outputs and some other side-effects I did not have in 1.15. However I do not want to spam with tickets here, so I'll keep it to myself.

**Comment by jankammerath** [comment] 2021-04-23 11:31
> But it looks like you have a different workflow where you deploy your lambda code yourself to S3 bucket and use S3 location as `CodeUri`.

Just for the sake of the clarification of my workflow:

- I write my JavaScript and CFN YAML code locally, test and debug it with the SAM CLI
- I commit and push my changes to my BitBucket repository
- The repository's BitBucket pipeline executes the CFN YAML when it was changed
- The BitBucket pipeline zips and pushes my code from the master to the S3 bucket
- The BitBucket pipeline updates the Lambda function with the code from the master branch
- My application is deployed and lives it's cloudy life happily

**Comment by awood45** [comment] 2021-04-29 20:45
I definitely understand the frustration of the change in behavior - the intention was to provide a more helpful error message when someone was using S3 sources in their serverless functions, since for most applications the root folder would not be executable directly.

Is the idea that you want to test the code that has been uploaded to S3 locally, or that you want to test local changes on your machine?

**Comment by jankammerath** [comment] 2021-04-30 11:01
> I definitely understand the frustration of the change in behavior - the intention was to provide a more helpful error message when someone was using S3 sources in their serverless functions, since for most applications the root folder would not be executable directly.

Sorry, if some sort of frustration did come across which was certainly not my intention. I was more upset with myself that I assumed my workflow as being a regular workflow and SAM intended to launch CFN templates.

> Is the idea that you want to test the code that has been uploaded to S3 locally, or that you want to test local changes on your machine?

I am testing local changes on my machine before uploading them to S3 and updating the lambda function.

**Comment by awood45** [comment] 2021-05-04 20:36
No worries at all, it was a genuine understanding that we made a breaking change to your workflow - that approach wasn't intended behavior, but it broke nonetheless.

What we would tend to recommend is to use the `CodeUri` resource to point to a folder on your machine. If you do that, you can `sam build` your changes, use `sam local` to test those changes, and use `sam package` and or `sam deploy` and SAM CLI will handle S3 updates for you. This is the general recommended workflow. This [tutorial](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html) walks through that recommended flow for an example app.

Closing, feel free to reopen if you have any other questions or issues getting your workflow set up.

**Closed by awood45** 2021-05-04 20:36 UTC
Labels: area/local/start-api
