### ISSUE TITLE
sam init --location support tag/branch

### ISSUE THREAD

**Issue by cfbarbero** [aws/aws-sam-cli#1326] opened 2019-08-08 19:26 UTC
### Describe your idea/feature/enhancement

I wish that sam cli supported initing from a git url with a specific tag/branch.

### Proposal

I see 2 options for implementing this:
1. Add a new parameter to the `sam init` command to be used alongside the `--location` parameter for controlling branch/tag.
  `--location git@bitbucket.org:someaccount/sometemplate-repo.git --ref v1.0`
2. Support specifying `ref` as part of the location url itself. 
  `--location git@bitbucket.org:someaccount/sometemplate-repo.git?ref=v1.0`  

The underlying templating tool ([cookiecutter](https://cookiecutter.readthedocs.io/en/latest/usage.html#works-directly-with-git-and-hg-mercurial-repos-too)) supports branches/tags through a --checkout flag.
```
cookiecutter git@bitbucket.org:someaccount/sometemplate-repo.git --checkout v1.0
```

SAM CLI would need to be updated to pass the `ref` value on to cookiecutter as the `checkout` parameter.

**Comment by jfuss** [comment] 2022-12-20 21:38
Closing as duplicate of https://github.com/aws/aws-sam-cli/issues/3555

**Closed by jfuss** 2022-12-20 21:38 UTC
Labels: priority/4-nice-to-have, type/feature, area/init, stage/pm-review, maintainer/need-response
