### ISSUE TITLE
Native support for Terraform in SAM CLI (now in Beta)

### ISSUE THREAD

**Issue by praneetap** [aws/aws-sam-cli#3154] opened 2021-08-10 18:52 UTC
### Terraform Support
Recently we added native support for CDK applications in the SAM CLI - you can see our [launch announcement](https://aws.amazon.com/blogs/compute/better-together-aws-sam-and-aws-cdk/) blog post and download the beta version of the CLI.

We would like to collect the community’s feedback on whether we should add **native support for Terraform** in the SAM CLI. Terraform users would be able to use the SAM CLI’s `build`, `package`, `local invoke`, and `start-api` commands. The `build` and `package` commands make it easy to create deployment packages or OCI images that are ready to be used in AWS Lambda. The `local invoke` and `start-api` commands makes it easy to emulate AWS Lambda and API Gateway in local Docker container for testing purposes.

With this change, the SAM CLI would parse HCL definitions to understand functions and APIs that can be locally tested and built. The SAM CLI would not write HCL, translate to, or force the use of CloudFormation. Deployments should still be performed using the Terraform toolkit.

*What feedback are we looking for?*

1. Is this something the community is interested in? _**Vote with 👍🏽 **._
2. The sam `build`, `package`, and `local invoke` commands rely on the `CodeUri` property of a function resource pointing to a local path where the source code for the Lambda function is stored. The SAM CLI automatically pulls dependencies, compiles if necessary, and prepares a deployment package for AWS Lambda. The package command today produces an output template that contains the S3 URL for the deployment package the SAM CLI prepared. _**How would you like this work with Terraform?**_

**Comment by antonbabenko** [comment] 2021-08-12 12:55
@Vlaaaaaaad I like the idea of bringing an alternative approach to the `package.py` with the main goal to make the module independent from Python and cross-platform right away.

(When we were making the [terraform-aws-lambda module](https://github.com/terraform-aws-modules/terraform-aws-lambda) module, `sam build` was far from feature-rich. Since there is support for running Lambda functions from a container image, I recommend using that instead of relying on `package.py` which is not perfect. See [container-image example](https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/master/examples/container-image).)

Terraform has its own resource lifecycle management which is carefully implemented as a part of the [terraform-aws-lambda module](https://github.com/terraform-aws-modules/terraform-aws-lambda). For example, rebuild the package and redeploy it _only_ if something in dependencies changed. This does not sound like an easy task for me to even describe how Terraform & SAM should _share the lifecycle management_ since resources can be cross-linked between SAM template and Terraform code.

As a developer, I like to have a tool that does comprehensive infrastructure management and serverless application deployments. `terraform apply` is it.

Yes, there is more to be done to improve the developer experience but it is not related to SAM CLI or this issue.

**Comment by Vlaaaaaaad** [comment] 2021-08-12 18:47
> Terraform has its own resource lifecycle management which is carefully implemented as a part of the terraform-aws-lambda module. For example, rebuild the package and redeploy it only if something in dependencies changed. This does not sound like an easy task for me to even describe how Terraform & SAM should share the lifecycle management since resources can be cross-linked between SAM template and Terraform code.

Good point! 
I was imagining `sam build` generating some kind of hashed artifact that can safely be used by Terraform. Having unnecessary deploys because of packaging would definitely ruin the dev experience. @praneetap any chance this would be an option?

**Comment by praneetap** [comment] 2021-08-16 16:42
@Vlaaaaaaad @antonbabenko Thank you for the feedback - this is helpful. To help us prioritize and make the integration decision, do you know how many Lambda users rely on the terraform-aws-lambda module? Could we get their +1s here if you are connected to the community?

**Comment by antonbabenko** [comment] 2021-08-16 18:35
@praneetap Let me share some statistics for the [terraform-aws-lambda module](https://github.com/terraform-aws-modules/terraform-aws-lambda).
1. [Terraform Registry page](https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest) says `Total provisions: 1.2M`. This is more than all other Lambda modules published in the Registry combined.
2. GitHub insights for the repo says: `115,928 Clones`, `32,847 Unique cloners` during the last 14 days.
3. Also, there are users who use private forks of the module or don't use Terraform Registry (e.g., using `terragrunt`).

I will share this issue with the community if anyone wants to upvote it.

**Comment by debragail** [comment] 2021-09-10 00:39
The only issue is that my projects use GraphQL, so `sam local start-api` isn't as helpful since i'm using AppSync and in some cases the serverless framework which hosts its own Apollo server.

**Comment by praneetap** [comment] 2021-09-14 17:33
@debragail thanks for your input! We just published our [open roadmap](https://github.com/aws/aws-sam-cli/wiki/SAM-CLI-Roadmap) that proposes to address your issue in a couple ways - [Cloud based development](https://github.com/aws/aws-sam-cli/issues/3264) or [building emulator plugins](https://github.com/aws/aws-sam-cli/issues/3265). Take a look and upvote the one that would work well for you.

**Comment by moelasmar** [comment] 2022-08-16 00:16
Hello All, 

I am trying to collect some data to know if the following pattern (defining multiple lambda functions and lambda layers using the count property, and t set the function.layers property to the corresponding layer using count.index) is commonly used pattern or not :
```
resource "aws_lambda_layer_version" "layer" {
  count = 2
  filename   = var.layers_source_code[count.index]
  ....
}

resource "aws_lambda_function" "get_country_languages" {
    count = 2
    filename = var.functions_source_code[count.index]
    ...
    layers = [aws_lambda_layer_version.layer[count.index].arn]
}
```

Also, if the following pattern (use conditional expression to set the Lambda function layers property)

```
resource "aws_lambda_function" "get_country_languages" {
    count = 2
    filename = var.functions_source_code[count.index]
    ...
    layers = var.env == "prod" ? [aws_lambda_layer_version.prod_layer.arn] : [aws_lambda_layer_version.beta_layer.arn]
}
```
I appreciate if you can share with us form your experience with using terraform if you used any of these patterns in any of your terraform projects.

**Comment by antonbabenko** [comment] 2022-08-16 09:47
@moelasmar Here are my 5 cents into this.

1. Using `count` is less flexible for cases where an order is not critical, so users should prefer to use `for_each` instead.
2. Using conditional expressions to set Lambda layers property is possible but I don't think many users would do it this way. An alternative solution would be to use `try()` like this - `layers = try([aws_lambda_layer_version.prod_layer.arn], [aws_lambda_layer_version.beta_layer.arn], [])`

"commonly used pattern" is a rather tricky thing to ask because if it is valid syntax, there are users who write it like this, and any tool/solution should support it.

**Comment by lorengordon** [comment] 2022-11-15 17:22
Looks like some portion of this has landed?

* https://aws.amazon.com/blogs/compute/better-together-aws-sam-cli-and-hashicorp-terraform/
* https://github.com/aws/aws-sam-cli/releases/tag/v1.63.0
* https://github.com/aws/aws-sam-cli/pull/4373
* https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/325

**Comment by praneetap** [comment] 2022-11-15 18:35
Hello!
SUPER excited to announce that our first step towards the full support - the ability to locally test and debug Lambda functions with SAM CLI, is now available in Beta. For the best experience, use it with [terraform-aws-modules](https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest#sam_cli_integration) maintained by @antonbabenko , but you can also use it with custom modules as [described in this blogpost](https://aws.amazon.com/blogs/compute/better-together-aws-sam-cli-and-hashicorp-terraform/). More details in the [what's new post here](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-sam-cli-terraform-support-lambda-local-testing-debugging/).

How can you help? As you can see, this is a preview of just the Lambda function testing, and we want to build on this based on your feedback and feature requests. You can give us feedback by- 
1. [Creating an issue](https://github.com/aws/aws-sam-cli/issues/new?labels=area%2Fterraform) to track a request
2. Connect with us on [AWS developer Slack #samdev channel](https://join.slack.com/t/awsdevelopers/shared_invite/zt-yryddays-C9fkWrmguDv0h2EEDzCqvw)

Thanks in advance!

**Comment by lorengordon** [comment] 2022-11-15 21:05
Is there an example somewhere of using this support with [terraform-aws-modules project](https://github.com/terraform-aws-modules/terraform-aws-lambda#sam_cli_integration)? I checked the docs there, and the examples directory, and also the [aws-samples](https://github.com/aws-samples/aws-sam-terraform-examples) repo, but didn't see anything...

**Comment by moelasmar** [comment] 2022-11-18 20:22
Hello @lorengordon .. please check this example https://github.com/aws-samples/aws-sam-terraform-examples/tree/main/serverless_tf_sample/api-lambda-dynamodb-example

**Comment by lorengordon** [comment] 2022-11-18 20:32
@moelasmar Thanks!

**Comment by philipws** [comment] 2022-11-21 12:26
I am having the same issue of:

```
Running Prepare Hook to prepare the current application
Executing prepare hook of hook "terraform"
Error: Import error - HookFunctionality module "samcli.hook_packages.terraform.main"
```

I am running in a container from Ubuntu 22.04 and installed sam cli via

```
# INSTALL | SAM CLI
RUN wget -O /tmp/samcli.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
RUN unzip /tmp/samcli.zip -d /tmp/sam-installation
RUN /tmp/sam-installation/install
RUN rm /tmp/samcli.zip && rm -rf /tmp/sam-installation
```

```
➜  api-lambda-dynamodb-example git:(main) ✗ sam --version
SAM CLI, version 1.65.0
```

**Comment by philipws** [comment] 2022-11-21 12:28
I am having the same issue of:

```
Running Prepare Hook to prepare the current application
Executing prepare hook of hook "terraform"
Error: Import error - HookFunctionality module "samcli.hook_packages.terraform.main"
```

I am running in a container from Ubuntu 22.04 and installed sam cli via

```
# INSTALL | SAM CLI
RUN wget -O /tmp/samcli.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
RUN unzip /tmp/samcli.zip -d /tmp/sam-installation
RUN /tmp/sam-installation/install
RUN rm /tmp/samcli.zip && rm -rf /tmp/sam-installation
```

```
➜  api-lambda-dynamodb-example git:(main) ✗ sam --version
SAM CLI, version 1.65.0
```

**Comment by tam116** [comment] 2022-11-21 16:20
> @tam116 .. could you please let us know how did you install SAM CLI, and what is your OS?

OS is Ubuntu 22.04 running under WSL2

SAM install was done using the Linux instructions here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html#install-sam-cli-instructions

**Comment by moelasmar** [comment] 2022-11-21 19:32
thanks @philipws, and @tam116 for raising this issue. I can reproduce it, and we are working on a fix for it.

**Comment by moelasmar** [comment] 2022-11-22 18:48
@philipws, and @tam116 I created this issue https://github.com/aws/aws-sam-cli/issues/4432 to track this problem.

**Comment by moelasmar** [comment] 2022-11-23 00:03
@tam116, @philipws  .. This issue is fixed in [this sam nightly release](https://github.com/aws/aws-sam-cli/releases/sam-cli-nightly/). As a workaround for now, please follow these [instructions](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/manage-sam-cli-versions.html#manage-sam-cli-versions-nightly-build) to install the sam nightly version. We will update [this issue](https://github.com/aws/aws-sam-cli/issues/4432) once we release this fix.

**Comment by tam116** [comment] 2022-11-23 17:32
@moelasmar The nightly build is working for me

**Comment by tam116** [comment] 2022-11-23 19:40
I've made a couple of feature requests, #4439 and #4440

**Comment by moelasmar** [comment] 2022-11-23 22:38
Thanks @tam116 for raising these requests. I replied to them and suggested some workarounds that you can try for now till we prioritized them and add a native SAM CLI support for them.

**Comment by super132** [comment] 2022-11-29 21:31
Just an update to this thread, for people who are working on Linux, [SAM CLI v1.66.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.66.0) should fix the problem of not able to run terraform support feature. Please give it a try and let us know your feedback about the feature. Thanks.

**Comment by JGynther** [comment] 2023-01-05 01:55
Current support for `sam local invoke` and `sam local start-lambda` is proving very helpful for debugging individual functions. However support for `sam local start-api` would make local testing of a whole application way simpler. Any updates on how far in the roadmap is support for start-api?

**Comment by adilnaimi** [comment] 2023-01-05 21:00
I prefer to use [terraform-aws-lambda module](https://github.com/terraform-aws-modules/terraform-aws-lambda) module to provision my lambda and related infra ressouces, and only use SAM to deploy the application. This seems impossible with the current way sam works because it needs to use my previously created lambda but instead wants to create a new one.

**Comment by super132** [comment] 2023-01-09 19:37
Thanks for the feedback. I created a [discussion thread](https://github.com/aws/aws-sam-cli/discussions/4553) to better capture the beta feedbacks at the mean time. Please feel free to discussion in the new discussion thread :) Happy testing!

**Comment by jfuss** [comment] 2023-02-10 02:07
Closing as this was moved to Discussion (see above comment).

**Closed by jfuss** 2023-02-10 02:07 UTC
Labels: stage/needs-feedback, area/terraform

**Comment by moelasmar** [comment] 2023-08-02 22:15
We release the Terraform support in `sam local start-api` for V1 API Gateway resources in [release V1.90.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.90.0). Now you can test your V1 API Gateway services that integrate to lambda functions locally. Please let us know if you have any feedback. Please refer to [this Docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/terraform-support.html) to get more info regarding SAM CLI and Terraform integrations.

**Comment by praneetap** [comment] 2023-09-06 04:59
Terraform support in SAM CLI tool is GA now ([announcement](https://aws.amazon.com/about-aws/whats-new/2023/09/aws-sam-cli-local-testing-debugging-terraform-projects/)) in [release 1.97.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.97.0).
Please refer to [this blogpost](https://aws.amazon.com/blogs/compute/aws-sam-support-for-hashicorp-terraform-now-generally-available/) to know what is supported in the new SAM CLI release, and also refer to [this docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/terraform-support.html) to get more info regarding the SAM CLI and Terraform integrations.
