### ISSUE TITLE
Remove dependency on requirements.txt

### ISSUE THREAD

**Issue by csy08** [aws/aws-sam-cli#2333] opened 2020-10-28 14:41 UTC
When i run sam build, it requires me to have a requirements.txt file or it crashes (python obviously).  On some projects, I only use native python libraries like urllib and json, and therefore dont require any external dependencies (except boto3), which requires me to have an empty requirements.txt file.

### Proposal

Remove the dependency and have it check if the file exists.

### Additional Details

% sam build --use-container
Starting Build inside a container
Building function 'HttpApiFunction'

Fetching amazon/aws-sam-cli-build-image-python3.7 Docker container image..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Mounting /Users/csy08/Documents/Development/projects/cec-prisma-cag-middleware/src as /tmp/samcli/source:ro,delegated inside runtime container

Build Failed
Running PythonPipBuilder:ResolveDependencies
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt

**Comment by hawflau** [comment] 2020-11-10 00:01
Closing as this is a duplicate of #784

**Closed by hawflau** 2020-11-10 00:01 UTC
Labels: area/build
