### ISSUE TITLE
Can’t brew install aws-sam-cli-beta-cdk  on MacOS Monterey 12.2.1 with M1 chip

### ISSUE THREAD

**Issue by EvgeniyTT** [aws/aws-sam-cli#3799] opened 2022-04-05 10:32 UTC
### Description:
Getting a build failure when trying to `brew install aws-sam-cli-beta-cdk` on MacOS Monterey 12.2.1 with M1 chip.
Might be connected with https://github.com/aws/aws-sam-cli/issues/3769

### Steps to reproduce:

`brew install aws-sam-cli-beta-cdk`

### Observed result:
```
==> /opt/homebrew/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/bin/pip install -v --pre --ignore-installed /private/tmp/aws-sam-cli-beta-cdk-20220405-88225-1dny44
Last 15 lines from /Users/Yevhen_Tataryn/Library/Logs/Homebrew/aws-sam-cli-beta-cdk/03.pip:
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/homebrew/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/bin/python3.8 /opt/homebrew/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /private/tmp/tmp5rdrx9ao
  cwd: /private/tmp/pip-install-pvdphkl9/pyyaml_614b66ed23c044dfa8294416c447cbb1
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/aws/homebrew-tap/issues
```

### Expected result:
The package is installed without errors

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
`brew install aws-sam-cli-beta-cdk  -v` - [aws-sam-cli-beta-cdk_install.txt](https://github.com/aws/aws-sam-cli/files/8417236/aws-sam-cli-beta-cdk_install.txt)
`brew install aws-sam-cli-beta-cdk  -v --build-from-source` - [aws-sam-cli-beta-cdk_install_source.txt](https://github.com/aws/aws-sam-cli/files/8417237/aws-sam-cli-beta-cdk_install_source.txt)

**Comment by qingchm** [comment] 2022-04-05 21:01
Hi there thanks for reporting! We are aware of this issue now and is most likely an regression from cython for their version 3.0.0a10. I will try to resolve this by providing the same resolution (removing the --pre flag) to beta-cdk as we did for the nightly and please let me know if it works for you guys! For long term we will look to ping down cython version to avoid such regressions as well. Thanks again for reporting this issues! @danorton @EvgeniyTT

**Comment by qingchm** [comment] 2022-04-05 21:26
@EvgeniyTT @danorton Now this installation issue should be fixed and feel free to test that out later with our next build! Just FYI, CDK is now GA in aws-sam-cli and any feature supported in the beta releases are already in aws-sam-cli so this might also be a good time to switch to aws-sam-cli (all future CDK support improvements will be in this as well, generally beta-cdk is not needed anymore ;) Let us know if you have any concerns!

**Comment by EvgeniyTT** [comment] 2022-04-08 11:43
@qingchm Thank you, now it works fine!

**Comment by danorton** [comment] 2022-04-08 16:55
Works for me

**Comment by qingchm** [comment] 2022-04-08 17:21
Glad to hear that! Thanks for understanding and reaching out to us! Now closing the ticket for you!

**Closed by qingchm** 2022-04-08 17:21 UTC
Labels: area/installation, stage/waiting-for-release
