### ISSUE TITLE
Multiple lambda image application templates found. This should not be possible, please raise an issue

### ISSUE THREAD

**Issue by vsimon** [aws/aws-sam-cli#2846] opened 2021-04-30 22:28 UTC
### Description:

`Error: Multiple lambda image application templates found. This should not be possible, please raise an issue.`

### Steps to reproduce:

`brew install aws/tap/aws-sam-cli`

```
sam --version
SAM CLI, version 1.23.0
```

`sam init --name foo --package-type Image --base-image amazon/python3.8-base`

### Observed result:

```
sam init --name foo --package-type Image --base-image amazon/python3.8-base

Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates
Error: Multiple lambda image application templates found. This should not be possible, please raise an issue.
```

### Expected result:

Not an error?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OSX
2. `sam --version`: 1.23.0
3. AWS region: us-east-1

`Add --debug flag to command you are running`

```
sam init --name foo --package-type Image --base-image amazon/python3.8-base --debug
2021-04-30 15:26:45,011 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-04-30 15:26:45,012 | Using config file: samconfig.toml, config environment: default
2021-04-30 15:26:45,012 | Expand command line arguments to:
2021-04-30 15:26:45,012 | --name=foo --package_type=Image --base_image=amazon/python3.8-base --output_dir=.
2021-04-30 15:26:45,013 |
Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates
2021-04-30 15:26:47,252 | Removing old templates from /Users/foo/.aws-sam/aws-sam-cli-app-templates
2021-04-30 15:26:47,461 | Copying templates from /var/folders/1f/h901r68j4q7_j55p0njzl6hw0000gn/T/tmpb3u1gjat/aws-sam-cli-app-templates to /Users/foo/.aws-sam/aws-sam-cli-app-templates
2021-04-30 15:26:48,333 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '4a9f570a-e0bd-40af-bfad-5f28d40b3245', 'installationId': '1b956d32-90d8-4fe4-b89d-5ed6e9d13ba4', 'sessionId': '25f25ffd-c454-4e4a-be05-68ea30799926', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.9', 'samcliVersion': '1.23.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam init', 'duration': 3320, 'exitReason': 'LambdaImagesTemplateException', 'exitCode': 1}}]}
2021-04-30 15:26:48,587 | Telemetry response: 200
Error: Multiple lambda image application templates found. This should not be possible, please raise an issue.

```

**Comment by vsimon** [comment] 2021-04-30 22:33
There seems to be multiple folders inside /Users/$user/.aws-sam/aws-sam-cli-app-templates/python3.8-image

```
cookiecutter-aws-sam-hello-python-lambda-image
cookiecutter-ml-apigw-pytorch
cookiecutter-ml-apigw-scikit-learn
cookiecutter-ml-apigw-tensorflow
cookiecutter-ml-apigw-xgboost
```

**Comment by awood45** [comment] 2021-05-03 20:16
There's a known issue with this right now, if you run `sam init` interactively (without parameters) that is a workaround for now.

**Comment by justinmk3** [comment] 2021-05-05 18:11
Related: https://github.com/aws/aws-sam-cli-app-templates/issues/95

**Comment by elbayaaa** [comment] 2021-06-03 20:25
The issue is fixed in V.1.24.0
you can now use the `--app-template` argument to resolve this. For example:

```
sam init --name foo --package-type Image --base-image amazon/python3.8-base --app-template hello-world-lambda-image
```

**Closed by elbayaaa** 2021-06-03 20:25 UTC
Labels: area/init, type/bug
