### ISSUE TITLE
AWS::Serverless::Function CodeUri no longer supports Files

### ISSUE THREAD

**Issue by mfriesen** [aws/aws-sam-cli#2693] opened 2021-03-06 18:35 UTC
### Description:
Previous to sam-cli 1.2 you could specify a ZIP file in the CodeUri parameter. Now receiving error that the path in the CodeUri must be a directory.

Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.LambdaRuntime
      Runtime: provided
      CodeUri: ./lambda.zip

### Steps to reproduce:
Create a lambda compatible zip file and specify the zip file in the CodeUri: parameter

### Observed result:
Receive error that sam cli expects the ./lambda.zip file to be a directory.

Error: CustomMakeBuilder:CopySource - [Errno 20] Not a directory:

### Expected result:
I expect the 'sam build' command to completely successfully like v1.19.1 did.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Big Sur 11.2.2
2. `sam --version`: 1.2
3. AWS region: us-east-1

`Add --debug flag to command you are running`
2021-03-06 12:28:26,851 | Building codeuri: formkiq-pro/storage/lambda-s3-graalvm.zip runtime: provided metadata: {} functions: ['FormKiQ/CoreStorage/StagingS3Create', 'FormKiQ/CoreStorage/DocumentsS3Update']
2021-03-06 12:28:26,851 | Building to following folder /Users/slycer/Documents/workspace/java/24hourwebhook/api/.aws-sam/build/FormKiQ/CoreStorage/StagingS3Create
2021-03-06 12:28:26,854 | Loading workflow module 'aws_lambda_builders.workflows'
2021-03-06 12:28:26,855 | Found workflow 'CustomMakeBuilder' to support capabilities 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-03-06 12:28:26,857 | Running workflow 'CustomMakeBuilder'
2021-03-06 12:28:26,857 | Running CustomMakeBuilder:CopySource
2021-03-06 12:28:26,857 | CustomMakeBuilder:CopySource raised unhandled exception
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.20.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/Cellar/aws-sam-cli/1.20.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/actions.py", line 101, in execute
    copytree(self.source_dir, self.dest_dir, ignore=shutil.ignore_patterns(*self.excludes))
  File "/usr/local/Cellar/aws-sam-cli/1.20.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/utils.py", line 43, in copytree
    names = os.listdir(source)
NotADirectoryError: [Errno 20] Not a directory: '/Users/slycer/Documents/workspace/java/24hourwebhook/api/formkiq-pro/storage/lambda-s3-graalvm.zip'
2021-03-06 12:28:26,862 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '0dce9063-0ccb-48ea-acbe-360e332be720', 'installationId': '0b808f24-f70f-4bda-bc67-f2f6e75a8977', 'sessionId': 'e4b71770-8c76-4b67-ad33-7d78c71afab2', 'executionEnvironment': 'CLI', 'pyversion': '3.8.8', 'samcliVersion': '1.20.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 59782, 'exitReason': 'WorkflowUnknownError', 'exitCode': 1}}]}
2021-03-06 12:28:27,158 | Telemetry response: 200
Error: CustomMakeBuilder:CopySource - [Errno 20] Not a directory: '/Users/slycer/Documents/workspace/java/24hourwebhook/api/formkiq-pro/storage/lambda-s3-graalvm.zip'

**Comment by aahung** [comment] 2021-03-09 19:02
Hi @mfriesen, looks like you are building a template with nested stacks in it. It is likely to be a duplicate of #2692. Can you modify the `CodeUri` from `./lambda.zip` to the absolute path and try again?

**Comment by mfriesen** [comment] 2021-03-09 22:28
Using the absolute path, fixed that error but now it's expecting a build.gradle file along with the zip file?

Error: Unable to find a supported build workflow for runtime 'java11'. Reason: None of the supported manifests '['build.gradle', 'build.gradle.kts', 'pom.xml']' were found in the following paths '['/Users/slycer/Documents/workspace/java/24hourwebhook/api/formkiq-pro/console/console-installer.zip', '/Users/slycer/Documents/workspace/java/24hourwebhook/api']'

**Comment by aahung** [comment] 2021-03-09 23:40
@mfriesen that's great. As for the build.gradle, what's your original directory structure like (where is your build.gradle, your root/child templates and zips) and can you also provide a snippet of your template?

**Comment by aahung** [comment] 2021-03-09 23:41
@mfriesen BTW, how did you build the function `FormKiQ/CoreStorage/StagingS3Create` before v1.20.0?

**Comment by mfriesen** [comment] 2021-03-10 01:24
@aahung You can see the whole project and directory structure at https://github.com/formkiq/formkiq-core/releases/download/v1.2.8/formkiq-core-1.2.8.zip. 

My build process is completely independent of SAM build. I use SAM as a tool to deploy applications to AWS and not a build tool. This allows me to take a number of separate components and combine them into 1 application / cloudformation template.

**Comment by aahung** [comment] 2021-03-10 21:53
> @aahung You can see the whole project and directory structure at https://github.com/formkiq/formkiq-core/releases/download/v1.2.8/formkiq-core-1.2.8.zip.
> 
> My build process is completely independent of SAM build. I use SAM as a tool to deploy applications to AWS and not a build tool. This allows me to take a number of separate components and combine them into 1 application / cloudformation template.

I am kind of confused. If you don't use SAM to build, why you need to run `sam build`?

How can I reproduce your error? I tried to download your zip, unzip it then run `sam build --use-container` in it, I got stuck at `Mounting ~Downloads/formkiq-core-1.2.8/storage/lambda-s3-graalvm.zip as /tmp/samcli/source:ro,delegated inside runtime container`. I am not sure if I am doing it correctly.

**Comment by mfriesen** [comment] 2021-03-10 23:55
> I am kind of confused. If you don't use SAM to build, why you need to run sam build?

I used nested project to combine multiple projects into a new project. For example: I will create a new project using "sam init" and then I will ADD  formkiq-core as a nested project under that project. So the new project will need to build using sam build, but the nested project comes with a lambda ready .zip file.

Using "sam build --use-container" I am also getting that error. I don't believe the --use-container is necessary, but this all worked fine using sam 1.19.

**Comment by aahung** [comment] 2021-03-11 00:24
@mfriesen, thanks, I think I get the full picture now. 

before 1.20.0, resources in nested stack are not built by `sam build`, and since you build yourself and directly provide a build artifact as zip file, sam just needs to deploy it. 

now in 1.20.0, `sam build` will recursively build all resources, even in nested stacks, when `sam build` tries to build the function in nested stack, it assume you provides a source code instead of build artifacts, that's why it failed. 

In your use case, since your functions are already built, you should not run `sam build` at all. I just tested your template, you can directly run `sam deploy` to deploy the stacks.

**Comment by mfriesen** [comment] 2021-03-11 00:30
@aahung  That makes a lot of sense. What happens if I have some resources that DO need to be built by SAM? I like a said I build a lot of modules and then use them as nested projects in new projects. I believe that's a really powerful use case being able to reuse and share code.

**Comment by aahung** [comment] 2021-03-11 00:48
@mfriesen That's a good question. Unfortunately by default `sam build` will build all local functions right now. Here are two workarounds in case you want to selectively build certain functions. 

1. `sam build` will skip functions with a remote `CodeUri` (s3 path), so you can upload those functions you custom build to S3 and use links (`s3://`) as `CodeUri`. Then `sam build` will ignore them. (I prefer this one because it also reduce your release package size)
2. `sam build [RESOURCE_LOGICAL_ID]`, you can pass the logical ID of the functions you do want SAM to build (only works if you have a single function to build). 

And importantly, if you have a solution in mind or believe this is something SAM CLI should explicitly support, welcome [to create a feature request](https://github.com/aws/aws-sam-cli/issues/new?assignees=&labels=&template=Feature_request.md&title=).

**Comment by aahung** [comment] 2021-03-11 00:50
I am gonna close this issue since the main problem is a duplicate of #2692. Thanks!

**Closed by aahung** 2021-03-11 00:50 UTC
Labels: area/build, blocked/more-info-needed
