### ISSUE TITLE
Bug: sam delete keeps asking for --region found in samconfig.toml

### ISSUE THREAD

**Issue by jsmucr** [aws/aws-sam-cli#4119] opened 2022-08-14 14:08 UTC
### Description:

`sam delete` doesn't let me delete a stack without providing a set of parameters already defined in the `samconfig.toml` file.

### Steps to reproduce:

Create a stack with `samconfig.toml` looking a bit like this:

```toml
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
s3_bucket = "<your bucket>"
s3_prefix = "<your prefix>"
kms_key_id = "<your S3 access key>"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = false
disable_rollback = false
```

With this you should be able to deploy a stack based on `template.yaml` only by calling

```
sam build
sam deploy --stack-name mystack
```

Try deleting it:

```
sam delete --stack-name mystack --no-prompts --debug
```

### Observed result:

```
sam delete --stack-name tsb-aim-production --no-prompts --debug
```
```
2022-08-14 15:55:23,217 | Using config file: samconfig.toml, config environment: default
2022-08-14 15:55:23,217 | Expand command line arguments to:
2022-08-14 15:55:23,217 | --stack_name=tsb-aim-production --no_prompts
2022-08-14 15:55:23,308 | Config file location: /c/user/git/tsb-lambda/samconfig.toml
2022-08-14 15:55:23,310 | Loading configuration values from [default.['deploy'].parameters] (env.command_name.section) in config file at '/c/user/git/tsb-lambda/samconfig.toml'...
2022-08-14 15:55:23,315 | Configuration values successfully loaded.
2022-08-14 15:55:23,315 | Configuration values are: {'s3_bucket': '[redacted]', 's3_prefix': 'tsb', 'kms_key_id': '[redacted]', 'region': 'eu-central-1', 'capabilities': 'CAPABILITY_IAM', 'image_repositories': [], 'confirm_changeset': False, 'disable_rollback': False}
Usage: sam delete [OPTIONS]

Error: Missing option '--region', region is required to run the non guided delete command.
```

### Expected result:

The SAM stack is deleted.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 / WSL2 Ubuntu 20.04.4 LTS
2. `sam --version`: SAM CLI, version 1.53.0
3. AWS region: eu-central-1

**Comment by jfuss** [comment] 2022-08-15 14:29
@jsmucr You need to have `default.delete.parameters` in your `samconfig.toml`. They way the `samconfig.toml` operates is by command config. So `deploy` parameters will not be picked up in `delete`.

If you want to specify a region per environment (in your example default is the environment), you can add 

```
[default.global.parameters]
region = "eu-central-1"
```

to the `samconfig.toml`, which should yield the results you want. https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html has more info on this.

**Comment by jsmucr** [comment] 2022-08-15 17:51
I didn't use `delete` parameters because it does not work (and it's also mentioned here: https://github.com/aws/aws-sam-cli/issues/3514#issuecomment-985976444).
Stripping the whole example of the unnecessary...
```toml
version = 0.1
[default.delete.parameters]
region = "eu-central-1"
```
```
sam delete --stack-name tsb-aim-production --no-prompts
```
...I still get
```
2022-08-15 19:41:56,163 | Using config file: samconfig.toml, config environment: default
2022-08-15 19:41:56,163 | Expand command line arguments to:
2022-08-15 19:41:56,163 | --stack_name=tsb-aim-production --no_prompts
2022-08-15 19:41:56,253 | Config file location: /c/user/git/tsb-lambda/samconfig.toml
2022-08-15 19:41:56,255 | Loading configuration values from [default.['deploy'].parameters] (env.command_name.section) in config file at '/c/user/git/tsb-lambda/samconfig.toml'...
2022-08-15 19:41:56,258 | Configuration values successfully loaded.
2022-08-15 19:41:56,258 | Configuration values are: {}
```
With the `global` entry the output is slightly different but ending up the same way:
```toml
version = 0.1
[default.global.parameters]
region = "eu-central-1"
```
```
sam delete --stack-name tsb-aim-production --no-prompts
```
```
2022-08-15 19:44:36,298 | Using config file: samconfig.toml, config environment: default
2022-08-15 19:44:36,298 | Expand command line arguments to:
2022-08-15 19:44:36,298 | --stack_name=tsb-aim-production --no_prompts
2022-08-15 19:44:36,388 | Config file location: /c/user/git/tsb-lambda/samconfig.toml
2022-08-15 19:44:36,389 | Loading configuration values from [default.['deploy'].parameters] (env.command_name.section) in config file at '/c/user/git/tsb-lambda/samconfig.toml'...
2022-08-15 19:44:36,393 | Configuration values successfully loaded.
2022-08-15 19:44:36,393 | Configuration values are: {'region': 'eu-central-1'}
Usage: sam delete [OPTIONS]

Error: Missing option '--region', region is required to run the non guided delete command.
```
Please notice two things:
- The output keeps referring to `default.['deploy'].parameters` despite the command being `sam delete`.
- With both the `global` and `deploy` ways the command recognizes the arguments properly, but then it fails anyway.

What am I doing wrong now?

**Comment by jfuss** [comment] 2022-08-15 19:04
@jsmucr Let me get back to you once I do a deeper dive. It's odd we deviated for `delete` but maybe I am just not as update to date as I thought. 

This might be a duplicate of https://github.com/aws/aws-sam-cli/issues/3621? Let me do some more digging to confirm though.

**Comment by jsmucr** [comment] 2022-08-31 08:25
@jfuss I think this is where the issue comes from (`delete_context.py`):
```python
    def parse_config_file(self):
        """
        Read the provided config file if it exists and assign the options values.
        """
        toml_provider = TomlProvider(CONFIG_SECTION, [CONFIG_COMMAND])
        config_options = toml_provider(
            config_path=self.config_file, config_env=self.config_env, cmd_names=[CONFIG_COMMAND]
        )
        if not config_options:
            return

        if not self.stack_name:
            self.stack_name = config_options.get("stack_name", None)
        # If the stack_name is same as the one present in samconfig file,
        # get the information about parameters if not specified by user.
        if self.stack_name and self.stack_name == config_options.get("stack_name", None):
            LOG.debug("Local config present and using the defined options")
            if not self.region:
                self.region = config_options.get("region", None)
            if not self.profile:
                self.profile = config_options.get("profile", None)
            if not self.s3_bucket:
                self.s3_bucket = config_options.get("s3_bucket", None)
            if not self.s3_prefix:
                self.s3_prefix = config_options.get("s3_prefix", None)
```
The issue with this is that if I specify the stack name via the command line while it's not specified in the config file as well, the             `region`, `s3_bucket` and `s3_prefix` presets aren't used at all.

**Comment by hnnasit** [comment] 2022-09-02 21:16
Hi @jsmucr, I checked the delete_context.py file and this is an intended behavior. The stack_name check is done with the samconfig.toml file stack_name so that the parameters which were used to deploy a particular stack can be reused to delete that stack. The rationale behind this is precaution and to prevent users from deleting something by mistake as unlike build/deploy delete is a destructive command and cannot be reversed. As a solution, you can add the stack-name to the samconfig file and try running sam delete --stack-name <> .

**Comment by qingchm** [comment] 2022-12-15 10:13
@cortexcompiler This mechanism is mainly aimed to focus on protecting users from accidentally deleting stacks if the stack name specified in command line option doesn't match with what's in the samconfig file, and you are poking at a direction where if the stack name is empty in the samconfig, it shouldn't be treated the same way as having a different stack name and user should be able to proceed delete with other specified parameters like region?

**Comment by qingchm** [comment] 2023-01-26 18:46
@jsmucr Please refer to the above justifications for the behaviour, feel free to re-open this issue if you want to discuss more about the design here. But so far this is expected behaviour!

**Closed by qingchm** 2023-01-26 18:46 UTC
Labels: area/sam-config, area/delete

**Comment by jsmucr** [comment] 2023-02-07 10:35
I understand the reasons (mostly). I stopped using this feature entirely as it's of no use to me in it's current state.
