### ISSUE TITLE
Allow customization of which files to exclude during `CustomMakeBuilder:CopySource`

### ISSUE THREAD

**Issue by komapa** [aws/aws-sam-cli#3350] opened 2021-10-08 21:08 UTC
### Describe your idea/feature/enhancement

Related to some of what I said in https://github.com/aws/aws-sam-cli/issues/3348

If your source tree has a lot of files, think golang `vendor/` folder AND also `node_modules`, `CustomMakeBuilder:CopySource` is super slow to the point of not even completing in many minutes (not sure if just the way it copies is also inefficient?) The root folder was close to 500MB, so not a lot of storage but I guess a lot of files.

### Proposal

It will be great if you can support reading `.gitignore` or allow for a `.samignore` file that will allow us to exclude large directories which are not needed for building but are naturally in the repo because of the project structure you might have in place.

### Additional Details

Thank you!

**Comment by nthornton2010** [comment] 2021-11-17 20:25
Yes please! My makefile being in the root causes sam build to take over 10 minutes to complete just because of node_modules.

**Comment by ksmoore17** [comment] 2022-01-21 03:16
Would be a solution for #1755 and #2310 -> examples of this being caused by python's `venv` and `node_modules` and occurring for pip builder and npm builder

**Comment by torresxb1** [comment] 2023-01-18 21:46
We have a few issues asking for a similar thing in `ignore:` or a `.samignore` file. Closing so that we can track here: https://github.com/aws/aws-lambda-builders/issues/185

**Closed as completed by torresxb1** 2023-01-18 21:46 UTC
Labels: type/feature, area/build, maintainer/need-followup
