### ISSUE TITLE
sam local invoke errors when 3-rd party layer is used: Invalid Layer name

### ISSUE THREAD

**Issue by Envek** [aws/aws-sam-cli#2347] opened 2020-11-02 19:56 UTC
### Description

If I add some external Lambda Layer (e.g. for monitoring and error reporting) then `sam local invoke` stops working.

### Steps to reproduce

 1. Create sample applicatiion with `sam init`, choose Node.js 12.x runtime and SQS example.

 2. Add 3-rd party layer into function definition in `template.yml`:

    ```yml
          Layers:
            - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:464622532012:layer:Datadog-Node12-x:36"
    ```

 3. Build and invoke function as usual

    ```sh
    sam build
    sam local invoke --event events/event-sqs.json
    ```

### Observed result

```
An error occurred (InvalidParameterValueException) when calling the GetLayerVersion operation: Invalid Layer name: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node12-x
```

<details>
<summary>Click to expand output of `sam local invoke --event events/event-sqs.json --debug`</summary>

```
2020-11-02 22:46:12,152 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2020-11-02 22:46:12,274 | local invoke command is called
2020-11-02 22:46:12,280 | No Parameters detected in the template
2020-11-02 22:46:12,317 | 2 resources found in the template
2020-11-02 22:46:12,317 | Found Serverless function with name='SQSPayloadLogger' and CodeUri='SQSPayloadLogger'
2020-11-02 22:46:12,321 | Found one Lambda function with name 'SQSPayloadLogger'
2020-11-02 22:46:12,321 | Invoking src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler (nodejs12.x)
2020-11-02 22:46:12,321 | No environment variables found for function 'SQSPayloadLogger'
2020-11-02 22:46:12,321 | Environment variables overrides data is standard format
2020-11-02 22:46:12,321 | Loading AWS credentials from session with profile 'None'
2020-11-02 22:46:12,338 | Resolving code path. Cwd=/home/envek/evl.ms/2uinc/sam-app/.aws-sam/build, CodeUri=SQSPayloadLogger
2020-11-02 22:46:12,338 | Resolved absolute path to code is /home/envek/evl.ms/2uinc/sam-app/.aws-sam/build/SQSPayloadLogger
2020-11-02 22:46:12,338 | Code /home/envek/evl.ms/2uinc/sam-app/.aws-sam/build/SQSPayloadLogger is not a zip/jar file
2020-11-02 22:46:13,619 | Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 1465, 'exitReason': 'InvalidParameterValueException', 'exitCode': 255, 'requestId': 'e5532896-87fa-41e9-930f-c172b5cab3d9', 'installationId': '33ae4d3b-0f37-4b53-9f05-3b6cbb85cda6', 'sessionId': '421463e4-057e-4a74-9dcb-82621aa7c8c7', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.7.0'}}]}
2020-11-02 22:46:14,773 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.7.0', 'console_scripts', 'sam')())
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 148, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 114, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 72, in cli
    do_cli(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 152, in do_cli
    context.local_lambda_runner.invoke(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 103, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 70, in invoke
    container = LambdaContainer(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 73, in __init__
    image = LambdaContainer._get_image(image_builder, runtime, layers, debug_options)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 179, in _get_image
    return image_builder.build(runtime, layers, is_debug)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 107, in build
    downloaded_layers = self.layer_downloader.download_all(layers, self.force_image_build)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/local/layers/layer_downloader.py", line 72, in download_all
    layer_dirs.append(self.download(layer, force))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/local/layers/layer_downloader.py", line 106, in download
    layer_zip_uri = self._fetch_layer_uri(layer)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/local/layers/layer_downloader.py", line 155, in _fetch_layer_uri
    raise e
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/samcli/local/layers/layer_downloader.py", line 136, in _fetch_layer_uri
    layer_version_response = self.lambda_client.get_layer_version(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.7.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the GetLayerVersion operation: Invalid Layer name: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node12-x
```
</details>

### Expected result

Lambda function invoked with layer 3rd-party layer from correct region (in `~/.aws/config` was `us-west-2` was specified, but error complains about `us-east-1`).

### Additional environment details

1. OS: Ubuntu Linux 18.04
2. `sam --version`: `SAM CLI, version 1.7.0` installed from Linuxbrew (as recommended)

**Comment by sforcier** [comment] 2020-11-06 19:56
So I found a temporary workaround that worked for me. IMO this does not negate the need for a fix, but it may help people while they wait for one.

- Set your PC's region to the one it's complaining about
- Run the function locally once
- Set your PC's region back to what you actually want to use

Then you should be OK. Running the function within the region SAM expects causes the layer to be cached and so subsequent requests will work.

**Comment by hawflau** [comment] 2020-11-09 23:56
Hey @Envek thanks for reporting this. A fix for this is to use the `--region` flag. For example:
```
sam local invoke -- event events/event-sqs.json --region us-west-2
```

**Comment by Envek** [comment] 2020-11-10 15:19
`--region` flag helps, thank you!

May be it is because I don't have region in my default AWS configuration (I'm using [named profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) instead).

So I have following in my `~/.aws/config`:
```ini
[profile some-client-aws]
region = us-west-2
output = json
```
And using it like so:
```sh
export AWS_PROFILE=some-client-aws
sam build
sam local invoke --event events/event-sqs.json
```

And I'm expecting that it will use region from this named profile.

**Comment by Envek** [comment] 2021-05-17 12:37
Also it doesn't honor `AWS_DEFAULT_REGION` [environment variable](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html). This is still is an issue on latest SAM CLI, version 1.23.0.

**Comment by tostangs** [comment] 2021-05-28 00:15
I'm unable to get this resolved even when manually providing the region thru the cli. I'm having to implement a project along the same lines here, adding a 3rd party Layer arn reference, then testing the function locally with the layer fails every time. I'm working with node v16.1.0 and SAM CLI v1.23.0.

**Comment by mndeveci** [comment] 2023-01-10 21:37
Resolving this since this is a duplicate of https://github.com/aws/aws-sam-cli/issues/4208

**Closed by mndeveci** 2023-01-10 21:37 UTC
Labels: type/bug, area/local/invoke, maintainer/need-followup
