### ISSUE TITLE
Bug: sam publish fails with a ScheduleV2 event on Serverless:StateMachine

### ISSUE THREAD

**Issue by cdschneider** [aws/aws-sam-cli#4543] opened 2023-01-06 02:03 UTC
### Description:

My `sam publish` command is failing with the following error:

```bash
$> sam publish
Publish Failed
Error: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [ExpireAccessKeysStateMachine] is invalid. Event with id [RecurringSchedule] is invalid. Resource dict has missing or invalid value for key Type. Event Type is: ScheduleV2.
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

### Steps to reproduce:

* Add a simple `ScheduleV2` ([EventBridge Scheduler schedule](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-statemachineschedulev2.html)) `EventSource` to a `AWS::Serverless::StateMachine` resource, like I have in my project:

```yaml
  ExpireAccessKeysStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
    # other StateMachine properties
      Events:
        RecurringSchedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(5 minutes)"
```

* Follow the steps from the AWS/SAM guide on publishing applications to the [Serverless Application Repository](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html)

### Observed result:

```bash
$> sam publish --debug 
2023-01-05 19:58:57,856 | Config file location: /Users/cdschneid/Projects/cdschneider/aws-access-key-expiry/samconfig.toml
2023-01-05 19:58:57,857 | Loading configuration values from [default.['publish'].parameters] (env.command_name.section) in config file at '/Users/cdschneid/Projects/cdschneider/aws-access-key-expiry/samconfig.toml'...
2023-01-05 19:58:57,859 | Configuration values successfully loaded.
2023-01-05 19:58:57,859 | Configuration values are: {'region': 'us-east-1', 'template_file': 'packaged.yaml'}
2023-01-05 19:58:57,865 | Using SAM Template at /Users/cdschneid/Projects/cdschneider/aws-access-key-expiry/packaged.yaml
2023-01-05 19:58:57,877 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-01-05 19:58:57,877 | Using config file: samconfig.toml, config environment: default
2023-01-05 19:58:57,877 | Expand command line arguments to:
2023-01-05 19:58:57,877 | --template_file=/Users/cdschneid/Projects/cdschneider/aws-access-key-expiry/packaged.yaml 
Publish Failed
2023-01-05 19:58:59,500 | Failed to publish application to serverlessrepo
Traceback (most recent call last):
  File "serverlessrepo/publish.py", line 45, in publish_application
  File "botocore/client.py", line 401, in _api_call
  File "botocore/client.py", line 731, in _make_api_call
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateApplication operation: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [ExpireAccessKeysStateMachine] is invalid. Event with id [RecurringSchedule] is invalid. Resource dict has missing or invalid value for key Type. Event Type is: ScheduleV2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samcli/commands/publish/command.py", line 86, in do_cli
  File "serverlessrepo/publish.py", line 50, in publish_application
serverlessrepo.exceptions.ServerlessRepoClientError: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [ExpireAccessKeysStateMachine] is invalid. Event with id [RecurringSchedule] is invalid. Resource dict has missing or invalid value for key Type. Event Type is: ScheduleV2.
2023-01-05 19:58:59,554 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '85a38a20-ffbe-4e62-bc15-1503b97e7ad0', 'installationId': '7ae700e8-3e88-4f05-a794-3b67925c7cbe', 'sessionId': '75756c4b-2324-46e8-b085-b7be97016714', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.66.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'us-east-1', 'commandName': 'sam publish', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': 'f0a09c8e2756e429c1e97cf0cb37fef38ec0a01796f1268f8626176e6ca292b1', 'initialCommit': None}, 'duration': 1677, 'exitReason': 'ServerlessRepoClientError', 'exitCode': 1}}]}
2023-01-05 19:58:59,809 | Telemetry response: 200
Error: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [ExpireAccessKeysStateMachine] is invalid. Event with id [RecurringSchedule] is invalid. Resource dict has missing or invalid value for key Type. Event Type is: ScheduleV2.
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

### Expected result:

Since my template contains a syntactically-valid SAM resource template, I would have expected a successful publish of my application to the Serverless Application Repository.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 12.6.1 (M1/MacBook Pro)
2. `sam --version`: `SAM CLI, version 1.66.0`
3. AWS region: `us-east-1`

**Comment by hnnasit** [comment] 2023-01-06 06:53
Thanks for reporting this issue, I was able to reproduce the error. Looks like the Type ScheduleV2 (AWS::Scheduler::Schedule resource) is not yet supported by SAR. The complete list of resources supported by SAR can be found [here](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html). I will check with the team if this can be supported.

**Comment by cdschneider** [comment] 2023-01-06 12:04
Thank you for this @hnnasit! I knew there was a list of resources that the SAR supported from CloudFormation, I just couldn't find this list myself in the documentation.

Please let me know what you find, and in the meantime I'll switch my `EventSource` to using a "classic" [`Schedule` resource](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-statemachineschedule.html).

**Comment by hnnasit** [comment] 2023-01-06 20:28
@cdschneider I have cut an internal ticket to the relevant team to look into this issue. I'd suggest you to reach out to [AWS Support Forum for SAR](https://forums.aws.amazon.com/forum.jspa?forumID=287) if you have any questions.
Closing as there is nothing we can do on the SAM CLI side.

**Closed by hnnasit** 2023-01-06 20:28 UTC
Labels: type/bug, area/publish
