### ISSUE TITLE
Add a docker volume mount option for sam local invoke

### ISSUE THREAD

**Issue by CJohnsonLehi** [aws/aws-sam-cli#1896] opened 2020-03-26 13:27 UTC
I wish SAM CLI would have an extra --volume parameter that I could mount an arbitrary directory on my host machine to an arbitrary directory inside my docker container. 

Under the hood, sam could forward this parameter to docker run using the -v parameter that docker run already supports.

I ask this, because I would like to get some files out of my docker container after my lambda function executes.

**Comment by cosbor11** [comment] 2020-05-28 03:47
@CJohnsonLehi - Is there a workaround?

**Comment by futurama92** [comment] 2020-08-06 17:54
i'm interested too in this feature, it let me emulate EFS

**Comment by NotSoSuper** [comment] 2020-08-25 22:14
Same! My lambdas depend on EFS. If anyone has a workaround or hack to pass in arguments to the docker run command that'd be great for the meanwhile.

**Comment by ryan-mars** [comment] 2020-09-21 19:18
Does anyone have a manual workaround for this at the moment?

**Comment by dacgray** [comment] 2021-03-09 02:17
For reference - this is how we get around this issue:

https://github.com/dacgray/sam-local-start-api-container-image-volume-mount

**Comment by moelasmar** [comment] 2021-11-11 00:32
duplicate of issue #2589

**Closed by moelasmar** 2021-11-11 00:32 UTC
Labels: type/feature, maintainer/need-response

**Comment by dschiavu** [comment] 2023-02-25 00:08
I'd vote for this one as well. Very much needed for many use cases.
