### ISSUE TITLE
Validation error with more than 50 parameters

### ISSUE THREAD

**Issue by dave-kennedy** [aws/aws-sam-cli#3757] opened 2022-03-18 18:50 UTC
I didn't find this issue in the backlog.

### Description:

My template has 53 parameters. `sam validate` throws this error:

```
% sam validate
2022-03-18 12:13:00 Loading policies from IAM...
2022-03-18 12:13:03 Finished loading policies from IAM.
2022-03-18 12:13:03 Template schema validation reported the following errors: [, P, a, r, a, m, e, t, e, r, s, ],  , O, r, d, e, r, e, d, D, i, c, t, (, [, (, ', A, w, s, R, e, g, i, o, n, ', ,,  , O, r, d, e, r, e, d, D, i, c, t, (, [, (, ', T, y, p, e, ', ,,  , ', S, t, r, i, n, g, ', ), ,,  , (, ', D, e, s, c, r, i, p, t, i, o, n, ', ,,  , ', A, W, S,  , R, e, g, i, o, n,  , b, e, i, n, g,  , u, s, e, d, ', ), ,,  , (, ', D, e, f, a, u, l, t, ', ,,  , ', u, s, -, e, a, s, t, -, 1, ', ), ], ), )...
```

I know the spaces in the error message are due to #3493 (still waiting on aws/serverless-application-model#2245). That's not the issue. This is what it looks like without the spaces (and with added line breaks):

```
[Parameters]
OrderedDict(
    [
        (
            'AwsRegion',
            OrderedDict(
                [
                    ('Type', 'String'),
                    ('Description', 'AWS Region being used'),
                    ('Default', 'us-east-1')
                ]
            )
        ),
        [a bunch of other properties here...],
    ]
) has too many properties
```

The error at the bottom is the relevant part. Removing any three of the parameters makes this error go away.

### Steps to reproduce:

1. Run `sam validate` on a template with more than 50 parameters.

### Observed result:

Validation error: `[Parameters] OrderedDict... has too many properties`

### Expected result:

CloudFormation supposedly supports up to 200 parameters, so it should validate.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 11.6.4
2. `sam --version`: 1.40.1
3. AWS region: us-east-1

`Add --debug flag to command you are running`

```
% sam validate --debug
2022-03-18 12:45:56,928 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-03-18 12:45:56,928 | Using config file: samconfig.toml, config environment: default
2022-03-18 12:45:56,928 | Expand command line arguments to:
2022-03-18 12:45:56,928 | --template_file=/Users/dave.kennedy/sam-api/template.yaml
2022-03-18 12:45:57 Loading policies from IAM...
2022-03-18 12:45:59 Finished loading policies from IAM.
2022-03-18 12:45:59 Template schema validation reported the following errors: [, P, a, r, a, m, e, t, e, r, s, ],  , O, r, d, e, r, e, d, D, i, c, t, (, [, (, ', A, w, s, R, e, g, i, o, n, ', ,,  , O, r, d, e, r, e, d, D, i, c, t, (, [, (, ', T, y, p, e, ', ,,  , ', S, t, r, i, n, g, ', ), ,,  , (, ', D, e, s, c, r, i, p, t, i, o, n, ', ,,  , ', A, W, S,  , R, e, g, i, o, n,  , b, e, i, n, g,  , u, s, e, d, ', )...
2022-03-18 12:45:59,425 | Translated template is:
AWSTemplateFormatVersion: '2010-09-09'
Description: SAM API template
Parameters:
  AwsRegion:
    Type: String
    Description: AWS Region being used
    Default: us-east-1
...

/Users/dave.kennedy/sam-api/template.yaml is a valid SAM Template
2022-03-18 12:45:59 There are unpublished metrics. Please make sure you call publish after you record all metrics.
2022-03-18 12:45:59 There are unpublished metrics. Please make sure you call publish after you record all metrics.
```

I can't disclose the entire template, hope that isn't a problem.

**Comment by qingchm** [comment] 2022-04-06 01:11
Thanks for reporting this to us @dave-kennedy ! We will get to this issue by trying to reproduce this first! Can I please get more context on what your template looks like, maybe a snippet of your template that contains the "parameters" section? I would Assume what you need in your yaml template is something like
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Example

Parameters:
  AwsRegion:
    Type: String
    Description: AWS Region being used
    Default: us-east-1
    Properties: dfsfs
...
```
Does this format of the template satisfy your needs? Sorry I couldn't quite follow the use of the OrderedDict string and other parenthesis here, it would be really helpful if you can help me understand the situation better here. Thanks!

**Comment by dave-kennedy** [comment] 2022-04-08 16:50
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  Parameter1:
    Type: String
  Parameter2:
    Type: String
  Parameter3:
    Type: String
  Parameter4:
    Type: String
  Parameter5:
    Type: String
  Parameter6:
    Type: String
  Parameter7:
    Type: String
  Parameter8:
    Type: String
  Parameter9:
    Type: String
  Parameter10:
    Type: String
  Parameter11:
    Type: String
  Parameter12:
    Type: String
  Parameter13:
    Type: String
  Parameter14:
    Type: String
  Parameter15:
    Type: String
  Parameter16:
    Type: String
  Parameter17:
    Type: String
  Parameter18:
    Type: String
  Parameter19:
    Type: String
  Parameter20:
    Type: String
  Parameter21:
    Type: String
  Parameter22:
    Type: String
  Parameter23:
    Type: String
  Parameter24:
    Type: String
  Parameter25:
    Type: String
  Parameter26:
    Type: String
  Parameter27:
    Type: String
  Parameter28:
    Type: String
  Parameter29:
    Type: String
  Parameter30:
    Type: String
  Parameter31:
    Type: String
  Parameter32:
    Type: String
  Parameter33:
    Type: String
  Parameter34:
    Type: String
  Parameter35:
    Type: String
  Parameter36:
    Type: String
  Parameter37:
    Type: String
  Parameter38:
    Type: String
  Parameter39:
    Type: String
  Parameter40:
    Type: String
  Parameter41:
    Type: String
  Parameter42:
    Type: String
  Parameter43:
    Type: String
  Parameter44:
    Type: String
  Parameter45:
    Type: String
  Parameter46:
    Type: String
  Parameter47:
    Type: String
  Parameter48:
    Type: String
  Parameter49:
    Type: String
  Parameter50:
    Type: String
  Parameter51:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

```
$ sam validate
2022-04-08 10:48:08 Loading policies from IAM...
2022-04-08 10:48:10 Finished loading policies from IAM.
2022-04-08 10:48:10 Template schema validation reported the following errors: [Parameters] OrderedDict([('Parameter1', OrderedDict([('Type', 'String')])), ('Parameter2', OrderedDict([('Type', 'String')])), ('Parameter3', OrderedDict([('Type', 'String')])), ('Parameter4', OrderedDict([('Type', 'String')])), ('Parameter5', OrderedDict([('Type', 'String')])), ('Parameter6', OrderedDict([('Type', 'String')])), ('Parameter7', OrderedDict([('Type', 'String')])), ('Parameter8', OrderedDict([('Type', 'String')])), ('Parameter9', OrderedDict([('Type', 'String')])), ('Parameter10', OrderedDict([('Type', 'String')])), ('Parameter11', OrderedDict([('Type', 'String')])), ('Parameter12', OrderedDict([('Type', 'String')])), ('Parameter13', OrderedDict([('Type', 'String')])), ('Parameter14', OrderedDict([('Type', 'String')])), ('Parameter15', OrderedDict([('Type', 'String')])), ('Parameter16', OrderedDict([('Type', 'String')])), ('Parameter17', OrderedDict([('Type', 'String')])), ('Parameter18', OrderedDict([('Type', 'String')])), ('Parameter19', OrderedDict([('Type', 'String')])), ('Parameter20', OrderedDict([('Type', 'String')])), ('Parameter21', OrderedDict([('Type', 'String')])), ('Parameter22', OrderedDict([('Type', 'String')])), ('Parameter23', OrderedDict([('Type', 'String')])), ('Parameter24', OrderedDict([('Type', 'String')])), ('Parameter25', OrderedDict([('Type', 'String')])), ('Parameter26', OrderedDict([('Type', 'String')])), ('Parameter27', OrderedDict([('Type', 'String')])), ('Parameter28', OrderedDict([('Type', 'String')])), ('Parameter29', OrderedDict([('Type', 'String')])), ('Parameter30', OrderedDict([('Type', 'String')])), ('Parameter31', OrderedDict([('Type', 'String')])), ('Parameter32', OrderedDict([('Type', 'String')])), ('Parameter33', OrderedDict([('Type', 'String')])), ('Parameter34', OrderedDict([('Type', 'String')])), ('Parameter35', OrderedDict([('Type', 'String')])), ('Parameter36', OrderedDict([('Type', 'String')])), ('Parameter37', OrderedDict([('Type', 'String')])), ('Parameter38', OrderedDict([('Type', 'String')])), ('Parameter39', OrderedDict([('Type', 'String')])), ('Parameter40', OrderedDict([('Type', 'String')])), ('Parameter41', OrderedDict([('Type', 'String')])), ('Parameter42', OrderedDict([('Type', 'String')])), ('Parameter43', OrderedDict([('Type', 'String')])), ('Parameter44', OrderedDict([('Type', 'String')])), ('Parameter45', OrderedDict([('Type', 'String')])), ('Parameter46', OrderedDict([('Type', 'String')])), ('Parameter47', OrderedDict([('Type', 'String')])), ('Parameter48', OrderedDict([('Type', 'String')])), ('Parameter49', OrderedDict([('Type', 'String')])), ('Parameter50', OrderedDict([('Type', 'String')])), ('Parameter51', OrderedDict([('Type', 'String')]))]) has too many properties
/Users/dave.kennedy/Code/sam-test/sam-app/template.yaml is a valid SAM Template
```

**Comment by jfuss** [comment] 2023-02-10 02:42
Cloudformation supports 200 Parameters now. We also recently shipped cfn-lint capabilities within SAM CLI. `cfn-lint` already handles this (and much more). The specific rule is https://github.com/aws-cloudformation/cfn-lint/blob/main/src/cfnlint/rules/parameters/LimitNumber.py. This can be run by using `sam validate --lint`. 

Closing as this is now supported.

**Closed by jfuss** 2023-02-10 02:42 UTC
Labels: stage/needs-feedback, stage/bug-repro, maintainer/need-followup
