### ISSUE TITLE
Max Memory Used Incorrect

### ISSUE THREAD

**Issue by cccassidy** [aws/aws-sam-cli#2464] opened 2020-12-08 02:05 UTC
### Description:
When using the python 3.8 lambda runtime the 'Max Memory Used' always shows the same number as the total memory allocated.

### Steps to reproduce:
Running any python 3.8 lambda w/ v 1.13.2

### Observed result:
Max Memory Used always = Memory Allocated

### Expected result:
Expected result is the actual memory usage of the Lambda

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux Centos 7
2. `sam --version`: 1.13.2

Other versions:
awscli: 1.18.189
botocore: 1.19.14
boto3: 1.13.19

**Comment by nrg-thom** [comment] 2020-12-08 20:18
I thought it was just my configuration, but this appears to be happening way before version 1.13.2. I first noticed it two weeks ago. It may have something to do with a newer version of AWS CLI. After I upgraded to the latest version, that's when I started seeing this issue.

**Comment by cccassidy** [comment] 2020-12-08 20:26
> 
> 
> I thought it was just my configuration, but this appears to be happening way before version 1.13.2. I first noticed it two weeks ago. It may have something to do with a newer version of AWS CLI. After I upgraded to the latest version, that's when I started seeing this issue.

I posted the versions of the CLI/botocore/boto3 I am running.  Maybe we can find some commonalities.

**Comment by nrg-thom** [comment] 2020-12-08 20:32
> > I thought it was just my configuration, but this appears to be happening way before version 1.13.2. I first noticed it two weeks ago. It may have something to do with a newer version of AWS CLI. After I upgraded to the latest version, that's when I started seeing this issue.
> 
> I posted the versions of the CLI/botocore/boto3 I am running. Maybe we can find some commonalities.

Hmm... Maybe not. Here's mine:

OS: Windows 10 
SAM version: 1.13.2
AWS CLI: 2.1.5
boto3: 1.16.28
botocore: 1.19.28

The only things we have in common so far are Python 3.8 and SAM CLI 1.13.2. I really hope that this issue doesn't affect production. I mean if it's saying that we're using the max memory size (let's say 2048), then we're being billed for that much.

**Comment by nrg-thom** [comment] 2020-12-08 22:02
So, the issue is "fixed" by downgrading to 1.12.0.

**Comment by jfuss** [comment] 2020-12-09 17:19
This is currently expected. Locally, there was no good way to see memory used within the container so it defaults to the Memory Size provided: https://github.com/aws/aws-lambda-runtime-interface-emulator/blob/main/cmd/aws-lambda-rie/handlers.go#L48

This is only affected in the local emulator and is purely just output.

Closing as this is a limitation by aws-lambda-rie currently.

**Closed by jfuss** 2020-12-09 17:19 UTC

**Comment by tazsingh** [comment] 2021-01-02 13:25
> the issue is "fixed" by downgrading to 1.12.0

And unfortunately losing all the features in subsequent releases 😅 I'm really enjoying the official Warm Containers feature from 1.14!

------------------------------------------------------------

I was bit by this quite badly recently, not strictly because the Memory Usage is the same as the Memory Size, but because there is no error telling me there is an Out Of Memory error when it actually happened. The Lambda just fails once the memory limit is hit, with the following output:

```sh
END RequestId: 45832c6d-7be9-49f6-a7d0-f4540affad04
REPORT RequestId: 45832c6d-7be9-49f6-a7d0-f4540affad04        Duration: 1731.93 ms    Billed Duration: 1800 ms      Memory Size: 256 MB  Max Memory Used: 256 MB
Invalid lambda response received: Lambda response must be valid json
2021-01-02 13:17:40 127.0.0.1 - - [02/Jan/2021 13:17:40] "GET / HTTP/1.1" 502 -
```

Note: I'm not even getting the opportunity to respond, the process just quits as soon as the memory limit is reached. So that 'invalid JSON response' message had me chasing the wrong goose.

Given the limitation to display the memory usage, would it be possible to notify me that an OOM error has occurred such that I can debug accordingly?

Thanks!

**Comment by nrg-thom** [comment] 2021-01-04 14:04
> > the issue is "fixed" by downgrading to 1.12.0
> 
> And unfortunately losing all the features in subsequent releases 😅 I'm really enjoying the official Warm Containers feature from 1.14!
> 
> I was bit by this quite badly recently, not strictly because the Memory Usage is the same as the Memory Size, but because there is no error telling me there is an Out Of Memory error when it actually happened. The Lambda just fails once the memory limit is hit, with the following output:
> 
> ```shell
> END RequestId: 45832c6d-7be9-49f6-a7d0-f4540affad04
> REPORT RequestId: 45832c6d-7be9-49f6-a7d0-f4540affad04        Duration: 1731.93 ms    Billed Duration: 1800 ms      Memory Size: 256 MB  Max Memory Used: 256 MB
> Invalid lambda response received: Lambda response must be valid json
> 2021-01-02 13:17:40 127.0.0.1 - - [02/Jan/2021 13:17:40] "GET / HTTP/1.1" 502 -
> ```
> 
> Note: I'm not even getting the opportunity to respond, the process just quits as soon as the memory limit is reached. So that 'invalid JSON response' message had me chasing the wrong goose.
> 
> Given the limitation to display the memory usage, would it be possible to notify me that an OOM error has occurred such that I can debug accordingly?
> 
> Thanks!

Sorry to hear that. I hope that the AWS dev teams would get it together and fix this issue for real soon...

**Comment by jfuss** [comment] 2021-01-05 16:21
@nrg-thom What is your suggestion to solve this problem? The library we are using: https://github.com/aws/aws-lambda-runtime-interface-emulator does not surface information about the memory used by the function. We don't even have a way to access the PID of the process is spawns. Without that, it is unclear how you would even get the memory usage of the function. If you have a way, I am all ears but currently I don't see a way `aws-lambda-rie` can provide that information (the actually software producing the log).

@tazsingh I am going off memory here but wouldn't you see the same thing in Lambda itself if you go over the memory usage? I think the problem you are specifically running into is that it seems you are using `start-api` so the response from lambda is interpreted in specific ways. I would try using `sam local invoke` or `sam local start-lambda` as this should allow you to view the actually response your local function returns. There is probably an improvement here, just unsure what it is.

**Comment by tazsingh** [comment] 2021-01-05 16:26
@jfuss For the original issue, would it be possible to omit that false "Max Memory Used" entirely if it's not possible to make it accurate? At least then it wouldn't be misleading

For my comment, ah ok, I was unaware that AWS Lambda itself didn't provide an OOM error. Thanks for the tip about the various behaviours 👍 Some sort of improvement would certainly be appreciated and I'll inform you if something does come to mind
