### ISSUE TITLE
removing CloudWatchLambdaInsightsExecutionRolePolicy causes an error

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws/aws-sam-cli#2887] opened 2021-05-17 15:00 UTC
### Description:

All I did was remove `CloudWatchLambdaInsightsExecutionRolePolicy` When I tried to deploy, I got this:

```
Waiting for changeset to be created..
Error: Failed to create changeset for the stack: myapp-dev, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.
```

I did not change anything related to `Fn::Join` or `!Join`, simply removed `CloudWatchLambdaInsightsExecutionRolePolicy` from all my functions. Deployment was successful prior to this change, and the error message is not specific.

### Steps to reproduce:

1. Create 10 functions with `CloudWatchLambdaInsightsExecutionRolePolicy` and make some of them have `LambdaInvokePolicy`.
2. Deploy.
3. Remove `CloudWatchLambdaInsightsExecutionRolePolicy`
4. Deploy.

### Observed result:

It results in a vague error.

### Expected result:

Should not even cause an error -- also the error message should be more specific.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux, using Github Actions
2. `sam --version`: SAM CLI, version 1.23.0
3. AWS region: ap-southeast-1

`Add --debug flag to command you are running`

N/A

### EDIT 1:

Adding `--debug` does not help

**Comment by c2tarun** [comment] 2021-10-04 14:53
> Reason: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.

Based on above error it looks like there is some issue with your template. If you are still facing this issue can you please share your template.

**Comment by aprilmintacpineda** [comment] 2021-10-05 03:57
> > Reason: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.
> 
> Based on above error it looks like there is some issue with your template. If you are still facing this issue can you please share your template.

It wasn't the template, I solved this problem by removing the lambda functions from the template, then re-adding them again without the cloud watch lambda insight policy.

**Comment by wchengru** [comment] 2021-11-21 01:07
Close this issue since the problem is resolved, please feel free to reopen it if you have more questions on it.

**Closed by wchengru** 2021-11-21 01:07 UTC
Labels: type/bug, stage/bug-repro, maintainer/need-followup
