### ISSUE TITLE
v1.13.2 breaks when using docker network host for Lambda runtime

### ISSUE THREAD

**Issue by bramkoot** [aws/aws-sam-cli#2468] opened 2020-12-09 16:44 UTC
### Description:

When running sam local invoke (or sam local start-lambda) it complains with 'no response from invoke container'
``` 
Invoking index.handler (nodejs12.x)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-nodejs12.x:rapid-1.13.2.

Mounting /Users/.../dist/foo as /var/task:ro,delegated inside runtime container
No response from invoke container for FooBar
```

This only happens when using the --docker-network host flag, for any other network this does not occur. This also only happens for version 1.13.2. I've managed to install v.1.12.0 (which is a nightmare using brew) and the bug does not present itself.

I've tried it on a Macbook running Catalina (macOS 10.15) and a separate machine running Mojave (macOS 10.14) 

### Steps to reproduce:

Run `sam local invoke --docker-network host SomeFunction` using a Clouformation template. It doesn't get to the actual function code.

### Observed result:
```
2020-12-09 17:40:14,991 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2020-12-09 17:40:15,085 | local invoke command is called
2020-12-09 17:40:15,215 | Unable to resolve property queueName: {'Fn::GetAtt': [‘***’, 'QueueName']}. Leaving as is.
2020-12-09 17:40:15,216 | Unable to resolve property Resource: {'Fn::Sub': ['arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${queueName}', {'queueName': {'Fn::GetAtt': [‘***’, 'QueueName']}}]}. Leaving as is.
2020-12-09 17:40:15,216 | Unable to resolve property queueName: {'Fn::GetAtt': [‘***’, 'QueueName']}. Leaving as is.
2020-12-09 17:40:15,216 | Unable to resolve property Resource: {'Fn::Sub': ['arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${queueName}', {'queueName': {'Fn::GetAtt': [‘****’, 'QueueName']}}]}. Leaving as is.
2020-12-09 17:40:15,216 | Unable to resolve property queueName: {'Fn::GetAtt': [‘***’, 'QueueName']}. Leaving as is.
2020-12-09 17:40:15,216 | Unable to resolve property Resource: {'Fn::Sub': ['arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${queueName}', {'queueName': {'Fn::GetAtt': [‘****’, 'QueueName']}}]}. Leaving as is.
2020-12-09 17:40:15,217 | Unable to resolve property queueName: {'Fn::GetAtt': ['SugarUpdatesQueue', 'QueueName']}. Leaving as is.
2020-12-09 17:40:15,217 | Unable to resolve property Resource: {'Fn::Sub': ['arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${queueName}', {'queueName': {'Fn::GetAtt': [‘****’, 'QueueName']}}]}. Leaving as is.
2020-12-09 17:40:15,218 | Unable to resolve property DNSName: {'Fn::GetAtt': ['CustomDomainName', 'RegionalDomainName']}. Leaving as is.
2020-12-09 17:40:15,218 | Unable to resolve property HostedZoneId: {'Fn::GetAtt': ['CustomDomainName', 'RegionalHostedZoneId']}. Leaving as is.
2020-12-09 17:40:15,218 | 18 resources found in the template
2020-12-09 17:40:15,218 | Found Serverless function with name=‘***’ and CodeUri='./dist/***’
2020-12-09 17:40:15,218 | Found Serverless function with name=‘***’ and CodeUri='./dist/***’
2020-12-09 17:40:15,218 | Found Serverless function with name=‘**’* and CodeUri='./dist/***’
2020-12-09 17:40:15,218 | Found Serverless function with name=‘***’ and CodeUri='./dist/***’
2020-12-09 17:40:15,218 | Found Serverless function with name=‘***’ and CodeUri='./dist/***’
2020-12-09 17:40:15,218 | Found Serverless function with name=‘***’ and CodeUri='./dist/***’
2020-12-09 17:40:15,227 | Found one Lambda function with name ‘***’
2020-12-09 17:40:15,228 | Invoking index.handler (nodejs12.x)
2020-12-09 17:40:15,228 | Environment variables overrides data is standard format
2020-12-09 17:40:15,228 | Loading AWS credentials from session with profile 'None'
2020-12-09 17:40:15,241 | Resolving code path. Cwd=/Users/***/Documents/***, CodeUri=./dist/***
2020-12-09 17:40:15,241 | Resolved absolute path to code is /Users/****
2020-12-09 17:40:15,241 | Code /Users/**** is not a zip/jar file
2020-12-09 17:40:15,267 | Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-nodejs12.x:rapid-1.13.2.

2020-12-09 17:40:15,267 | Mounting /Users/**** as /var/task:ro,delegated inside runtime container
2020-12-09 17:40:15,704 | Starting a timer for 60 seconds for function ‘****’
2020-12-09 17:40:16,840 | No response from invoke container for ****
2020-12-09 17:40:16,841 | Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 1848, 'exitReason': 'success', 'exitCode': 0, 'requestId': ‘***’, 'installationId': '134a598c-3c51-418d-aa48-17d983590691', 'sessionId': ‘***’*, 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.13.2'}}]}
2020-12-09 17:40:17,689 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### Expected result:
Run the Lambda code and show the log output. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS Catalina, also tested on Mojave
2. `sam --version`: v1.13.2

`Add --debug flag to command you are running`

**Comment by jfuss** [comment] 2020-12-10 04:43
@bramkoot From version 1.12 to 1.13, we changed how we communicate with the container. In 1.13, we send an http request to a port the container exposes but in 1.12 we just execute the the container directly. This relates to a change in moving to `aws-lambda-rie` instead of the community built one. I need to do a little deeper digging to see why this could be happening.

Side note: Is there a reason you are using `host`? For Mac and Windows, the host network is the Docker VM not your actually host machine. While this is still a bug, you should be able to freely drop the `--docker-network host` without issues (unless you really want it connected to the Docker VM).

**Comment by jfuss** [comment] 2020-12-10 04:58
This looks to be a duplicate of #2436

**Comment by bramkoot** [comment] 2020-12-10 08:50
Indeed a duplicate, I was confused by the title of that one but the core issue seems to be the same. Probably best to close this one in favour of the older issue #2436. 

> Side note: Is there a reason you are using host? For Mac and Windows, the host network is the Docker VM not your actually host machine. While this is still a bug, you should be able to freely drop the --docker-network host without issues (unless you really want it connected to the Docker VM).

We're using the SAM Lambda runtime to connect to a Postgres database that runs inside the Docker VM as well via Docker compose, and this seems to be the easiest way to get that connection working. 

Side note for anyone who installed AWS CLI via brew and wants to go back to a previous version, here are the steps I took:
* clone the AWS homebrew tab git repo: https://github.com/aws/homebrew-tap
* search in the commits till you find the one that bumps the version of the aws-sam-cli to the version you want, in this case v1.12.0 seems to still work; https://github.com/aws/homebrew-tap/commit/2194a21971bb4898a794e92f17450c6fe53090e4
* checkout the commit locally, and run brew install using the formulae Ruby file: `brew install Formula/aws-sam-cli.rb`

**Comment by jfuss** [comment] 2020-12-10 15:52
@bramkoot I am going to close this in favor of the #2436.

> We're using the SAM Lambda runtime to connect to a Postgres database that runs inside the Docker VM as well via Docker compose, and this seems to be the easiest way to get that connection working.

This makes sense. Thanks for explaining your use case.

**Closed by jfuss** 2020-12-10 15:52 UTC
Labels: area/local/invoke, stage/bug-repro
