### ISSUE TITLE
Process Amazon S3 Events Example not show Trigger in Lambda function

### ISSUE THREAD

**Issue by mikezang** [aws/aws-sam-cli#2228] opened 2020-09-18 16:32 UTC
### Describe your idea/feature/enhancement

I tried [Process Amazon S3 Events](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-example-s3.html), after I run `sam deploy --template-file packaged.yaml --stack-name aws-sam-ocr --capabilities CAPABILITY_IAM`, I can upload a picture and found a record in dynamoDB.

You can there S3 event like this 
![S3Event](https://user-images.githubusercontent.com/1030268/93622288-d56b6b00-fa17-11ea-8b2b-caa8f19c1b86.jpg)

### Proposal
But when open Lambda function in Designer, I found there is no trigger from S3
![LambdaDesigner](https://user-images.githubusercontent.com/1030268/93622026-655ce500-fa17-11ea-97a9-a10014497102.jpg)

I want to know how can I let Lambda function to show S3 trigger in Designer?

**Comment by CoshUS** [comment] 2020-09-18 22:11
@mikezang Can you post your template so we can investigate further into this issue?

**Comment by mikezang** [comment] 2020-09-19 01:03
@CoshUS Here is my template file
> AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM app that uses Rekognition APIs to detect text in S3 Objects and stores labels in DynamoDB.
Resources:
　DetectTextInImage:
　　Type: 'AWS::Serverless::Function'
　　Properties:
　　　Handler: src/app.lambda_handler
　　　Runtime: python3.8
　　　CodeUri: .
　　　Description: Uses Rekognition APIs to detect text in S3 Objects and stores the text and labels in DynamoDB.
　　　MemorySize: 512
　　　Timeout: 30
　　　Environment:
　　　　Variables:
　　　　　TABLE_NAME:
　　　　　　Ref: ResultsTable
　　　Policies:
　　　　- Version: '2012-10-17'
　　　　　Statement:
　　　　　　- Effect: Allow
　　　　　　　Action:
　　　　　　　　- 's3:GetObject'
　　　　　　　Resource: 'arn:aws:s3:::*'
　　　　　　- Effect: Allow
　　　　　　　Action:
　　　　　　　　- 'rekognition:DetectText'
　　　　　　　　- 'rekognition:DetectLabels'
　　　　　　　Resource: '*'
　　　　　　- Effect: Allow
　　　　　　　Action:
　　　　　　　　- 'dynamodb:GetItem'
　　　　　　　　- 'dynamodb:PutItem'
　　　　　　　　- 'dynamodb:Scan'
　　　　　　　　- 'dynamodb:UpdateItem'
　　　　　　　Resource:
　　　　　　　　'Fn::Join':
　　　　　　　　　- ''
　　　　　　　　　- - 'arn:aws:dynamodb:'
　　　　　　　　　　- Ref: 'AWS::Region'
　　　　　　　　　　- ':'
　　　　　　　　　　- Ref: 'AWS::AccountId'
　　　　　　　　　　- ':table/'
　　　　　　　　　　- Ref: ResultsTable
　　　Events:
　　　　BucketEvent1:
　　　　　Type: S3
　　　　　Properties:
　　　　　　Bucket:
　　　　　　　Ref: SourceImageBucket
　　　　　　Events:
　　　　　　　- 's3:ObjectCreated:*'
　SourceImageBucket:
　　Type: 'AWS::S3::Bucket'
　ResultsTable:
　　Type: AWS::Serverless::SimpleTable

**Comment by mikezang** [comment] 2020-09-25 11:40
Is this bug?

**Comment by DobbyH** [comment] 2021-03-29 12:11
Is there an update on this issue? Was it fixed?

**Comment by DobbyH** [comment] 2021-03-29 16:41
This fixed the issue for me: 
https://github.com/aws/serverless-application-model/issues/300#issuecomment-723484023

**Comment by jfuss** [comment] 2022-08-13 02:00
Closing as this is a duplicate of https://github.com/aws/serverless-application-model/issues/300 (which is the correct repo for this issue). There are workarounds provided in the issue already but the cause here stems from what the Lambda Console looks for in generating the triggers and how SAM generates the template.

**Closed by jfuss** 2022-08-13 02:00 UTC
Labels: type/question, maintainer/need-followup
