### ISSUE TITLE
Bug: `local start-api` cannot handle CDK-defined Lambda functions with same name, but different parents

### ISSUE THREAD

**Issue by denisw** [aws/aws-sam-cli#5728] opened 2023-08-07 08:54 UTC
### Description:

When `sam local start-api` mounts Lambda functions from a CloudFormation template synthesized by CDK, a unique ID for each function is generated from the resource's `aws:cdk:path` metadata with the following assumption ([source](https://github.com/aws/aws-sam-cli/blob/cae8e2dbf49c8bda7f87192e4702fbde9e4d92c3/samcli/lib/samlib/resource_metadata_normalizer.py#L252C1-L255C43)):

```python
# aws:cdk:path metadata format of functions: {stack_id}/{function_id}/Resource
# Design doc of CDK path: https://github.com/aws/aws-cdk/blob/master/design/construct-tree.md
```

However, this is only true if the function is defined directly in the stack. If it is nested in another higher-level construct, though, then the `aws:cdk:path` looks like  `{stack_id}/{parent_construct_id}/{function_id}/Resource`, and the `{function_id}` part by itself might not actually be unique. (There might be even more levels of nesting.)

This means that if you have multiple function resources with the same CDK resource name but different parents (e.g. `{stack_id}/Service1/Function` and `{stack_id}/Service2/Function`), `sam local start-api` only mounts the last one that occurs in the template because the others, having the same derived "ID", get overridden.

### Steps to reproduce:

Create the following CDK app:

```ts
import { HttpApi, HttpMethod } from '@aws-cdk/aws-apigatewayv2-alpha';
import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';

const app = new cdk.App();
new ExampleStack(app, 'Stack');

export class ExampleStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: cdk.StackProps) {
    super(scope, id, props);
    
    const api = new HttpApi(this, 'HttpApi', {});
    
    new ExampleService(this, 'FooService', { 
      serviceName: 'foo-service', 
      path: '/foo',
      api 
    });

    new ExampleService(this, 'BarService', { 
      serviceName: 'bar-service', 
      path: '/bar',
      api 
    });
  }
}

type ExampleServiceProps = {
  api: HttpApi;
  serviceName: string;
  path: string;
}

class ExampleService extends Construct {
  constructor(scope: Construct, id: string, props: ExampleServiceProps) {
    super(scope, id);

    const handler = new lambda.Function(this, 'Function', {
      functionName: props.serviceName,
      runtime: lambda.Runtime.NODEJS_18_X,
      handler: 'index.handler',
      code: lambda.Code.fromInline(`
        exports.handler = async function(event) {
          return 'Hello from ${props.serviceName}!';
        }
      `),
    })

    api.addRoutes({
      path: props.path,
      methods: [HttpMethod.GET],
      integration: new HttpLambdaIntegration('AuthIntegration', handler),
    });
  }
}
```

Note that this defines two lambda function resources with the CDK name `Function`, but nested in two differently named parent constructs. The synthesized CloudFormation resources have the follow `aws:cdk:path` metadata values:

* `Stack/Service1/Function/Resource`
* `Stack/Service2/Function/Resource`

Then, run:

```sh
cdk synth Stack
sam local start-api -t cdk.out/Stack.template.json
```

Try invoking both functions' paths:

```sh
curl http://localhost:3000/foo
curl http://localhost:3000/bar
```

### Observed result:

One of the paths returns the expected response, but the other returns:

```sh
{
  "message": "No function defined for resource method"
}
```

The SAM command logs contain a line like:

```
foo-service not found. Possible options in your template: ['Function']
```

### Expected result:

Both endpoints work as expected.

**Comment by jfuss** [comment] 2023-08-07 17:04
Duplicate of https://github.com/aws/aws-sam-cli/issues/4034. Will be updating the title to this one as it's more descriptive. 

We are open to contributions on this, there is a closed PR (can be found in the #4024 issue) that can be used to start from which was abandoned.

**Closed by jfuss** 2023-08-07 17:04 UTC
Labels: stage/needs-triage
