### ISSUE TITLE
macOS Catalina - 'sam' fails with "ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_"

### ISSUE THREAD

**Issue by floydpink** [aws/aws-sam-cli#2229] opened 2020-09-18 17:23 UTC
### Description

After upgrading to macOS Catalina recently, the `sam` command (with any subcommand/option) is failing with this error:

```
➜ sam
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.2.0', 'console_scripts', 'sam')())
  File "/usr/local/bin/sam", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/samcli/cli/main.py", line 10, in <module>
    from samcli.lib.telemetry.metrics import send_installed_metric
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 11, in <module>
    from samcli.cli.context import Context
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/samcli/cli/context.py", line 8, in <module>
    import boto3
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 30, in <module>
    import botocore.credentials
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/awsrequest.py", line 25, in <module>
    import botocore.utils
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/urllib3/util/ssl_.py)
```

### Steps to reproduce

* Run `sam` command

I use `pyenv` to switch between different Python versions, HomeBrew to install aws-sam-cli and use `zsh`.

Here are some relevant version numbers:

OS: macOS Catalina (10.15.6)

```
➜ python --version
Python 3.8.5
```

```
➜ pip --version
pip 20.2.3 from ~/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip (python 3.8)
```

```
➜ pyenv --version
pyenv 1.2.20
```

### Observed result

Output for `sam --debug`:

```
➜ sam --debug
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.2.0', 'console_scripts', 'sam')())
  File "/usr/local/bin/sam", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/samcli/cli/main.py", line 10, in <module>
    from samcli.lib.telemetry.metrics import send_installed_metric
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 11, in <module>
    from samcli.cli.context import Context
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/samcli/cli/context.py", line 8, in <module>
    import boto3
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 30, in <module>
    import botocore.credentials
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/awsrequest.py", line 25, in <module>
    import botocore.utils
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/urllib3/util/ssl_.py)
```

### Expected result

`sam` command will work and print the help.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS
2. `sam --version`: 1.2.0 (`sam --version` is also not working, found version number via `brew info `aws-sam-cli`)

**Comment by CoshUS** [comment] 2020-09-18 22:28
This seems like an issue with SSL and Catalina. [Related link](https://discuss.streamlit.io/t/importerror-cannot-import-name-ssl-from-urllib3-util-ssl-usr-local-lib-python3-7-site-packages-urllib3-util-ssl-py/4139).

**Comment by aahung** [comment] 2021-09-12 23:51
The issue is pretty old and [awscli also had a similar issue that was resolved by re-installing](https://stackoverflow.com/questions/54217137/from-urllib3-util-ssl-import-importerror-cannot-import-name-ssl). Considering the issue didn't get any `+1`s, I am closing it. Please open a new issue if anyone still encountered such issue.

**Closed by aahung** 2021-09-12 23:51 UTC
Labels: area/installation
