### ISSUE TITLE
Docker repo used by samcli seems to be having troubles

### ISSUE THREAD

**Issue by codek** [aws/aws-sam-cli#3773] opened 2022-03-24 14:42 UTC
Getting this error from a github workflow

We thought it had gone away earlier, but it's just come back.

I just re-ran *again* and it worked - so it's definitely not an issue my end.

Traceback (most recent call last):
  File "/home/runner/work/_temp/setup-sam-eRVrkY/.venv/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/runner/work/_temp/setup-sam-eRVrkY/.venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/images/create?tag=latest-x86_64&fromImage=[http://public.ecr.aws](https://t.co/ohkxipPahz)%2Fsam%2Fbuild-python3.8%3Alatest-x86_64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/_temp/setup-sam-eRVrkY/.venv/lib/python3.8/site-packages/samcli/local/docker/manager.py", line 160, in pull_image
    result_itr = self.docker_client.api.pull(image_name, tag=tag, stream=True, decode=True)
  File "/home/runner/work/_temp/setup-sam-eRVrkY/.venv/lib/python3.8/site-packages/docker/api/image.py", line 415, in pull
    self._raise_for_status(response)
  File "/home/runner/work/_temp/setup-sam-eRVrkY/.venv/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/runner/work/_temp/setup-sam-eRVrkY/.venv/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Get "[https://public.ecr.aws/v2/](https://t.co/rk31yjZObZ)": net/http: TLS handshake timeout")

**Comment by mildaniel** [comment] 2022-03-24 20:22
Thanks for reporting the issue, we will be investigating it further. Please watch this channel for more updates, and feel free to reach out.

**Comment by mndeveci** [comment] 2022-07-07 16:52
This error is coming from Public ECR endpoint, SAM CLI just calls docker engine to pull certain images for `sam build` or `sam local` commands. There is not much we can do to stop this happening.

What you could try is to adjust the docker daemon settings which might help you to resolve this issue. Some of the configurations that might help you is;
```
      --max-concurrent-downloads int          Set the max concurrent downloads for each pull (default 3)
      --max-download-attempts int             Set the max download attempts for each pull (default 5)
```

Looking at the documentation of these parameters, lower `--max-concurrent-downloads` might help if the number of connections is creating this issue. Or you can also try higher `--max-download-attempts` since it seems like how many times it will re-try before it fails to download an image.

Details: https://docs.docker.com/engine/reference/commandline/dockerd/

**Comment by sriram-mv** [comment] 2022-10-05 17:49
I'm going to close this issue, since its not directly a AWS SAM CLI issue. @mndeveci has outlined workarounds on this.

**Closed by sriram-mv** 2022-10-05 17:49 UTC
Labels: blocked/more-info-needed

**Comment by andrzejsliwa** [comment] 2023-02-11 20:26
```
andrzejsliwa@NUC:~/sam-app$ sam local invoke
Invoking app.lambda_handler (python3.9)

Error: 500 Server Error: Internal Server Error ("Head "https://public.ecr.aws/v2/lambda/python/manifests/3.9-x86_64": Get "https://public.ecr.aws/token/?scope=repository%3Alambda%2Fpython%3Apull&service=public.ecr.aws": dial tcp 75.2.101.78:443: i/o timeout")
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 183, in wrapped
  File "samcli/lib/telemetry/metric.py", line 150, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 92, in wrapper
  File "samcli/commands/local/invoke/cli.py", line 116, in cli
  File "samcli/commands/local/invoke/cli.py", line 202, in do_cli
  File "samcli/commands/local/lib/local_lambda.py", line 144, in invoke
  File "samcli/lib/telemetry/metric.py", line 323, in wrapped_func
  File "samcli/local/lambdafn/runtime.py", line 188, in invoke
  File "samcli/local/lambdafn/runtime.py", line 99, in create
  File "samcli/local/docker/lambda_container.py", line 94, in __init__
  File "samcli/local/docker/lambda_container.py", line 236, in _get_image
  File "samcli/local/docker/lambda_image.py", line 192, in build
  File "samcli/local/docker/lambda_image.py", line 452, in _check_base_image_is_current
  File "samcli/local/docker/lambda_image.py", line 476, in is_base_image_current
  File "samcli/local/docker/lambda_image.py", line 492, in get_remote_image_digest
  File "docker/models/images.py", line 337, in get_registry_data
  File "docker/utils/decorators.py", line 34, in wrapper
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/image.py", line 282, in inspect_distribution
  File "docker/api/client.py", line 267, in _result
  File "docker/api/client.py", line 263, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception

An unexpected error was encountered while executing "sam local invoke".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20local%20invoke%20-%20APIError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20local%20invoke%20-%20APIError
andrzejsliwa@NUC:~/sam-app$ sam local invoke
Invoking app.lambda_handler (python3.9)
Local image is up-to-date
Using local image: public.ecr.aws/lambda/python:3.9-rapid-x86_64.

Mounting /home/andrzejsliwa/sam-app/hello_world as /var/task:ro,delegated inside runtime container
START RequestId: ca8c7261-cbfa-4f97-90f7-bf84fc5fcc8d Version: $LATEST
{"statusCode": 200, "body": "{\"message\": \"hello world\"}"}END RequestId: ca8c7261-cbfa-4f97-90f7-bf84fc5fcc8d
REPORT RequestId: ca8c7261-cbfa-4f97-90f7-bf84fc5fcc8d  Init Duration: 0.14 ms  Duration: 82.57 ms      Billed Duration: 83 ms  Memory Size: 128 MB    Max Memory Used: 128 MB

andrzejsliwa@NUC:~/sam-app$ sam local invoke
Invoking app.lambda_handler (python3.9)

Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 183, in wrapped
  File "samcli/lib/telemetry/metric.py", line 150, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 92, in wrapper
  File "samcli/commands/local/invoke/cli.py", line 116, in cli
  File "samcli/commands/local/invoke/cli.py", line 202, in do_cli
  File "samcli/commands/local/lib/local_lambda.py", line 144, in invoke
  File "samcli/lib/telemetry/metric.py", line 323, in wrapped_func
  File "samcli/local/lambdafn/runtime.py", line 188, in invoke
  File "samcli/local/lambdafn/runtime.py", line 99, in create
  File "samcli/local/docker/lambda_container.py", line 94, in __init__
  File "samcli/local/docker/lambda_container.py", line 236, in _get_image
  File "samcli/local/docker/lambda_image.py", line 192, in build
  File "samcli/local/docker/lambda_image.py", line 452, in _check_base_image_is_current
  File "samcli/local/docker/lambda_image.py", line 476, in is_base_image_current
  File "samcli/local/docker/lambda_image.py", line 492, in get_remote_image_digest
  File "docker/models/images.py", line 337, in get_registry_data
  File "docker/utils/decorators.py", line 34, in wrapper
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/image.py", line 282, in inspect_distribution
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 230, in _get
  File "requests/sessions.py", line 555, in get
  File "requests/sessions.py", line 542, in request
  File "requests/sessions.py", line 655, in send
  File "requests/adapters.py", line 498, in send

An unexpected error was encountered while executing "sam local invoke".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20local%20invoke%20-%20ConnectionError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20local%20invoke%20-%20ConnectionError
```

Ok, two points from my side:

1. yes, the problem is with public.ecr.aws, but for sake, it's owned by AWS! (or I'm wrong?, what is the failure rate on this endpoint, why no body is taking care for scaling it up properly?)
Changing max-conncurrent/download isn't helping a lot. 

2. why, if the docker image is already downloaded ONCE, it's checking for a new version on every invoke?

**Comment by andrzejsliwa** [comment] 2023-02-11 20:33
btw this looks like problem is with your telemetry?!?
`andrzejsliwa@NUC:~/sam-app$ sam local invoke --debug
2023-02-11 21:31:40,409 | Config file location: /home/andrzejsliwa/sam-app/samconfig.toml
2023-02-11 21:31:40,409 | Config file '/home/andrzejsliwa/sam-app/samconfig.toml' does not exist
2023-02-11 21:31:40,413 | Using SAM Template at /home/andrzejsliwa/sam-app/template.yaml
2023-02-11 21:31:40,431 | Using config file: samconfig.toml, config environment: default
2023-02-11 21:31:40,431 | Expand command line arguments to:
2023-02-11 21:31:40,431 | --template_file=/home/andrzejsliwa/sam-app/template.yaml --no_event --layer_cache_basedir=/home/andrzejsliwa/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2023-02-11 21:31:40,431 | local invoke command is called
2023-02-11 21:31:40,436 | No Parameters detected in the template
2023-02-11 21:31:40,446 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-02-11 21:31:40,446 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-02-11 21:31:40,448 | 0 stacks found in the template
2023-02-11 21:31:40,448 | No Parameters detected in the template
2023-02-11 21:31:40,457 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-02-11 21:31:40,457 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-02-11 21:31:40,457 | 2 resources found in the stack 
2023-02-11 21:31:40,457 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2023-02-11 21:31:40,457 | --base-dir is not presented, adjusting uri hello_world/ relative to /home/andrzejsliwa/sam-app/template.yaml
2023-02-11 21:31:40,462 | Found one Lambda function with name 'HelloWorldFunction'
2023-02-11 21:31:40,462 | Invoking app.lambda_handler (python3.9)
2023-02-11 21:31:40,462 | No environment variables found for function 'HelloWorldFunction'
2023-02-11 21:31:40,462 | Loading AWS credentials from session with profile 'None'
2023-02-11 21:31:40,471 | Resolving code path. Cwd=/home/andrzejsliwa/sam-app, CodeUri=/home/andrzejsliwa/sam-app/hello_world
2023-02-11 21:31:40,471 | Resolved absolute path to code is /home/andrzejsliwa/sam-app/hello_world
2023-02-11 21:31:40,471 | Code /home/andrzejsliwa/sam-app/hello_world is not a zip/jar file
2023-02-11 21:32:40,526 | Cleaning all decompressed code dirs
2023-02-11 21:32:40,527 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-02-11 21:32:40,542 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '969b80e8-b4a6-4286-a2ea-c43a02476ff2', 'installationId': '9437d767-0f16-4051-8b79-651824194adc', 'sessionId': '2e55b400-ade2-4fdb-9166-ff403c87ec29', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.72.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3', 'initialCommit': None}, 'duration': 60096, 'exitReason': 'ReadTimeout', 'exitCode': 255}}]}
2023-02-11 21:32:42,084 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

Error: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 183, in wrapped
  File "samcli/lib/telemetry/metric.py", line 150, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 92, in wrapper
  File "samcli/commands/local/invoke/cli.py", line 116, in cli
  File "samcli/commands/local/invoke/cli.py", line 202, in do_cli
  File "samcli/commands/local/lib/local_lambda.py", line 144, in invoke
  File "samcli/lib/telemetry/metric.py", line 323, in wrapped_func
  File "samcli/local/lambdafn/runtime.py", line 188, in invoke
  File "samcli/local/lambdafn/runtime.py", line 99, in create
  File "samcli/local/docker/lambda_container.py", line 94, in __init__
  File "samcli/local/docker/lambda_container.py", line 236, in _get_image
  File "samcli/local/docker/lambda_image.py", line 192, in build
  File "samcli/local/docker/lambda_image.py", line 452, in _check_base_image_is_current
  File "samcli/local/docker/lambda_image.py", line 476, in is_base_image_current
  File "samcli/local/docker/lambda_image.py", line 492, in get_remote_image_digest
  File "docker/models/images.py", line 337, in get_registry_data
  File "docker/utils/decorators.py", line 34, in wrapper
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/image.py", line 282, in inspect_distribution
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 230, in _get
  File "requests/sessions.py", line 555, in get
  File "requests/sessions.py", line 542, in request
  File "requests/sessions.py", line 655, in send
  File "requests/adapters.py", line 529, in send`

**Comment by andrzejsliwa** [comment] 2023-02-11 20:36
```
andrzejsliwa@NUC:~/sam-app$ sam local invoke --debug
2023-02-11 21:34:41,983 | Config file location: /home/andrzejsliwa/sam-app/samconfig.toml
2023-02-11 21:34:41,983 | Config file '/home/andrzejsliwa/sam-app/samconfig.toml' does not exist
2023-02-11 21:34:41,988 | Using SAM Template at /home/andrzejsliwa/sam-app/template.yaml
2023-02-11 21:34:42,008 | Using config file: samconfig.toml, config environment: default
2023-02-11 21:34:42,008 | Expand command line arguments to:
2023-02-11 21:34:42,008 | --template_file=/home/andrzejsliwa/sam-app/template.yaml --no_event --layer_cache_basedir=/home/andrzejsliwa/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2023-02-11 21:34:42,008 | local invoke command is called
2023-02-11 21:34:42,012 | No Parameters detected in the template
2023-02-11 21:34:42,023 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-02-11 21:34:42,023 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-02-11 21:34:42,023 | 0 stacks found in the template
2023-02-11 21:34:42,024 | No Parameters detected in the template
2023-02-11 21:34:42,033 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-02-11 21:34:42,033 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-02-11 21:34:42,034 | 2 resources found in the stack 
2023-02-11 21:34:42,034 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2023-02-11 21:34:42,034 | --base-dir is not presented, adjusting uri hello_world/ relative to /home/andrzejsliwa/sam-app/template.yaml
2023-02-11 21:34:42,040 | Found one Lambda function with name 'HelloWorldFunction'
2023-02-11 21:34:42,040 | Invoking app.lambda_handler (python3.9)
2023-02-11 21:34:42,040 | No environment variables found for function 'HelloWorldFunction'
2023-02-11 21:34:42,040 | Loading AWS credentials from session with profile 'None'
2023-02-11 21:34:42,048 | Resolving code path. Cwd=/home/andrzejsliwa/sam-app, CodeUri=/home/andrzejsliwa/sam-app/hello_world
2023-02-11 21:34:42,048 | Resolved absolute path to code is /home/andrzejsliwa/sam-app/hello_world
2023-02-11 21:34:42,048 | Code /home/andrzejsliwa/sam-app/hello_world is not a zip/jar file
2023-02-11 21:35:37,275 | Local image is up-to-date
2023-02-11 21:35:37,285 | Using local image: public.ecr.aws/lambda/python:3.9-rapid-x86_64.

2023-02-11 21:35:37,285 | Mounting /home/andrzejsliwa/sam-app/hello_world as /var/task:ro,delegated inside runtime container
2023-02-11 21:35:37,721 | Starting a timer for 3 seconds for function 'HelloWorldFunction'
START RequestId: a0b61ab4-4367-49f1-bf03-28ab67ffcc30 Version: $LATEST
{"statusCode": 200, "body": "{\"message\": \"hello world\"}"}END RequestId: a0b61ab4-4367-49f1-bf03-28ab67ffcc30
REPORT RequestId: a0b61ab4-4367-49f1-bf03-28ab67ffcc30  Init Duration: 0.07 ms  Duration: 48.04 ms      Billed Duration: 49 ms  Memory Size: 128 MB    Max Memory Used: 128 MB
2023-02-11 21:35:38,298 | Cleaning all decompressed code dirs
2023-02-11 21:35:38,298 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-02-11 21:35:38,309 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '608b3faa-3aea-4802-b397-f60c36ca9f43', 'installationId': '9437d767-0f16-4051-8b79-651824194adc', 'sessionId': 'ec1f1699-3030-48cf-b47d-59390f4e65f8', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.72.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3', 'initialCommit': None}, 'duration': 56290, 'exitReason': 'success', 'exitCode': 0}}]}
2023-02-11 21:35:39,170 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2023-02-11 21:35:39,170 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-02-11 21:35:39,171 | Sending Telemetry: {'metrics': [{'runtimeMetric': {'requestId': '3bedf52d-2a34-451e-ae38-aadf1135d100', 'installationId': '9437d767-0f16-4051-8b79-651824194adc', 'sessionId': 'ec1f1699-3030-48cf-b47d-59390f4e65f8', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.72.0', 'runtimes': ['python3.9']}}]}
2023-02-11 21:35:39,973 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

**Comment by andrzejsliwa** [comment] 2023-02-11 20:47
Skipping pull is working.

```
andrzejsliwa@NUC:~/sam-app$ sam local invoke --skip-pull-image
Invoking app.lambda_handler (python3.9)
Requested to skip pulling images ...

Mounting /home/andrzejsliwa/sam-app/hello_world as /var/task:ro,delegated inside runtime container
START RequestId: 3011b1f9-2cc6-462d-a019-6dbe6b05137a Version: $LATEST
END RequestId: 3011b1f9-2cc6-462d-a019-6dbe6b05137a
{"statusCode": 200, "body": "{\"message\": \"hello world\"}"}REPORT RequestId: 3011b1f9-2cc6-462d-a019-6dbe6b05137a     Init Duration: 0.12 ms  Duration: 45.45 ms      Billed Duration: 46 ms  Memory Size: 128 MB     Max Memory Used: 128 M
```
