### ISSUE TITLE
sam build --use-container not working correctly with v1.0.0 

### ISSUE THREAD

**Issue by ORDEP81** [aws/aws-sam-cli#2133] opened 2020-07-25 22:03 UTC
### Description

While trying to run `sam build --use-container` I get the following error. 
`Build Failed Error: Docker is unreachable. Docker needs to be running to build inside a container.` even though docker is installed and running. It breaks when trying to build the Function. If you introduce a typo to the end of `Type:AWS::Serverless::Functionc` this works for some reason and the get the "Build Succeeded" message. Once you deploy then you come across error `Unresolved resource dependencies [ServerlessRestApi] in the Outputs block of the template`
this is fixed by placing the full path to the functions folder in the .aws-sam/build template.yaml file. This file also contains other errors and the typo for the function at this point will also have to be corrected.
```
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8

```
### Steps to reproduce
`sam build --use-container` with the following teamplate.yaml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'test'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        test:
          Type: Api
          Properties:
            Path: /hello
            Method: get
Outputs:
  testApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

```

### Observed result
`Build Failed Error: Docker is unreachable. Docker needs to be running to build inside a container.` 

### Expected result

Describe what you expected.
"Build Succeeded"
### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18/04
2. `sam --version`: SAM CLI version 1.0.0

`Add --debug flag to command you are running`

**Comment by what-name** [comment] 2020-07-25 22:20
Can confirm that the template works on my end with `SAM CLI V0.53`, can build with `sam build --use-container` and can be deployed with `sam deploy -g` no problem. Missing space here in the `CodeUri:Lambda` property but it works (I tested it with him beforehand).

**Comment by mndeveci** [comment] 2020-08-05 00:06
Hi @ORDEP81,

Thanks for reporting this issue. I try to reproduce it on a linux machine, and I found out that using an older docker might be the root cause. 

My docker version;
```
$ docker version
Client:
 Version:      1.12.6
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Thu Jan 26 09:26:48 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Thu Jan 26 09:26:48 2017
 OS/Arch:      linux/amd64
```

And running build command using container fails;
```
$ samdev build -u --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
3 resources found in the template
Found Serverless function with name='TestFunction' and CodeUri='Lambda/'
No Parameters detected in the template
Building function 'TestFunction'
Docker is not reachable
Traceback (most recent call last):
  File "/home/deveci/.pyenv/versions/3.7.2/envs/samcli37/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/deveci/.pyenv/versions/3.7.2/envs/samcli37/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://127.0.0.1:2376/v1.35/_ping

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/home/deveci/workplace/aws/sam/aws-sam-cli/samcli/local/docker/manager.py", line 47, in is_docker_reachable
    self.docker_client.ping()
  File "/home/deveci/.pyenv/versions/3.7.2/envs/samcli37/lib/python3.7/site-packages/docker/client.py", line 187, in ping
    return self.api.ping(*args, **kwargs)
  File "/home/deveci/.pyenv/versions/3.7.2/envs/samcli37/lib/python3.7/site-packages/docker/api/daemon.py", line 166, in ping
    return self._result(self._get(self._url('/_ping'))) == 'OK'
  File "/home/deveci/.pyenv/versions/3.7.2/envs/samcli37/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/deveci/.pyenv/versions/3.7.2/envs/samcli37/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/deveci/.pyenv/versions/3.7.2/envs/samcli37/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.35, server API version: 1.24)")

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'samdev build', 'duration': 53, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1, 'requestId': 'cdd959ab-ded7-4895-ba7e-63260d8b1208', 'installationId': 'a2b32ab6-547d-4778-af33-3599b0daac6b', 'sessionId': '3ba084a5-7a06-4db7-9d1f-0de269596518', 'executionEnvironment': 'CLI', 'pyversion': '3.7.2', 'samcliVersion': '1.0.0'}}]}
Telemetry response: 200
Error: Docker is unreachable. Docker needs to be running to build inside a container.
```

As you can see the following line, it is failing due to older version of docker; 
`docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.35, server API version: 1.24)")`

After updating my docker the issue has been fixed.

Can you run your build with `--debug` parameter (`samdev build -u --debug`) to see if it is failing with same issue?
And if it is, can you upgrade your docker installation to verify it is working?

Thanks!

**Comment by CoshUS** [comment] 2020-11-28 01:18
Closing.
Feel free to reopen is there is further information or issue.

**Closed by CoshUS** 2020-11-28 01:18 UTC
Labels: area/build, area/docker, stage/more-info-needed
