### ISSUE TITLE
Locally Invoking Lambda function on Apple M1 - Strange Behaviour

### ISSUE THREAD

**Issue by SaifAbrahimSaleem** [aws/aws-sam-cli#3389] opened 2021-10-22 15:17 UTC
### **Description:**
I am trying to locally invoke a Lambda function which uses a HuggingFace Summarization model (ref: https://huggingface.co/sshleifer/distilbart-cnn-6-6).

### Expected Result:
Once the Lambda is locally invoked, it should ideally execute the lambda code.

### Observed Result:
I am able to invoke `sam build`, however, when I locally invoke the Lambda function, I observe the following issue: 
![image](https://user-images.githubusercontent.com/37380757/138479610-345622b1-d0a3-4009-9afc-6ea798a86866.png)

### Steps to Reproduce: 
1. Create a YAML template file which declares the Lambda PackageType as an Image.
2. Create a DockerFile similar to: 
![image](https://user-images.githubusercontent.com/37380757/138478903-6d775b47-9aea-4187-9e3f-5ee8f20c306e.png)
3. Locally invoke the Lambda function.

### Environment Details: 
- OS: MacOS - Big Sur (v11.4)
- Chip: Apple M1
- AWS SAM CLI Version: 1.33.0
- AWS Region: eu-west-2

I have tried many fixes such as clean installing Docker (https://docs.docker.com/desktop/mac/apple-silicon/) and AWS SAM CLI (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html), using previous versions of both, pruning images and so on.

Is there anything I am overlooking/missing?

**Comment by jtlz2** [comment] 2022-03-15 06:47
@SaifAbrahimSaleem Hi - is there any chance of an update on this? It's still an issue for me :(

**Comment by LoganArnett** [comment] 2022-05-05 17:06
Update on my previous comment, I was able to get this working on my M1 laptop for a day and then when coming back the next morning and running it I get the same result of `Invalid lambda response` with no changes to what was working

**Comment by sebelga** [comment] 2022-09-15 18:24
I am also facing some issue on my local machine with M1. It exits the function with the following error:

```
Invalid lambda response received: Lambda response must be valid json
```

I am still investigating but it _seems_ it is happening right when I use the `scrypt` function from the `node:crypto` native module.

**Comment by lucashuy** [comment] 2022-09-15 21:30
Hi @SaifAbrahimSaleem, I am unable to reproduce this on my M1 machine by invoking a hello world handler inside the Docker container you provided. Is there a specific dependency that is causing this behaviour you experienced?

**Comment by sebelga** [comment] 2022-09-16 13:47
Sorry for the noise, it was a silly mistake on my side. Once I set the `Architectures` to `arm64` in my `template.yaml` it got fixed.

**Comment by sriram-mv** [comment] 2022-09-27 18:19
Once I switched to below config

```
Architectures:
   - arm64
```

on a M1 mac.

build and local invokes just work. I'm going to close this issue out, if this does not solve it. please comment here and we can look at reopening and investigating.

**Closed by sriram-mv** 2022-09-27 18:19 UTC
Labels: blocked/more-info-needed, area/local/invoke, stage/bug-repro, maintainer/need-followup, platform/mac/arm

**Comment by nickgrealy** [comment] 2023-01-23 23:38
Just to elaborate more on @sriram-mv 's answer (thank you!)

```yaml
Resources:
    yourFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: src/handlers/get-all-items.getAllItemsHandler
        Runtime: nodejs18.x
        Architectures:
          # NOTE alternate these to match your target CPU Architecture! 
          # - x86_64
          - arm64
```

**Comment by HWiese1980** [comment] 2023-02-14 08:58
> Just to elaborate more on @sriram-mv 's answer (thank you!). The fix is to use `arm64` in your architecture like so:
> 
> ```yaml
> Resources:
>     yourFunction:
>       Type: AWS::Serverless::Function
>       Properties:
>         Handler: src/handlers/get-all-items.getAllItemsHandler
>         Runtime: nodejs18.x
>         Architectures:
>           # NOTE alternate these to match your target CPU Architecture! 
>           # - x86_64
>           - arm64
> ```
> 
> Problem:
> 
> I was getting `Failed to build Docker Image` when running `sam local start-api` and invoking my http endpoint ...
> 
> ```
> samcli.commands.local.cli_common.user_exceptions.ImageBuildException: Error building docker image: The command '/bin/sh -c mv /var/rapid/aws-lambda-rie-x86_64 /var/rapid/aws-lambda-rie && chmod +x /var/rapid/aws-lambda-rie' returned a non-zero code: 1
> ```

I'm seeing the exact same error right now. Is there a solution for this already?

I've tried setting `Architectures` underneath each function entry explicitly and also under `Globals/Functions`, but no success so far. The error persists.

**Comment by HWiese1980** [comment] 2023-02-14 09:05
Okay, I think I've found it. 

1. in the template file there was still the `Architectures:` entry for x86_64 as mentioned in the quote above. 
2. replacing that with `arm64` and subsequently executing 
```bash
docker system prune  # careful with this one
docker rmi 96bb0a677e84  # or whatever the digest of your local `public.ecr.aws/lambda/...` image is
sam build
```
finally worked and let me invoke the function locally.
