### ISSUE TITLE
`sam publish` fails on CreateApplication when the template has 'Custom' resource lambda

### ISSUE THREAD

**Issue by pratik-gdb** [aws/aws-sam-cli#955] opened 2019-01-23 09:13 UTC
### Description

I have a custom resource which runs a lambda. I am able to package it and deploy it. But when I try to publish the application I am getting an error - unsupported resource types. [Custom::InitFunctionLambda]

### Observed result
Publish Failed
Traceback (most recent call last):
  File "/home/pratik/workspace/dvsa/.venv/bin/sam", line 11, in <module>
    sys.exit(cli())
  File "/home/pratik/workspace/dvsa/.venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pratik/workspace/dvsa/.venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pratik/workspace/dvsa/.venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pratik/workspace/dvsa/.venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pratik/workspace/dvsa/.venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pratik/workspace/dvsa/.venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/pratik/workspace/dvsa/.venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pratik/workspace/dvsa/.venv/lib/python2.7/site-packages/samcli/commands/publish/command.py", line 44, in cli
    do_cli(ctx, template)  # pragma: no cover
  File "/home/pratik/workspace/dvsa/.venv/lib/python2.7/site-packages/samcli/commands/publish/command.py", line 64, in do_cli
    raise _wrap_s3_uri_exception(ex)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateApplication operation: The template contains unsupported resource types. [Custom::InitFunctionLambda]

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 16.04
2. `sam --version`: SAM CLI, version 0.10.0

`Add --debug flag to command you are running`

**Comment by alexzelenuyk** [comment] 2019-01-26 22:22
I have the same issue. I'm able to deploy stack but on publishing i get the following error:
```
botocore.errorfactory.BadRequestException: 
An error occurred (BadRequestException) when calling the CreateApplication operation: 
The template contains unsupported resource types. 
[AWS::SES::ReceiptRule, AWS::SES::ReceiptRuleSet]
```
Version:
```
SAM CLI, version 0.10.0
```

My template is [here](https://github.com/alexzelenuyk/forward-invoice-to-s3/blob/master/sam/template.yaml)

**Comment by robzolkos** [comment] 2019-04-01 01:26
@alexzelenuyk try running the stack in a region that supports SES (us-east-1, eu-west-1 or us-west-2).   I had the same issue until I realized the Sydney doesn't have SES 😂

**Comment by jfuss** [comment] 2019-06-15 01:48
This is a restriction on SAR (Serverless Application Repo) itself. You can find a list of all supported SAR Resources [here](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/list-supported-resources.html). 

This is working as intended but we should output a better error message instead of showing a stack trace.

**Comment by jfuss** [comment] 2023-02-06 21:19
Closing Due to age. Please poen a new issue if something is still off.

**Closed by jfuss** 2023-02-06 21:19 UTC
Labels: type/ux, area/publish
