### ISSUE TITLE
Bug: 500 Server Error on dialing public.ecr.aws:443

### ISSUE THREAD

**Issue by andrzejsliwa** [aws/aws-sam-cli#4702] opened 2023-02-13 12:22 UTC
### Description:
500 Server Error on dialing public.ecr.aws:443

### Steps to reproduce:
[~/sam-app]$ sam local invoke                                                             

### Observed result:

Invoking app.lambda_handler (python3.9)

Error: 500 Server Error: Internal Server Error ("Head "https://public.ecr.aws/v2/lambda/python/manifests/3.9-x86_64": Get "https://public.ecr.aws/token/?scope=repository%3Alambda%2Fpython%3Apull&service=public.ecr.aws": dialing public.ecr.aws:443 static system has no HTTPS proxy: connecting to 99.83.145.10:443: dial tcp 99.83.145.10:443: i/o timeout")

### Expected result:

Executing function locally.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOSX Ventura 13.1
2. `sam --version`: SAM CLI, version 1.73.0
3. AWS region: local

```
# Paste the output of `sam --info` here
[~/sam-app]$ sam --info                                                                   rvm:ruby-3.1.2
{
  "version": "1.73.0",
  "system": {
    "python": "3.11.1",
    "os": "macOS-13.1-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.22",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

`Add --debug flag to command you are running`
```
[~/sam-app]$ sam local invoke --debug                                                     rvm:ruby-3.1.2
2023-02-13 13:21:03,756 | Config file location: /Users/andrzejsliwa/sam-app/samconfig.toml
2023-02-13 13:21:03,756 | Config file '/Users/andrzejsliwa/sam-app/samconfig.toml' does not exist
2023-02-13 13:21:03,763 | Using SAM Template at /Users/andrzejsliwa/sam-app/template.yaml
2023-02-13 13:21:03,793 | Using config file: samconfig.toml, config environment: default
2023-02-13 13:21:03,793 | Expand command line arguments to:
2023-02-13 13:21:03,793 | --template_file=/Users/andrzejsliwa/sam-app/template.yaml --no_event --layer_cache_basedir=/Users/andrzejsliwa/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1
2023-02-13 13:21:03,793 | local invoke command is called
2023-02-13 13:21:03,799 | No Parameters detected in the template
2023-02-13 13:21:03,829 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-02-13 13:21:03,829 | There is no customer defined id or cdk path defined for resource ApplicationResourceGroup, so we will use the resource logical id as the resource id
2023-02-13 13:21:03,829 | There is no customer defined id or cdk path defined for resource ApplicationInsightsMonitoring, so we will use the resource logical id as the resource id
2023-02-13 13:21:03,829 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-02-13 13:21:03,830 | 0 stacks found in the template
2023-02-13 13:21:03,830 | No Parameters detected in the template
2023-02-13 13:21:03,843 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-02-13 13:21:03,843 | There is no customer defined id or cdk path defined for resource ApplicationResourceGroup, so we will use the resource logical id as the resource id
2023-02-13 13:21:03,844 | There is no customer defined id or cdk path defined for resource ApplicationInsightsMonitoring, so we will use the resource logical id as the resource id
2023-02-13 13:21:03,844 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-02-13 13:21:03,844 | 4 resources found in the stack
2023-02-13 13:21:03,844 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2023-02-13 13:21:03,844 | --base-dir is not presented, adjusting uri hello_world/ relative to /Users/andrzejsliwa/sam-app/template.yaml
2023-02-13 13:21:03,856 | Found one Lambda function with name 'HelloWorldFunction'
2023-02-13 13:21:03,856 | Invoking app.lambda_handler (python3.9)
2023-02-13 13:21:03,856 | No environment variables found for function 'HelloWorldFunction'
2023-02-13 13:21:03,856 | Loading AWS credentials from session with profile 'None'
2023-02-13 13:21:05,871 | Resolving code path. Cwd=/Users/andrzejsliwa/sam-app, CodeUri=/Users/andrzejsliwa/sam-app/hello_world
2023-02-13 13:21:05,871 | Resolved absolute path to code is /Users/andrzejsliwa/sam-app/hello_world
2023-02-13 13:21:05,871 | Code /Users/andrzejsliwa/sam-app/hello_world is not a zip/jar file
2023-02-13 13:21:13,168 | Cleaning all decompressed code dirs
2023-02-13 13:21:13,169 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-02-13 13:21:13,228 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'd5dcaec2-7232-45cd-bdc7-a38f5c9077a6', 'installationId': '775f10e1-51ee-484c-b8eb-440dc0697ce8', 'sessionId': '33857acb-0789-4aad-9944-368ea1ba2bcd', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.11.1', 'samcliVersion': '1.73.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3', 'initialCommit': None}, 'duration': 9376, 'exitReason': 'APIError', 'exitCode': 255}}]}
2023-02-13 13:21:13,974 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

Error: 500 Server Error: Internal Server Error ("Head "https://public.ecr.aws/v2/lambda/python/manifests/3.9-x86_64": Get "https://public.ecr.aws/token/?scope=repository%3Alambda%2Fpython%3Apull&service=public.ecr.aws": dialing public.ecr.aws:443 static system has no HTTPS proxy: connecting to 99.83.145.10:443: dial tcp 99.83.145.10:443: i/o timeout")
Traceback:
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/lib/telemetry/metric.py", line 183, in wrapped
    raise exception  # pylint: disable=raising-bad-type
    ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/lib/telemetry/metric.py", line 150, in wrapped
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/cli/main.py", line 92, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/commands/local/invoke/cli.py", line 94, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/commands/local/invoke/cli.py", line 201, in do_cli
    context.local_lambda_runner.invoke(
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/commands/local/lib/local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/lib/telemetry/metric.py", line 323, in wrapped_func
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/local/lambdafn/runtime.py", line 188, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/local/lambdafn/runtime.py", line 84, in create
    container = LambdaContainer(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_container.py", line 93, in __init__
    image = LambdaContainer._get_image(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_container.py", line 236, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture, function_name=function_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_image.py", line 191, in build
    self._check_base_image_is_current(base_image)
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_image.py", line 451, in _check_base_image_is_current
    if self.is_base_image_current(image_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_image.py", line 475, in is_base_image_current
    return self.get_local_image_digest(image_name) == self.get_remote_image_digest(image_name)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_image.py", line 491, in get_remote_image_digest
    remote_info = self.docker_client.images.get_registry_data(image_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/docker/models/images.py", line 337, in get_registry_data
    attrs=self.client.api.inspect_distribution(name, auth_config),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/docker/api/image.py", line 281, in inspect_distribution
    return self._result(
           ^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.73.0/libexec/lib/python3.11/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)

An unexpected error was encountered while executing "sam local invoke".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20local%20invoke%20-%20APIError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20local%20invoke%20-%20APIError
[~/sam-app]$                                                                             
```

I have exactly same error on Windows 11 Pro, under WSL2

**Comment by jfuss** [comment] 2023-02-13 16:36
@andrzejsliwa We need better error handling here but the error isn't something we can control. For whatever reason, your machine is getting a 443 from AWS Public ECR. 

This looks similar to https://github.com/aws/aws-sam-cli/issues/4696 and https://github.com/aws/aws-sam-cli/issues/4694. One re-did their WSL and docker setup which works and the other retried and things works. 

Is this still reproducible? I wonder if there was something in trying to communicate with Public ECR that is no longer happening (something with networking?)

**Comment by leegohi04517** [comment] 2023-02-14 07:41
the same issue with me. "dialing public.ecr.aws:443 static system has no HTTPS proxy"

**Comment by lucashuy** [comment] 2023-02-14 17:30
Thanks for letting us know @leegohi04517, are you connected to a VPN or have a firewall setup that might be blocking requests to ECR? If possible can you paste the output of `sam --info` here so that we can gather some info about the systems that are encountering this problem? I am not able to reproduce this with a Python 3.8 hello world SAM template.

**Comment by sriram-mv** [comment] 2023-02-21 18:40
We do believe this is a bug, I'm not able to reproduce this either. Is there any networking that is different on your end that could be causing this?

**Comment by sriram-mv** [comment] 2023-02-21 22:50
Closing this issue, we can re-open it if its persisting on your end.

**Closed by sriram-mv** 2023-02-21 22:50 UTC
Labels: question
