### ISSUE TITLE
Bug: TITLE Error while executing command: sam build --use-container --template ${SAM_TEMPLATE}

### ISSUE THREAD

**Issue by sshiv5768** [aws/aws-sam-cli#4529] opened 2023-01-02 09:41 UTC
### Description:
I was trying to run ``sam build --use-container --template ${SAM_TEMPLATE}`` but it failed and showed ```Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sam build --use-container --template ${SAM_TEMPLATE}. Reason: exit status 1 ```

### Observed result:

<html>
<body>

[Container] 2023/01/02 09:00:13 Phase complete: INSTALL State: SUCCEEDED
--
247 | [Container] 2023/01/02 09:00:13 Phase context status code:  Message:
248 | [Container] 2023/01/02 09:00:13 Entering phase PRE_BUILD
249 | [Container] 2023/01/02 09:00:13 Phase complete: PRE_BUILD State: SUCCEEDED
250 | [Container] 2023/01/02 09:00:13 Phase context status code:  Message:
251 | [Container] 2023/01/02 09:00:13 Entering phase BUILD
252 | [Container] 2023/01/02 09:00:13 Running command sam build --use-container --template ${SAM_TEMPLATE}
253 | Traceback (most recent call last):
254 | File "/root/.pyenv/versions/3.8.13/bin/sam", line 8, in <module>
255 | sys.exit(cli())
256 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
257 | return self.main(*args, **kwargs)
258 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 1055, in main
259 | rv = self.invoke(ctx)
260 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 1651, in invoke
261 | cmd_name, cmd, args = self.resolve_command(ctx, args)
262 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/click/core.py", line 1698, in resolve_command
263 | cmd = self.get_command(ctx, cmd_name)
264 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/samcli/cli/command.py", line 133, in get_command
265 | mod = importlib.import_module(pkg_name)
266 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py", line 127, in import_module
267 | return _bootstrap._gcd_import(name[level:], package, level)
268 | File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
269 | File "<frozen importlib._bootstrap>", line 991, in _find_and_load
270 | File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
271 | File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
272 | File "<frozen importlib._bootstrap_external>", line 843, in exec_module
273 | File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
274 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/samcli/commands/build/__init__.py", line 6, in <module>
275 | from .command import cli  # noqa
276 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/samcli/commands/build/command.py", line 12, in <module>
277 | from samcli.commands._utils.options import (
278 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/samcli/commands/_utils/options.py", line 21, in <module>
279 | from samcli.commands._utils.template import get_template_data, TemplateNotFoundException
280 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/samcli/commands/_utils/template.py", line 10, in <module>
281 | from botocore.utils import set_value_from_jmespath
282 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/botocore/utils.py", line 37, in <module>
283 | import botocore.httpsession
284 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/botocore/httpsession.py", line 46, in <module>
285 | from urllib3.contrib.pyopenssl import (
286 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
287 | import OpenSSL.SSL
288 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
289 | from OpenSSL import crypto, SSL
290 | File "/root/.pyenv/versions/3.8.13/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3268, in <module>
291 | _lib.OpenSSL_add_all_algorithms()
292 | AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
293 |  
294 | [Container] 2023/01/02 09:00:14 Command did not exit successfully sam build --use-container --template ${SAM_TEMPLATE} exit status 1
295 | [Container] 2023/01/02 09:00:14 Phase complete: BUILD State: FAILED
296 | [Container] 2023/01/02 09:00:14 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: sam build --use-container --template ${SAM_TEMPLATE}. Reason: exit status 1
297 | [Container] 2023/01/02 09:00:14 Entering phase POST_BUILD
298 | [Container] 2023/01/02 09:00:14 Phase complete: POST_BUILD State: SUCCEEDED
299 | [Container] 2023/01/02 09:00:14 Phase context status code:  Message:
300 | [Container] 2023/01/02 09:00:14 exiting execCommands
301 | [Container] 2023/01/02 09:00:14 Expanding base directory path: .
302 | [Container] 2023/01/02 09:00:14 Assembling file list
303 | [Container] 2023/01/02 09:00:14 Expanding .
304 | [Container] 2023/01/02 09:00:14 Expanding file paths for base directory .
305 | [Container] 2023/01/02 09:00:14 Assembling file list
306 | [Container] 2023/01/02 09:00:14 Expanding packaged-test.yaml
307 | [Container] 2023/01/02 09:00:14 Skipping invalid file path packaged-test.yaml
308 | [Container] 2023/01/02 09:00:14 Expanding assume-role.sh
309 | [Container] 2023/01/02 09:00:14 Expanding pipeline/*
310 | [Container] 2023/01/02 09:00:14 Found 8 file(s)
311 | [Container] 2023/01/02 09:00:14 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED
312 | [Container] 2023/01/02 09:00:14 Phase context status code:  Message:

</body>
</html>

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`

**Comment by pkotnis** [comment] 2023-01-02 14:27
Line 292 suggests you run into the https://github.com/aws/aws-sam-cli/issues/4527 issue

**Comment by moelasmar** [comment] 2023-01-03 00:10
Closing this issue as it is a duplicate of issue https://github.com/aws/aws-sam-cli/issues/4527

**Closed by moelasmar** 2023-01-03 00:10 UTC
Labels: type/bug, stage/needs-triage
