### ISSUE TITLE
Unable to run docker in ARM Architecture

### ISSUE THREAD

**Issue by samgegr8** [aws/aws-sam-cli#2951] opened 2021-06-10 06:45 UTC
### Steps to reproduce:

1. Step : 1 Create a  YAML for lambda that uses Docker Image 
2. Step: 2 Add Docker File in the metadata of yaml which is similar to 
`FROM  python:3.6
WORKDIR /src
COPY main.py requirements.txt config.json ./
RUN apt-get update && apt-get install make git
RUN apt-get install -y apt-utils
RUN apt-get install -y cmake
RUN apt-get install -y librdkafka-dev
RUN pip install -r requirements.txt
ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD ["main.lambda_handler"]`
3. Fails as it tries to build in arm architecture

### Observed result:

Fails to build the image 
`creating build/temp.linux-aarch64-3.6/tmp/pip-install-bur4_y1q/confluent-kafka_3a16b52446ce4d7a82d5dbf75653e9f4/src/confluent_kafka/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.6m -c /tmp/pip-install-bur4_y1q/confluent-kafka_3a16b52446ce4d7a82d5dbf75653e9f4/src/confluent_kafka/src/confluent_kafka.c -o build/temp.linux-aarch64-3.6/tmp/pip-install-bur4_y1q/confluent-kafka_3a16b52446ce4d7a82d5dbf75653e9f4/src/confluent_kafka/src/confluent_kafka.o
    In file included from /tmp/pip-install-bur4_y1q/confluent-kafka_3a16b52446ce4d7a82d5dbf75653e9f4/src/confluent_kafka/src/confluent_kafka.c:17:
    /tmp/pip-install-bur4_y1q/confluent-kafka_3a16b52446ce4d7a82d5dbf75653e9f4/src/confluent_kafka/src/confluent_kafka.h:66:2: error: #error "confluent-kafka-python requires librdkafka v1.6.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
     #error "confluent-kafka-python requires librdkafka v1.6.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"`

### Expected result:

SAM CLI should automatically build Docker image for x86 till the support of Lambda is ready for Graviton

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:MacOs M1
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.24.0
3. AWS region: ap-southeast-2

`Add --debug flag to any SAM CLI commands you are running`

**Comment by mndeveci** [comment] 2021-06-12 01:50
Thanks for raising this issue @samgegr8 ,

AFAIK, in order to build for different architectures, you need `buildx` and additional CLI from docker. https://docs.docker.com/buildx/working-with-buildx/

You can try to use custom builds for function which is described here; https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html

**Comment by samratskmart** [comment] 2021-06-23 03:11
docker buildx works fine . But the problem is with sam build which ignores the platform parameter and tries to run in ARM ignoring the platform parameter. Is there a way to force the docker image building in the sam for a particular platform

**Comment by samgegr8** [comment] 2021-06-23 03:14
Docker buildx runs fine. But in this case I am trying to build the Docker image through the yaml using sam build, where the lambda would be build using the docker image. In this case , the sam build ignores the platform parameter and tries to build using the underlying architecture which is ARM in this case.

**Comment by metaskills** [comment] 2021-07-17 11:27
👂🏼 I'm curious about this as well because I am trying to learn how to use buildx with SAM on GitHub Actions and caching. This issue may not be where I need to learn that information but wanted to share the eavesdropping reason. https://github.com/moby/buildkit/pull/2244/files#r668926866

**Comment by pagameba** [comment] 2022-09-26 18:42
I am also interested in how to enable caching of docker build for sam functions and enable caching in GitHub Actions.

**Comment by sriram-mv** [comment] 2023-02-21 22:57
Closing this issue. You can specify which base image you want to build from the in dockerfile and and also set the arch in template.

**Closed by sriram-mv** 2023-02-21 22:57 UTC
Labels: stage/needs-investigation, maintainer/need-followup, platform/mac/arm
