### ISSUE TITLE
Unstable state when updating repo. Check that you have permissions to create/delete files

### ISSUE THREAD

**Issue by arav1509** [aws/aws-sam-cli#4091] opened 2022-08-01 17:58 UTC
Hi,
When I am trying to create a project in IntelliJ ,  getting below error.
`java.lang.RuntimeException: Could not execute `sam init`!: [Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment), Error: Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\aravi\AppData\Roaming\AWS SAM directory or file an issue at https://github.com/aws/aws-sam-cli/issues]`

SAM CLI, version 1.53.0

Thanks,
Aravind

**Comment by computan** [comment] 2022-08-01 18:45
> Hi, When I am trying to create a project in IntelliJ , getting below error. `java.lang.RuntimeException: Could not execute `sam init`!: [Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment), Error: Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\aravi\AppData\Roaming\AWS SAM directory or file an issue at https://github.com/aws/aws-sam-cli/issues]`
> 
> SAM CLI, version 1.53.0
> 
> Thanks, Aravind

Did you figure out the issue? I am having the same issue.

**Comment by MaisumAbbas** [comment] 2022-08-01 18:47
Did you figure out the issue? I am having the same error.

**Comment by bbarthel** [comment] 2022-08-01 20:36
I'm also having the issue with .NET 6

**Comment by jfuss** [comment] 2022-08-01 21:32
@arav1509 Did you see if you had create/delete permission, as the error stated? `Check that you have permissions to create/delete files in C:\Users\aravi\AppData\Roaming\AWS SAM directory`

**Comment by jfuss** [comment] 2022-08-01 21:36
You are also on Windows and I know the file path length can be an issue. You can try doing https://github.com/aws/aws-sam-cli/issues/4031#issuecomment-1183633630

This is also a duplicate of #4031. Not sure if you did look at open issues but if you didn't please do that before creating. Makes it much easier to follow and track on our end and already has a workaround (which I think is just the solution to this at this point).

Closing

**Closed by jfuss** 2022-08-01 21:36 UTC
Labels: stage/needs-triage

**Comment by AJESH-CR** [comment] 2022-08-08 11:41
```
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
-Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```

**Comment by KIRUBHAHAR** [comment] 2022-08-12 15:45
Okay here is the problem why it occurs and the solution for Windows users:

The problem was with the path ("AWS SAM") in Windows that has a space that causes the problem: By calling the --location arg and putting the full path in double quotes it works

> sam init --location "C:\Users[your_user_name]\AppData\Roaming\AWS SAM\aws-sam-cli-app-templates\python3.9\cookiecutter-aws-sam-hello-python"

**Comment by pconnell99** [comment] 2022-08-19 11:12
> Okay here is the problem why it occurs and the solution for Windows users:
> 
> The problem was with the path ("AWS SAM") in Windows that has a space that causes the problem: By calling the --location arg and putting the full path in double quotes it works
> 
> > sam init --location "C:\Users[your_user_name]\AppData\Roaming\AWS SAM\aws-sam-cli-app-templates\python3.9\cookiecutter-aws-sam-hello-python"

How are we fixing this via AWS toolkit calls?

**Comment by subwaymatch** [comment] 2022-09-13 13:05
> ```
> New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
> -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
> ```
> 
> Try running following command administrator in PowerShell, it's worked for me. https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later
> 
> This is the actual cause playing behind all the troubles.
> 
> ```
> fatal: cannot create directory at 'provided.al2/graalvm/java11/cookiecutter-aws-sam-graalvm-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core':
>  Filename too long
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'
> ```

@AJESH-CR You're a real hero. Thank you for sharing your solution. Running the command to change `LongPathsEnabled` on PowerShell fixed the issue for me on Windows 10 + AWS Toolkit for VSCode.

**Comment by sdsa-cci** [comment] 2022-09-16 05:51
> ```
> New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
> -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
> ```
> 
> Try running following command administrator in PowerShell, it's worked for me. https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later
> 
> This is the actual cause playing behind all the troubles.
> 
> ```
> fatal: cannot create directory at 'provided.al2/graalvm/java11/cookiecutter-aws-sam-graalvm-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core':
>  Filename too long
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'
> ```

Thank you sir! 💯  This worked for me too.

**Comment by NdukaClara** [comment] 2022-09-17 01:11
> ```
> New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
> -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
> ```
> 
> Try running following command administrator in PowerShell, it's worked for me. https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#enable-long-paths-in-windows-10-version-1607-and-later
> 
> This is the actual cause playing behind all the troubles.
> 
> ```
> fatal: cannot create directory at 'provided.al2/graalvm/java11/cookiecutter-aws-sam-graalvm-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core':
>  Filename too long
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'
> ```

Thank you so much!
