### ISSUE TITLE
Feature request: SAM CLI -Include-dir (Terraform) (Build)

### ISSUE THREAD

**Issue by jordancparker** [aws/aws-sam-cli#5339] opened 2023-06-12 09:28 UTC
Hi Team, 

I think this has been discussed in other threads, but it would be really helpful if we can help with more structured repositories in a terraform work flow like the below: 

```
/project
  /infrastructure
    envrionment/
        dev/
            dev.tfvars
        test/
            test.tfvars
    main.tf
    providers.tf
  /src
    ... (lambda code) ...
  /tests
    ... (lambda tests) ...
```

I prepose a couple of solutions:
- 1. add a cli command to include-dir e.g. `--include-dir "../src/*"`
  - this could then be added to the samconfig.toml

```
version = 0.1
[default]
[default.build.parameters]
hook_name = "terraform"
beta_features = true
include-dir = ../src/*
```

- 2. Pull through the code declared in the `sam_metadata` resource `
```
resource "null_resource" "sam_metadata_..." {
  triggers = {
    original_source_code = "../src
  }
}
```

I have tried playing with the --base-dir and --manifest flags however when the file is located above the root it cannot identify the ../src folder with the lambda code.

It would be amazing to see if we can help with more flexible terraform builds to suit the structured folders, instead of putting the python structure under the terraform folder.

**Comment by GantZA** [comment] 2023-06-12 10:31
I would like this feature too, currently trying to help setup SAM and Terraform at a client where lambda function projects are structure similar to the above. local debugging and testing isn't great at the moment but SAM working with Terraform would solve this massively

**Comment by mildaniel** [comment] 2023-06-12 21:17
Thanks for the feature request. We understand this to be a limitation currently impacting customers and are looking at a few different ways to address this issue!

**Comment by jordancparker** [comment] 2023-06-16 11:56
Hi @mildaniel , 

Do we have an ETA or a view on when this is in the roadmap. 

Also do we need to update the tags to add `area/build`, `area/terraform`?

**Comment by moelasmar** [comment] 2023-08-29 19:25
Hi @jordancparker, 
Thanks for raising this request. This request is a duplicate of [this issue](https://github.com/aws/aws-sam-cli/issues/4724). I am going to close your request, and you can follow up on the other issue to get updates on this feature.

**Closed by moelasmar** 2023-08-29 19:25 UTC
Labels: type/feature, area/build, area/terraform
