### ISSUE TITLE
Incorrect path when using --docker-volume-basedir with local invoke/start-api

### ISSUE THREAD

**Issue by dsanders11** [aws/aws-sam-cli#1834] opened 2020-02-28 21:26 UTC
### Description

The wrong path is being used when `--docker-volume-basedir` is used. By the help description, the path should be to the SAM template, but for expected behavior you have to provide the path to the build artifacts.

### Steps to reproduce

1. `sam build`
2. `sam local invoke --docker-volume-basedir /foo`

### Observed result

```
Invoking app.lambda_handler (python3.8)

Fetching lambci/lambda:python3.8 Docker container image......
Mounting `/foo/HelloWorldFunction as /var/task:ro,delegated inside runtime container
```

### Expected result

```
Invoking app.lambda_handler (python3.8)

Fetching lambci/lambda:python3.8 Docker container image......
Mounting `/foo/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. `sam --version`: SAM CLI, version 0.43.0

**Comment by nirradi** [comment] 2021-04-13 11:43
seems to be working properly in 1.12, and stops working again in 1.22

**Comment by xazhao** [comment] 2021-07-20 22:34
Currently I don't have remote Docker setup so I couldn't verify it. I need to dive deep into the code to see the root cause. But it seems related to `--base-dir` option in `sam build`. We made some changes related to that option in 1.21 so it matches to what @nirradi said. While I'm on investigation, feel free to try using `--base-dir`

**Comment by xazhao** [comment] 2021-07-23 00:26
Trying to reproduce this issue in the current version 1.24.1
`sam local invoke "HelloWorldFunction" -e events/event.json --docker-volume-basedir /Users/xazhao/sshfs`
And in the log it works properly
`Mounting /Users/xazhao/sshfs/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container`
Since it was one year ago, I believe this issue has been fixed.

I will close the issue. If you find other bugs, feel free to create a new issue.

**Closed by xazhao** 2021-07-23 00:26 UTC
Labels: area/local/invoke, area/local/start-api
