### ISSUE TITLE
Bug: Uncomplete publish on Serverless Application Repository

### ISSUE THREAD

**Issue by EliaContiniCL-CH** [aws/aws-sam-cli#3932] opened 2022-05-11 09:37 UTC
Hi everybody,

I'm trying to make public on SAR the **Hello World Example** but I had some troubles:
 - the README.md is not displayed/set
 - the License in not displayed/set and it is not possible to make the application public.

## My dev env
macOS Big Sur 11.6.5
SAM CLI, version 1.49.0

## Steps to reproduce the issue

1. I used `sam init` to create the project (Hello World Example, Nodejs 16). Here the output

    ```
    sam init
    
    You can preselect a particular runtime or package type when using the `sam init` experience.
    Call `sam init --help` to learn more.
    
    Which template source would you like to use?
	    1 - AWS Quick Start Templates
	    2 - Custom Template Location
    Choice: 1
    
    Choose an AWS Quick Start application template
	    1 - Hello World Example
	    2 - Multi-step workflow
	    3 - Serverless API
	    4 - Scheduled task
	    5 - Standalone function
	    6 - Data processing
	    7 - Infrastructure event management
	    8 - Machine Learning
    Template: 1
    
    Use the most popular runtime and package type? (Python and zip) [y/N]: 
    
    Which runtime would you like to use?
	    1 - dotnet6
	    2 - dotnet5.0
	    3 - dotnetcore3.1
	    4 - go1.x
	    5 - java11
	    6 - java8.al2
	    7 - java8
	    8 - nodejs16.x
	    9 - nodejs14.x
	    10 - nodejs12.x
	    11 - python3.9
	    12 - python3.8
	    13 - python3.7
	    14 - python3.6
	    15 - ruby2.7
	    16 - rust (provided.al2)
    Runtime: 8
    
    Based on your selections, the only Package type available is Zip.
    We will proceed to selecting the Package type as Zip.
    
    Based on your selections, the only dependency manager available is npm.
    We will proceed copying the template using npm.
    
    Select your starter template
	    1 - Hello World Example
	    2 - Hello World Example TypeScript
    Template: 1
    
    Would you like to enable X-Ray tracing on the function(s) in your application?  [y/N]: y
    X-Ray will incur an additional cost. View https://aws.amazon.com/xray/pricing/ for more details
    
    Project name [sam-app]: pippo
    
    Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)
    
        -----------------------
        Generating application:
        -----------------------
        Name: pippo
        Runtime: nodejs16.x
        Architectures: x86_64
        Dependency Manager: npm
        Application Template: hello-world
        Output Directory: .
        
        Next steps can be found in the README file at ./pippo/README.md
            
    
        Commands you can use next
        =========================
        [*] Create pipeline: cd pippo && sam pipeline init --bootstrap
        [*] Validate SAM template: sam validate
        [*] Test Function in the Cloud: sam sync --stack-name {stack-name} --watch
    ```

2. I edited the `template.yaml` adding the `Metadata` section
    ```
    Metadata:
      AWS::ServerlessRepo::Application:
        Author: ACME
        Description: >
          Test README.md on SAR
        Labels: ["test", "readme", "sar"]
        LicenseUrl: LICENSE.txt
        Name: sar-readme-test
        ReadmeUrl: README.md
        SemanticVersion: 1.0.0
        SpdxLicenseId: Apache-2.0
    ```

3. Added a LICENSE.txt with the content of [Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0.txt)

4. I followed the [official guide](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html#serverless-sam-template-publishing-applications-prerequisites) setting up the bucket (`sar-test-readme`) and the bucket policies.

5. I ran `sam build`

6. I ran `sam package --output-template-file packaged.yaml --s3-bucket sar-test-readme`. The output
    ```
    Uploading to 3b83ef96387f14655fc854ddc3c6bd57  11358 / 11358  (100.00%)
    Uploading to 23351179e40170179374efc8237b514b  8219 / 8219  (100.00%)
    Uploading to c4f0b3ffd3691657a574b71945d034a1  225697 / 225697  (100.00%)
    
    Successfully packaged artifacts and wrote output template to file packaged.yaml.
    Execute the following command to deploy the packaged template
    sam deploy --template-file /Users/elia/projects/sar-readme-test/packaged.yaml --stack-name <YOUR STACK NAME>
    ```

7. I ran `sam publish --template packaged.yaml --region eu-west-1`. The output
    ```
    Publish Succeeded
    The following metadata of application "arn:aws:serverlessrepo:eu-west-1:123456789012:applications/sar-readme-test" has been updated:
    {
      "Author": "ACME",
      "Description": "Test README.md on SAR\n",
      "Labels": [
        "test",
        "readme",
        "sar"
      ],
      "ReadmeUrl": "s3://sar-test-readme/23351179e40170179374efc8237b514b",
      "SemanticVersion": "1.0.0"
    }
    Click the link below to view your application in AWS console:
    https://console.aws.amazon.com/serverlessrepo/home?region=eu-west-1#/published-applications/arn:aws:serverlessrepo:eu-west-1:123456789012:applications~sar-readme-test
    ```

8. From console I created a statemet to share the application with another account. This account is able to see the app and install it. But unfortunately is not able to see the content of the `README.md`.

9. In addition, if I try to make the app public, the console says `Only application with license can be made public`.

Do I miss some configuration?
How can I make available for users  the README.md with more info and installation tips?

Thanks in advance for any suggestion.
Have a nice day

**Comment by mildaniel** [comment] 2022-06-03 18:10
Moving to SAM-CLI since it is more applicable.

**Comment by mildaniel** [comment] 2023-01-19 19:51
Hey Elia, thanks for bringing this to our attention. I followed the steps you provided above and used the referenced official guide for bucket creation but wasn't able to reproduce this issue. When I publish the application I can see the README and LICENSE files in SAR and am able to make it public. I wonder if this could've been a transient issue with the SAR service at the time since it looks like the artifacts you created were packaged in S3 and are part of the metadata being published.

**Comment by jfuss** [comment] 2023-02-10 03:40
Closing since we can't repro the failure.

If something still isn't working on the latest version of SAM CLI, please create a new issue and we will be glad to help further.

**Closed by jfuss** 2023-02-10 03:40 UTC
Labels: blocked/more-info-needed, question
