### ISSUE TITLE
Bug: sam local start-api tries to fetch layer from wrong account

### ISSUE THREAD

**Issue by royassis** [aws/aws-sam-cli#5230] opened 2023-05-31 11:28 UTC
### Description:
sam local start-api tries to fetch layer from wrong account when **AWS::AccountId** is used in template.

This is part of template.yaml: 
```
....
<ResourceLogicalName>:
    Type: AWS::Serverless::Function
    Properties:
       ....
        Layers:
            !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:layer:neo4j:1
       ....
....
```

When I invoked the endpoint of the lambda (with ResourceLogicalName) that uses the layer, after running ` sam local start-api`. I get:
```
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetLayerVersion operation: User: arn:aws:iam::<masked>:user/<masked> is not authorized to perform:
lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:123456789012:layer:neo4j:1 because no resource-based policy allows the lambda:GetLayerVersion action
```
The account id in the error message, **123456789012**, is not the correct accountid, or any accountid that I know of. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows-10
2. `sam --version`: SAM CLI, version 1.83.0
3. AWS region: us-east-1

```
{
  "version": "1.83.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.24",
    "aws_cdk": "Not available",
    "terraform": "1.3.4"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by jfuss** [comment] 2023-05-31 21:45
Duplicate of https://github.com/aws/aws-sam-cli/issues/4208.

We have logic within the cli to do best effort on Intrinsic resolving. We do not support `AWS::AccountId` at the moment. 

Alternative is passing in through Parameters or if you are defaulting to the same account and the layer is in the same template, you can `!Ref` the layer instead (which will work locally and deployed).

**Closed by jfuss** 2023-05-31 21:45 UTC
Labels: stage/needs-triage
