### ISSUE TITLE
Host and pull sam cli local invocation images in ECR Public

### ISSUE THREAD

**Issue by tbennett0** [aws/aws-sam-cli#3095] opened 2021-07-21 18:04 UTC
It would be incredibly helpful if AWS could host the sam cli/emulation images (used to [invoke functions locally](https://github.com/aws/aws-sam-cli/blob/72f7bfe209eb5cbe05ae294a897c988fe942fd79/samcli/local/docker/lambda_image.py#L57-L58) in `sam local invoke` or `sam local start-lambda`) in ECR public like has been done with [other sam tooling](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-image-repositories.html). Otherwise, running sam local tooling in a CI environment with a shared public IP can cause intermittent failures because of Docker Hub throttling, with errors like the following:

`
samcli.commands.local.cli_common.user_exceptions.ImageBuildException: Error building docker image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
`

The same would also be helpful for DynamoDB local, but this is easier to mirror for private use (not hardcoded where it would be used).

Thank you!

**Comment by jfuss** [comment] 2021-07-22 02:22
Duplicate of https://github.com/aws/aws-sam-cli/issues/2467

closing

**Closed by jfuss** 2021-07-22 02:22 UTC
