### ISSUE TITLE
sam-beta-cdk not support local invoke of container packaged Lambda

### ISSUE THREAD

**Issue by yike5460** [aws/aws-sam-cli#3462] opened 2021-11-12 03:10 UTC
### Description:
currently our sam-beta-cdk (SAM CLI, version 1.29.0.dev202108311500) not support local invoke of Lambda create with container image

### Steps to reproduce:

"sam-beta-cdk local invoke" for code snippet below will prompt errors like "jsii.errors.JSIIError: Object of type @aws-cdk/aws-lambda.DockerImageCode is not convertible to @aws-cdk/aws-lambda.Code
Subprocess exited with error 1"

```
cdk_lambda = _lambda.Function(
            scope=self,
            id="cdk-hello-world-lambda",
            runtime=_lambda.Runtime.PYTHON_3_8,
            function_name="cdk-hello-world-lambda-function",
            description="Lambda function deployed using AWS CDK Python",
            code=_lambda.DockerImageCode.from_image_asset("./hello_world"),
            handler="app.lambda_handler",
            events=[self.lambda_event]
        )
```

### Observed result:

full log of local invoke as follows:

```
sam-beta-cdk local invoke sam-app-orig/cdk-hello-world-lambda --debug
2021-11-12 11:07:04,152 | IAC Plugin getting project...
2021-11-12 11:07:04,156 | CDK Toolkit found at /usr/local/bin/cdk
2021-11-12 11:07:04,156 | Synthesizing CDK App
2021-11-12 11:07:04,156 | command: ['/usr/local/bin/cdk', 'synth', '--no-staging', '-o', '.aws-sam/.cdk-out']
Error: When synthesizing your CDK app, the following error occurs:

jsii.errors.JavaScriptError: 
  Error: Object of type @aws-cdk/aws-lambda.DockerImageCode is not convertible to @aws-cdk/aws-lambda.Code
      at Object.deserialize (/private/var/folders/6v/dx_b63s5113d9p0cxv7zvrx8vdqn9c/T/tmpj3eezhd1/lib/program.js:9107:35)
      at Kernel._toSandbox (/private/var/folders/6v/dx_b63s5113d9p0cxv7zvrx8vdqn9c/T/tmpj3eezhd1/lib/program.js:8505:69)
      at /private/var/folders/6v/dx_b63s5113d9p0cxv7zvrx8vdqn9c/T/tmpj3eezhd1/lib/program.js:9070:37
      at mapValues (/private/var/folders/6v/dx_b63s5113d9p0cxv7zvrx8vdqn9c/T/tmpj3eezhd1/lib/program.js:9341:35)
      at Object.deserialize (/private/var/folders/6v/dx_b63s5113d9p0cxv7zvrx8vdqn9c/T/tmpj3eezhd1/lib/program.js:9066:28)
      at Kernel._toSandbox (/private/var/folders/6v/dx_b63s5113d9p0cxv7zvrx8vdqn9c/T/tmpj3eezhd1/lib/program.js:8505:69)
      at /private/var/folders/6v/dx_b63s5113d9p0cxv7zvrx8vdqn9c/T/tmpj3eezhd1/lib/program.js:8553:42
      at Array.map (<anonymous>)
      at Kernel._boxUnboxParameters (/private/var/folders/6v/dx_b63s5113d9p0cxv7zvrx8vdqn9c/T/tmpj3eezhd1/lib/program.js:8553:27)
      at Kernel._toSandboxValues (/private/var/folders/6v/dx_b63s5113d9p0cxv7zvrx8vdqn9c/T/tmpj3eezhd1/lib/program.js:8539:29)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kyiamzn/01_code/23_MIE/metadata/samCdkPreview/sam-app-orig/app.py", line 15, in <module>
    AwsSamCliCdkHelloWorldStack(app, 'sam-app-orig',
  File "/usr/local/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/kyiamzn/01_code/23_MIE/metadata/samCdkPreview/sam-app-orig/aws_sam_cli_cdk_hello_world_stack/aws_sam_cli_cdk_hello_world_stack.py", line 24, in __init__
    cdk_lambda = _lambda.Function(
  File "/usr/local/lib/python3.9/site-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aws_cdk/aws_lambda/__init__.py", line 15340, in __init__
    jsii.create(Function, self, [scope, id, props])
  File "/usr/local/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 275, in create
    response = self.provider.create(
  File "/usr/local/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 344, in create
    return self._process.send(request, CreateResponse)
  File "/usr/local/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Object of type @aws-cdk/aws-lambda.DockerImageCode is not convertible to @aws-cdk/aws-lambda.Code
Subprocess exited with error 1
```

### Expected result:
Lambda function can be simulated in local container properly

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. If using SAM CLI, `sam --version`:
3. AWS region:

`Add --debug flag to any SAM CLI commands you are running`

**Comment by moelasmar** [comment] 2021-11-12 22:29
I believe the issue is in the CDK application itself. Could you please try first to run `cdk synth` in your application to make sure that it is a valid CDK application.

**Comment by yike5460** [comment] 2021-11-15 01:22
My bad, I didn't adjust code accordingly, error fix when I using code below.
`        
cdk_lambda = _lambda.DockerImageFunction(
            scope=self,
            id="cdk-hello-world-lambda",
            function_name="cdk-hello-world-lambda-function",
            description="Lambda function deployed using AWS CDK Python",
            code=_lambda.DockerImageCode.from_image_asset("./hello_world"),
            events=[self.lambda_event]
        )
`
However, another error prompt as follows:
`
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: /v1.35/images/metadata/samCdkPreview/sam-app-orig/hello_world:rapid-1.29.0.dev202108311500/json

During handling of the above exception, another exception occurred and "cdk synth" works fine:

Traceback (most recent call last):
  File "/usr/local/bin/sam-beta-cdk", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/iac/utils/helpers.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/commands/_utils/iac_validations.py", line 79, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 174, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 141, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 95, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 195, in do_cli
    context.local_lambda_runner.invoke(
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 129, in invoke
    self.local_runtime.invoke(
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 238, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 176, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 73, in create
    container = LambdaContainer(
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 87, in __init__
    image = LambdaContainer._get_image(lambda_image, runtime, packagetype, imageuri, layers)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 213, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 131, in build
    self.docker_client.images.get(image_tag)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/docker/api/image.py", line 245, in inspect_image
    return self._result(
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("no such image: Users/metadata/samCdkPreview/sam-app-orig/hello_world:rapid-1.29.0.dev202108311500: invalid reference format: repository name must be lowercase")
`
the dockerfile in hello_world is pretty straight forward, not sure the image calling "rapid-1.29.0.dev202108311500" in log meant to
`
FROM public.ecr.aws/lambda/python:3.8

COPY *.py ${LAMBDA_TASK_ROOT}

CMD ["app.lambda_handler"]
`

**Comment by moelasmar** [comment] 2021-11-15 11:07
is it possible to share your project with us on some github repo, this will help us to investigate.

**Comment by yike5460** [comment] 2021-11-15 14:30
reproduce step:

init project first
```
sam-beta-cdk init
Which type of project would you like to create?
        1 - SAM
        2 - CDK
Choice: 2
Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 1

Which language would you like to use for the CDK app?
        1 - python
        2 - javascript
        3 - typescript
CDK Language: 1
Example CDK project only have ZIP type (artifact is a zip uploaded to S3) now.

Which runtime would you like to use?
        1 - nodejs14.x
        2 - python3.8
Runtime: 2

Project name [sam-app]: 

Cloning from https://github.com/aws/aws-sam-cli-app-templates

    -----------------------
    Generating application:
    -----------------------
    Name: sam-app
    Runtime: python3.8
    Dependency Manager: pip
    Application Template: hello-world
    Output Directory: .
    Project Type: CDK 
    CDK application language: python

    
    Next steps can be found in the README file at ./sam-app/README.md
        

SAM CLI update available (1.35.0); (1.29.0.dev202108311500 installed)
To download: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html
```
then add dockerfile into default created hello_world folder, and modify lambda code as follows:
```
cdk_lambda = _lambda.DockerImageFunction(
            scope=self,
            id="cdk-hello-world-lambda",
            function_name="cdk-hello-world-lambda-function",
            description="Lambda function deployed using AWS CDK Python",
            code=_lambda.DockerImageCode.from_image_asset("./hello_world"),
            events=[self.lambda_event]
        )
```

**Comment by yike5460** [comment] 2021-11-29 14:13
@moelasmar any feedback?

**Comment by spmacdonald** [comment] 2021-12-02 22:15
I think I have the exact same issue as this:

```Synthesizing CDK App
Invoking Container created from /home/scott/code/RiskModels/src/lambda-functions
Traceback (most recent call last):
  File "docker/api/client.py", line 261, in _raise_for_status
  File "requests/models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: /v1.35/images/home/scott/code/RiskModels/src/lambda-functions:rapid-1.29.0.dev202108311500/json```

**Comment by hawflau** [comment] 2022-01-20 22:42
Hi @yike5460 @spmacdonald CDK Support for SAM CLI is now GA at version 1.37.0. I tested with a CDK app with a simple Image-type Function, and it worked fine. Can you try again with SAM CLI v1.37.0?

I'm closing the issue for now. Feel free to re-open if the problem persists.

**Closed by hawflau** 2022-01-20 22:42 UTC
Labels: stage/needs-investigation, maintainer/need-followup
