### ISSUE TITLE
[Tracking Issue] SAM CLI + CDK Beta release feedback

### ISSUE THREAD

**Issue by praneetap** [aws/aws-sam-cli#3242] opened 2021-09-04 19:56 UTC
We recently announced the [public preview](https://aws.amazon.com/blogs/compute/better-together-aws-sam-and-aws-cdk/
) of SAM CLI support for local development and testing of CDK projects. 
With this preview release, you can use AWS SAM CLI to build, test, and in the future, package applications defined using the AWS CDK.

To install this beta release, follow instructions [here](https://aws.amazon.com/blogs/compute/better-together-aws-sam-and-aws-cdk/).

We would love your feedback on the feature! Please feel free to leave your thoughts/ideas in the comments.

**Comment by sonya** [comment] 2021-09-05 21:35
It looks like the homebrew tap for `aws-sam-cli-beta-cdk` is currently pointing to a tag that no longer exists ([1.29.0.dev202108311500](https://github.com/aws/homebrew-tap/blob/aa4eb0f5f5ad2b129b2f9e991d1e07d80c8534ed/bottle-configs/aws-sam-cli-beta-cdk.json#L2)), will this be updated soon?

**Comment by wchengru** [comment] 2021-09-07 00:38
Thanks for reporting this @sonya ! We have recreated this tag and updated our homebrew config. Can you please try downloading the source, or installing it with homebrew `--build-from-source` option?

**Comment by sonya** [comment] 2021-09-08 02:50
Thanks @wchengru, i was able to install directly with `brew install aws-sam-cli-beta-cdk`. 🎉 

I recently tried out the high level PythonFunction construct in CDK and was impressed by how easily it packaged up all my dependencies. Very excited about the potential of adding SAM to making local testing easier!

I just tried running `sam-beta-cdk` directly in an existing project that uses CDK to set up an API Gateway and Lambda function in Python 3.8 and ran info a few issues so far (I haven't spent too much time so any of these could be user error):
* My app file (in `bin`) defines two stacks in two accounts. With regular `cdk` I can select which stack to build by passing it as a command line parameter. When using `sam-beta-cdk` I can't seem to make it build only one stack.
* After making my appfile define only one stack, `sam-beta-cdk build` errors out with `Invalid executable for python at /usr/bin/python`. When building with CDK, it uses pipenv and doesn't have this issue.
* Lambda invocations attempted via `sam-beta-cdk local invoke` and `sam-beta-cdk local start-api` time out, which may or may not be related to the previous issue with building python

**Comment by malbertus** [comment] 2021-09-15 04:15
I've found it unusable at the moment. The CDK L2 constructs sometimes create 'helper' lambdas for configuration, and sam-beta-cdk tries to compile these during the build process, which fails. For example, adding a CloudWatch log group as the target of an EventBridge rule in CDK creates a Lambda that creates a Custom::CloudwatchLogResourcePolicy, and SAM attempts to build this Lambda, which fails.

Have raised issue #3192

**Comment by rupe120** [comment] 2021-10-30 12:37
Why does a Python CDK project initialized with SAM not use a Virtual Environment like is used when initializing a Python CDK project with the CDK cli? Does the `sam build` manage that aspect for you?

**Comment by rupe120** [comment] 2021-10-30 13:53
I just created a bug for `sam-beta-cdk build --profile` . The switch appears to be ignored. 

https://github.com/aws/aws-sam-cli/issues/3427

**Comment by matthewthomasgb** [comment] 2021-11-02 22:23
Hey, I'm using M1 Pro on Monterey, `brew install aws-sam-cli-beta-cdk` returns cannot be found. Strangely it works on my old mac with Mojave. 

`Warning: No available formula or cask with the name "aws-sam-cli-beta-cdk".`

Any advice is greatly appreciated, thanks

**Comment by iRoachie** [comment] 2021-11-03 01:30
@matthewthomasgb can try `brew install --build-from-source aws-sam-cli-beta-cdk

**Comment by matthewthomasgb** [comment] 2021-11-03 20:56
@iRoachie thanks for getting back to me, unfortunately I get the same result - 
`
 homebrew git:(stable) brew install --build-from-source aws-sam-cli-beta-cdk
Warning: No available formula or cask with the name "aws-sam-cli-beta-cdk".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
`

**Comment by moelasmar** [comment] 2021-11-10 22:21
@matthewthomasgb .. thanks for raising this issue .. There is already [a requested feature](https://github.com/aws/aws-sam-cli/issues/2673) asking for M1 Mac homebrew bottle. This will fix the SAM CLI installation in M1 mac. Please +1 this issue to prioritize it.

**Comment by moelasmar** [comment] 2021-11-10 22:29
@sonya .. thanks for sharing your feedback .. can I ask you to give us more info about the `sam-beta-cdk local invoke` and `sam-beta-cdk local start-api` issues, if it is possible to refer us to some github project that we can use to reproduce this issue. 
Regarding the `sam-beta-cdk build` issue, we need to know more about your use case of using `sam-beta-cdk build` to build your CDK project. Was it because you just want to try the beta version, or you was not be able to build your lambda functions using CDK build features ([Assets bundling option](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.BundlingOptions.html), and Runtime Lambda Function Constructs [Python](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-python.PythonFunction.html), [nodeJs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-nodejs.NodejsFunction.html), [go](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-go.GoFunction.html)), and you need to make use of `sam build` features.

**Comment by cdanhowell** [comment] 2021-11-16 18:50
First - I absolutely love this and sincerely appreciate the addition of this integration.

I am currently running into an issue that appears to have been resolved for the released versions. I suspect that this beta may be outdated compared to release, but I'm not sure. The referenced issue is #3243.

Secondly, I noticed something interesting. The CDK cli and SAM cli use two different .cdk-out folders. If possible, it would be great if sam-cli would check for a .cdk-out that is in the current working directory before creating its .sam-cli/.cdk-out directory (at least for cdk projects).

Third, I am wondering how well this will play together with CDK deployed apps. I was noticing in my testing that I was getting an invalid ARN for the KMS service (and possibly others, though I didn't check). The setup is this:

* I have cdk app that I have deployed to a dev/staging environment.
* The app creates several resources, including an S3 bucket, an SSM secret, a KMS key, and an RDS database in addition to the lambda function.
* When running sam local invoke [function name], the ARN that is passed for the KMS key does not resolve to a valid resource in my account, thus when accessing the resource to encrypt a string, it fails.

The workaround would be to develop the lambda functionality with sam deploy then use cdk in the pipelines. **That is a valid solution for us,** though I think having the two CLI's play nicely would be extremely helpful in a number of scenarios.

Thanks again for pushing something like this forward!

**Comment by praneetap** [comment] 2021-11-18 06:44
> First - I absolutely love this and sincerely appreciate the addition of this integration.
> 
> I am currently running into an issue that appears to have been resolved for the released versions. I suspect that this beta may be outdated compared to release, but I'm not sure. The referenced issue is #3243.
> 
> Secondly, I noticed something interesting. The CDK cli and SAM cli use two different .cdk-out folders. If possible, it would be great if sam-cli would check for a .cdk-out that is in the current working directory before creating its .sam-cli/.cdk-out directory (at least for cdk projects).
> 
> Third, I am wondering how well this will play together with CDK deployed apps. I was noticing in my testing that I was getting an invalid ARN for the KMS service (and possibly others, though I didn't check). The setup is this:
> 
>     * I have cdk app that I have deployed to a dev/staging environment.
> 
>     * The app creates several resources, including an S3 bucket, an SSM secret, a KMS key, and an RDS database in addition to the lambda function.
> 
>     * When running sam local invoke [function name], the ARN that is passed for the KMS key does not resolve to a valid resource in my account, thus when accessing the resource to encrypt a string, it fails.
> 
> 
> The workaround would be to develop the lambda functionality with sam deploy then use cdk in the pipelines. **That is a valid solution for us,** though I think having the two CLI's play nicely would be extremely helpful in a number of scenarios.
> 
> Thanks again for pushing something like this forward!

Hey @cdanhowell , thank you so much for the feedback! I would love to get on a call and understand your use cases better, please [reach out to me via DM](https://twitter.com/praneetaprakash) and I will set up a call!

**Comment by wazcov** [comment] 2021-11-18 14:36
> @iRoachie thanks for getting back to me, unfortunately I get the same result - `homebrew git:(stable) brew install --build-from-source aws-sam-cli-beta-cdk Warning: No available formula or cask with the name "aws-sam-cli-beta-cdk". ==> Searching for similarly named formulae... Error: No similarly named formulae found. ==> Searching for a previously deleted formula (in the last month)... Error: No previously deleted formula found. ==> Searching taps on GitHub... Error: No formulae found in taps.`

same

**Comment by Kelvijn** [comment] 2021-11-23 22:27
> > @iRoachie thanks for getting back to me, unfortunately I get the same result - `homebrew git:(stable) brew install --build-from-source aws-sam-cli-beta-cdk Warning: No available formula or cask with the name "aws-sam-cli-beta-cdk". ==> Searching for similarly named formulae... Error: No similarly named formulae found. ==> Searching for a previously deleted formula (in the last month)... Error: No previously deleted formula found. ==> Searching taps on GitHub... Error: No formulae found in taps.`
> 
> same

Same, does anyone have a temp solution instead of deploying to aws for each code change? 😓😭

**Comment by moelasmar** [comment] 2021-11-23 23:27
@kelvijn .. is you issue related to install the CDK beta version on M1 Mac? .. I do not get your question about a deploying to aws for each code change?

**Comment by jcaito** [comment] 2021-11-24 01:13
@Kelvijn / @wazcov / @matthewthomasdev 

Run `brew tap aws/tap` before running `brew install aws-sam-cli-beta-cdk` and that should work. You should be able to verify it is working by doing a `brew search aws-sam-cli`

**Comment by moelasmar** [comment] 2021-11-24 10:11
@jcaito .. thanks for your help.

I verified that it is working on Big Sur mac with the following details
```
administrator@46559 ~ % sysctl -a | grep machdep.cpu
machdep.cpu.brand_string: Apple M1
machdep.cpu.core_count: 8
machdep.cpu.cores_per_package: 8
machdep.cpu.logical_per_package: 8
machdep.cpu.thread_count: 8
administrator@46559 ~ % system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 11.6 (20G165)
      Kernel Version: Darwin 20.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: 46559
      User Name: administrator (administrator)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6 days 6:37
```

I just did as explained by @jcaito 
```
administrator@46559 ~ % brew tap aws/tap
==> Tapping aws/tap
Cloning into '/opt/homebrew/Library/Taps/aws/homebrew-tap'...
....
Tapped 15 formulae (48 files, 516.9KB).

administrator@46559 ~ % brew install aws-sam-cli-beta-cdk
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/manifests/1.22
 ...... 
🍺  /opt/homebrew/Cellar/aws-sam-cli-beta-cdk/202108311500: 6,614 files, 103.4MB, built in 29 seconds

administrator@46559 ~ % sam-beta-cdk --version
SAM CLI, version 1.29.0.dev202108311500
```

@Kelvijn @wazcov @matthewthomasdev .. could you please confirm if this fixes your issue, or you still have installation issue.

**Comment by godacre** [comment] 2021-12-09 13:56
Thanks very much to the team for the efforts on SAM+CDK local testing integration to date. My team and I are hoping to migrate from Severless Framework to AWS CDK. Whilst CDK doesn't natively provide local development testing functionality whereas Serverless Framework does, I was hoping to be able to use sam-beta-cdk to fill the gaps for our Lambda deployments.

Something I came across during testing however is that presently sam-beta-cdk only supports local testing of Lambda functions created with the [aws_lambda](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda-readme.html) CDK construct: 
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-cdk-testing.html 
![image](https://user-images.githubusercontent.com/48926225/145408682-88f68545-0698-431e-9042-50dd714264ad.png)

During refactoring some of our Lambda apps from Serverless Framework -> AWS CDK, I decided that ideally we would use the [aws_lambda_nodejs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html) construct as it allows for much simpler dependency management and project structuring of nodejs functions.

I was wondering if anyone would be able to point me in the right direction regarding the reasons for the current limitation and if providing support for other Lambda L2 constructs is on the roadmap?

Thanks in advance!

**Comment by rupe120** [comment] 2021-12-09 20:23
I'm receiving the error `Need to perform AWS calls for account ###, but no credentials have been configured` when I am trying run `build` with `ec2.Vpc.from_lookup()` in a stack. 

I tried both the `--profile` switch and the access key environment variables, and received the same error with both.

How do I provide the credentials?

**Comment by iRoachie** [comment] 2021-12-15 03:56
Is there anyway to update the sam-cli version? Seems sam-beta-cdk is stuck on 1.29.0

**Comment by iRoachie** [comment] 2022-01-06 16:47
Hey @praneetap I just saw release [1.37.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.37.0). Does this mean that aws-sam-cli-beta-cdk is no longer needed?

**Comment by praneetap** [comment] 2022-01-06 18:59
Yes! You should be able to get it on mainline! Let us know what you think :)

**Comment by moelasmar** [comment] 2022-01-21 00:17
Thanks all for your feedback on the beta version. The CDK support got released in version [1.37.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.37.0). 

Please check the [CDK support documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-cdk.html) for the updated information about the CDK support usage. If you have any questions, features, or issue, please do not hesitate to open a github issue.

**Closed by moelasmar** 2022-01-21 00:17 UTC
Labels: stage/needs-feedback

**Comment by moelasmar** [comment] 2022-06-07 07:11
Sorry @kenchoong, unfortunately `sam local start-api` does not support API Gateway Authorizer right now.

**Comment by niluckne** [comment] 2023-01-31 08:42
Can you inform on your planning wrt 

> and in the future, package applications

That would be great.
