### ISSUE TITLE
sam local generate-event does not escape quotes  producing invalid JSON 

### ISSUE THREAD

**Issue by marcinkoziej** [aws/aws-sam-cli#2848] opened 2021-05-03 11:15 UTC
### Description:
sam local generate-event does not escape quotes  producing invalid JSON . It does not escape newlines either.

### Steps to reproduce:

`sam local generate-event sqs receive-message --body '{"hello": "world"}' `

### Observed result:
```
{
  "Records": [
    {
      "messageId": "19dd0b57-b21e-4ac1-bd88-01bbb068cb78",
      "receiptHandle": "MessageReceiptHandle",
      "body": "{"hello": "world"}",
      "attributes": {
        "ApproximateReceiveCount": "1",
        "SentTimestamp": "1523232000000",
        "SenderId": "123456789012",
        "ApproximateFirstReceiveTimestamp": "1523232000001"
      },
      "messageAttributes": {},
      "md5OfBody": "49dfdd54b01cbcd2d2ab5e9e5ee6b9b9",
      "eventSource": "aws:sqs",
      "eventSourceARN": "arn:aws:sqs:us-east-1:123456789012:MyQueue",
      "awsRegion": "us-east-1"
    }
  ]
}
```

### Expected result:
```
{
  "Records": [
    {
      "messageId": "19dd0b57-b21e-4ac1-bd88-01bbb068cb78",
      "receiptHandle": "MessageReceiptHandle",
      "body": "{\"hello\": \"world\"}",
      "attributes": {
        "ApproximateReceiveCount": "1",
        "SentTimestamp": "1523232000000",
        "SenderId": "123456789012",
        "ApproximateFirstReceiveTimestamp": "1523232000001"
      },
      "messageAttributes": {},
      "md5OfBody": "49dfdd54b01cbcd2d2ab5e9e5ee6b9b9",
      "eventSource": "aws:sqs",
      "eventSourceARN": "arn:aws:sqs:us-east-1:123456789012:MyQueue",
      "awsRegion": "us-east-1"
    }
  ]
}
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu Linux
2. SAM CLI, version 1.23.0
3. AWS region: N/A

**Comment by c2tarun** [comment] 2021-10-04 13:53
Hi @marcinkoziej,

Thanks for reporting this, however this is by design. We cannot assume that `body` is always JSON to escape quotes. So we simply accept body as a string and put it in the generated template.

I am closing this issue for now, please feel free to re-open if you have more questions/suggestions.

Thanks
Tarun

**Closed by c2tarun** 2021-10-04 13:53 UTC
Labels: type/bug, area/local/generate-event
