### ISSUE TITLE
Bug: Powershell not showing prompts to input in sam deploy

### ISSUE THREAD

**Issue by psambit9791** [aws/aws-sam-cli#4999] opened 2023-04-11 08:12 UTC
### Description:
When I run `sam deploy -g` or just `sam deploy`, Powershell does not prompt me for any inputs.

### Steps to reproduce:
1. Install Docker Desktop (for Windows)
2. Run Powershell in administrator mode
3. `sam build --use-container ` to build the code
4. `sam deploy -g`

### Observed result:

![sam-stuck](https://user-images.githubusercontent.com/25612092/231097045-365e5a4b-9d1d-424c-8f30-bd2b1c8cebb0.png)
No prompt shown to move ahead for `sam deploy -g`.

The same happens for `sam deploy`, but it is stuck at the Changeset confirmation prompt.

### Expected result:

`sam dpeloy -g` should show a prompt to add stack details etc.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 1.78.0
6. AWS region: eu-west-2

```
{
  "version": "1.78.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
```

**Comment by jfuss** [comment] 2023-04-12 13:46
@psambit9791 Thanks for reporting. I checked the commits and nothing jumped out to me. If you stall a previous version of SAM CLI, do you see the same behavior?

Can you try adding `--no-confirm-changeset` to `sam deploy`? Just want to verify that things work if no prompts are there.

**Comment by psambit9791** [comment] 2023-04-16 18:35
@jfuss is there a way to do run the sam deploy command without the artefacts being uploaded and the changesets being deployed? The reason I ask is so I can try this on the same codebase where the issue was encountered.

**Comment by jfuss** [comment] 2023-04-17 15:52
@psambit9791 
> is there a way to do run the sam deploy command without the artefacts being uploaded and the changesets being deployed?

There is a couple ways you can do this, you can run `sam package` directly then `sam deploy`. `sam deploy` could be prompting because of fields set in the `samconfig.toml` (specifically the `no-confirm-changeset` or `confirm-changeset`.

You can also upload the artifacts directly and have the template point to the s3 location. I wouldn't recommend this unless you have some specific use-case, because you are effectively doing `sam package`.

SAM CLI will always use changesets, so there is no way to bypass that at the moment. However, `sam deploy` shouldn't prompt by default. So my guess is your `samconfig.toml` is causing the prompts to be displayed on `sam deploy` (without `-g`).

Still doesn't answer why your prompts are getting stuck though.

**Comment by psambit9791** [comment] 2023-04-23 00:32
@jfuss Can confirm that using `no-confirm-changeset` allows me to deploy. Seems like its just the prompt which is creating the issue. The prompt never shows up so it looks like it is just stuck.

**Comment by lucashuy** [comment] 2023-06-23 17:04
Sorry about the delay in response, unfortunately I am not able to reproduce this issue on my system. Does this still happen with the latest release (1.88.0 at the time of writing)? Additionally, does this happen to any other commands that have a guided work flow (`sam init`, or `sam pipeline init`)?

This is the Powershell version on my system (regular admin Powershell window):
```
PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by lucashuy** [comment] 2023-07-03 18:24
Closing as unfortunately the team is not able to reproduce this issue. Please create a new issue if this still persists in any future versions.

**Closed by lucashuy** 2023-07-03 18:24 UTC
Labels: type/bug, platform/windows, blocked/more-info-needed, area/deploy, stage/needs-investigation, stage/bug-repro
