### ISSUE TITLE
VpcEndpointIds getting removed from private APIs post stack update. Stack shows drifted.

### ISSUE THREAD

**Issue by saurabhshri** [aws/aws-sam-cli#2353] opened 2020-11-05 07:11 UTC
### Description:

I have a private API that is being provisioned using SAM. Here's how it looks 

```
PrivateApiResource:
    Type: AWS::Serverless::Api
    Tags:
      Application: !Ref Application
    Properties:
      Name: !Sub ${Env}-${Application}-PrivateApiResource
      StageName: prod
      EndpointConfiguration:
        Type: PRIVATE
        VPCEndpointIds:
          - !FindInMap [ EnvConfig, !Ref Env, VPCEndpointAPI ]
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: '*'
              Action: execute-api:Invoke
              Resource: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*"
            - Effect: Deny
              Principal: '*'
              Action: execute-api:Invoke
              Resource: "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*"
              Condition:
                StringNotEquals:
                  aws:SourceVpce: !FindInMap [ EnvConfig, !Ref Env, VPCEndpointAPI ]
```

I have a lambda that has the above API as event resource : 

```
SayHelloPrivately:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./target/index.sayHelloPrivatelyHandler
      Runtime: nodejs12.x
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Sub ${Application}/latest-lambda.zip
      Events:
        SayHelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref PrivateApiResource
```

This worked and I was able to access /hello endpoint when on VPC and it times out when not in VPC.

Now anytime stack updates and there's a related update to the API resource, like adding a new lambda with different endpoint, the VPCEndpointIds and Tags seems to be getting removed randomly. I am not exactly sure what exact event triggers it. But most recently, doing as little adding a third lambda lead to removal of both tags and VPCe.

CloudFormation stack's template tab shows that the template still has VPCe. Stack shows it's drifted and both are removed. 

- template, as it appears in CloudFormation stack tab

<img width="584" alt="Screenshot 2020-11-05 at 12 28 52 PM" src="https://user-images.githubusercontent.com/12415700/98208380-310b9c80-1f63-11eb-8d0e-a177d5363a90.png">

- Stack drift : 

<img width="1323" alt="Screenshot 2020-11-05 at 12 30 07 PM" src="https://user-images.githubusercontent.com/12415700/98208428-454f9980-1f63-11eb-8706-a8a2fe4bbec1.png">

- VPCe removed 

<img width="1265" alt="Screenshot 2020-11-05 at 12 28 18 PM" src="https://user-images.githubusercontent.com/12415700/98208478-5d271d80-1f63-11eb-8519-2fd0c2ac12a0.png">

Nothing related to VPCEndpointIds/Tags were done. Even the API resource was untouched in stack update. Only a new lambda was created which added a new endpoint to the API resource, similar to how it's done in `SayHelloPrivately` above.

### Steps to reproduce:

Follow the steps in description.

### Observed result:

VPCEndpointIds from private API and tags are removed. Stack shows drifted.

### Expected result:

Nothing should have changed with this aspect. 

**NOTE** :  This has happened more than once.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux 2
2. `sam --version`: 1.1.0

Almost forgot to tag @awsjeffg ! Let me know if I can provide any other information. Thanks!

**Comment by saurabhshri** [comment] 2020-11-05 11:28
If it helps, I tried looking through CloudTrail to see if I can spot something. 

<img width="1389" alt="Screenshot 2020-11-05 at 4 52 42 PM" src="https://user-images.githubusercontent.com/12415700/98235142-6e822100-1f87-11eb-988e-ab0e5eff95d6.png">

1. When it was working, I can see in event `UpdateRestApi November 03, 2020, 19:21:30 (UTC+05:30)` (the bottom most entry) the following : 

```
"requestParameters": {
        "restApiId": "xxxxxxxx",
        "updateRestApiInput": {
            "patchOperations": [
                {
                    "path": "/endpointConfiguration/types/EDGE",
                    "value": "PRIVATE",
                    "op": "replace"
                },
                {
                    "path": "/name",
                    "value": "dev-xxxxx-PrivateApiResource",
                    "op": "replace"
                },
                {
                    "path": "/endpointConfiguration/vpcEndpointIds",
                    "value": "vpce-xxxxxx",
                    "op": "add"
                }
            ]
        },
        "template": false
    },

```

and 

```
        "endpointConfiguration": {
            "vpcEndpointIds": [
                "vpce-xxxxx"
            ],
            "types": [
                "PRIVATE"
            ],
            "ipv6": false
        },
```

Later when another lambda was added, the new event  `UpdateRestApi (November 03, 2020, 21:24:42 (UTC+05:30)` (third from top) has the following : 

```
"requestParameters": {
        "restApiId": "xxxxxx",
        "updateRestApiInput": {
            "patchOperations": [
                {
                    "path": "/name",
                    "value": "dev-xxxx-PrivateApiResource",
                    "op": "replace"
                }
            ]
        },
        "template": false
    },
```

and 

```
        "endpointConfiguration": {
            "types": [
                "PRIVATE"
            ],
            "ipv6": false
        },
```

**Comment by hawflau** [comment] 2020-11-05 19:34
Thanks for providing the details. I'll try to reproduce it

**Comment by saurabhshri** [comment] 2020-11-06 10:56
Thank you @hawflau & @awsjeffg. Let me know how can I help.

**Comment by hawflau** [comment] 2020-11-06 17:46
Hey @saurabhshri, I couldn't reproduce the result for the `Tags` property. It seems you placed in at the wrong place in your example. It should be placed under `Properties` instead. Also the tags will be created under the `AWS::ApiGateway::Stage` resource.

**Comment by saurabhshri** [comment] 2020-11-06 17:55
@hawflau you're absolutely right, Tags are indeed not at correct place. The only reason I pointed out tags was I saw it in Drift while I was checking vanished VPCEndpointIds (hence the title only mentioned VPCe). I never verified Tags from the console. Sorry if it threw you off. Any luck with VPCe?

**Comment by hawflau** [comment] 2020-11-06 17:55
However, I managed to reproduce the result on `VPCEndpointIds` getting removed. The problem doesn't seem to be related to SAM or SAM CLI though - the property was not gone after SAM translation.

So I did another experiment - I created a pure CloudFormation template with a `AWS::ApiGateway::RestApi` resource with `VPCEndpointIds` and swagger defined; created a stack using this template; updated swagger in the template; created changeset and executed it. And `VPCEndpointIds` was gone! Note that in the changeset, there was not any mentioning about the removal of the property.

**Comment by saurabhshri** [comment] 2020-11-06 18:06
> However, I managed to reproduce the result on VPCEndpointIds getting removed. 

Thank you @hawflau, for a moment there I thought I was going crazy. :) 

> The problem doesn't seem to be related to SAM or SAM CLI though - the property was not gone after SAM translation.

Correct, I assumed so too, because the translate CF template seemed to have VPCEndpointIds as expected..

> So I did another experiment - I created a pure CloudFormation template with a AWS::ApiGateway::RestApi resource with VPCEndpointIds and swagger defined; created a stack using this template; updated swagger in the template; created changeset and executed it. And VPCEndpointIds was gone! Note that in the changeset, there was not any mentioning about the removal of the property.

Sounds like it matches more or less my experience. Not changing anything related to VPCe, but any modification to API be it adding another endpoint -- may lead to removal of the VPCe. 

So, does that mean it's an issue with CF? Do you know what would be the next steps here.

**Comment by awsjeffg** [comment] 2020-11-06 18:37
> So, does that mean it's an issue with CF? Do you know what would be the next steps here.

@saurabhshri thanks again for reporting this. You are correct, we are for now considering this a possible Cloudformation issue and are creating an internal ticket with that team, however we will keep this issue open for the time being and update here as events warrant.

**Comment by saurabhshri** [comment] 2020-11-06 19:08
Thank you for looking into this so quickly and raising it internally @awsjeffg  @hawflau !

> however we will keep this issue open for the time being and update here as events warrant.

That is really helpful, thank you. Let me know if I can be of any help.

**Comment by srinadhv9** [comment] 2020-12-04 23:11
Ran into the exact same issue today.

**Comment by nakedcity** [comment] 2021-01-12 12:24
any update on this? or CF ref ticket?

**Comment by saurabhshri** [comment] 2021-02-09 08:20
An update for folks facing the same issue : we opened a support ticket since this was restricting us in moving forward with private api gateways in production. We got a response acknowledging that this is a known behaviour and that there is already an internal ticket on it which the service team is actively working on.

> ... this is a known behavior which occurs when the stack is updated. CloudFormation makes a PutRestApi [1] call in overwrite mode, and then makes an UpdateRestApiCall[2] without adding the VPC endpoint parameter in the request. Hence, this leads to disassociation of VPC endpoints from the API Gateway.

> References:-
> [1] https://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html
> [2] https://docs.aws.amazon.com/cli/latest/reference/apigateway/update-rest-api.html

Unfortunately, they couldn't provide an ETA on the fix, but suggested a workaround to manually reattach the VPC Endpoint via the API Gateway settings page.

> ... This can be done using the following steps:
>
>   1) Navigate to the API Gateway Console
>  2) Select the API in question
>   3) Navigate to "Settings"
>  4) Under "Endpoint Configuration" enter the VPC Endpoint ID in the text box, and press the "Add" button.
>  5) Scroll to the bottom of the Settings page and click the "Save Changes" button.

Hopefully it helpful to those who are trying to figure out the issue and fix from their end.

**Comment by jaglade** [comment] 2021-05-20 16:35
This issue has been open since November and is production impacting?  I am floored by the fact that aws would allow this to go on for so long. The behavior i have seen has been random in that some times the vpc endpoint gets removed and other times it does not.  On top of that, after i make the manual change it sometimes takes a moment to go into effect.  During this time, my private api gateway endpoint is unreachable and my production system is down.  
I just got the same advice from support to use the manual workaround and i couldn't believe what i was reading.  CloudFormation/SAM is an automation tool, why would we be instructed to followup an automation tool with a manual step? Crazy.  This has been an issue for more than six months and i would hope that something production impacting would have a higher priority.  
Please provide an update on when we can expect a fix.

**Comment by sapessi** [comment] 2021-06-18 17:08
Hi @jaglade, apologies for the delay. The fix for the issue completed deployment earlier this month.

**Comment by hawflau** [comment] 2021-06-21 20:51
Closing as the issue has been fixed. Feel free to reopen if there's still issue.

**Comment by bkitch21** [comment] 2021-07-16 15:35
@sapessi You mention this being fixed and it completing deployment earlier this month. AWS Support is saying that this is only fixed for stacks created after March 29, 2021 and that stacks created before then you have to manually specify 'Merge' as the Mode in the properties on the template. However 'Mode' does not exist in SAM as a property at the moment. Their solution from there was to manually add back in the endpoint ID after deploying via the console. However, this means that on production deployments all of our private API gateways will have downtime between the deployment and going into console, manually adding back in the endpoint, and waiting for it to propogate. 

If this is fixed, what are we missing here? I see a PR in release 1.38.0 for the SAM translation that adds in the 'Mode' property - which would help - but what's the fix that you referenced being complete earlier this month?

**Comment by RONITKHUNGAR10** [comment] 2021-07-16 16:54
++ @Akash Verma ***@***.***>

**Comment by andrewhopper** [comment] 2021-08-05 22:36
Fyi, Mode has now been added to SAM (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-mode).

If you explicitly specify `Mode: merge` it should no longer remove VpcEndpoints.

Make sure to update your sam-cli to get the latest version.

`brew upgrade aws-sam-cli`

**Comment by saurabhshri** [comment] 2021-08-12 08:29
Hello @hawflau and @sapessi! We are seeing this issue yet again since last two days (or at least that's when we noticed it in our lower environments), did something change about this?

If I understand correctly, the `Mode` property is only needed if OpenAPI is used to define the API. The example in the original issue comment doesn't use OpenAPI, so it should not be needed, right?

Or due to translation to CF, it becomes a required property?

**Comment by hawflau** [comment] 2021-08-12 17:02
Hey @saurabhshri, I've tried to reproduce it once again - I noticed that CloudFormation still showed drift in the api resource. But when I clicked into the api and checked its Endpoint Configuration, the VPC Endpoint ID was still here. Can you verify if that's the same for you?

Feel free to re-open the issue if that's not the case.

**Comment by saurabhshri** [comment] 2021-08-13 06:21
Hi @hawflau, unfortunately no. We are back to VPCe getting removed, exact same scenario from my initial post in this issue (it's the same setup). Our stack shows drifted and the API shows no VPCe attached. One of the API consumers reported that they are not able to resolve the endpoint URL (they use the URL with route53 alias to call the API) -- that's how we realised the issue is back.

- Here's the stack drift showing the exact difference : 

<img width="2439" alt="drift" src="https://user-images.githubusercontent.com/12415700/129313263-b9e49db9-b856-4762-8c9c-6a562cdf5a23.png">

- Here's the API settings page showing no VPCe

<img width="1675" alt="api-gw-settings" src="https://user-images.githubusercontent.com/12415700/129313320-94f72d1d-d608-4bd2-80ea-381a6247e5a7.png">

- CloudTrail Event : 

<img width="2215" alt="cloudtrail" src="https://user-images.githubusercontent.com/12415700/129313353-a27f10ab-88a9-4be6-bd2e-6d500075acb8.png">
<img width="347" alt="cloudtrail-body" src="https://user-images.githubusercontent.com/12415700/129313366-58cf5397-d32a-4dd6-a33a-13a7656db072.png">

Let me know if you need any other information too (like API ID), happy to provide them.

Also, mind re-opening the issue? I do not seem to have an option to do that.

**Comment by hawflau** [comment] 2021-08-13 15:29
Sure, re-opening the issue

**Comment by hawflau** [comment] 2021-08-13 20:59
@saurabhshri is your stack newly created (after March 29, 2021)? If not, I'd suggest you to try set the `Mode` property in your `AWS::Serverless::Api` resource. 

Looking back at your original example, you created `RestApi` events in your `AWS::Severless::Function` resource. Because of this, SAM created an OpenApi definition in the corresponding Api resource. 

In my latest attempt, I set `Mode` to `"overwrite"` and deployed the stack - the VPC Endpoint ID is gone. 
Then, when I set `Mode` to `"merge"` and rotated to use another VPC Endpoint ID, the new VPC Endpoint ID is added.
(The reason for using a new VPC Endpoint ID was probably CloudFormation or ApiGateway thought there was no change in that attribute, thus doing no change)

Let us know if that helps!

**Comment by xazhao** [comment] 2021-08-16 04:16
Closing this issue after syncing with @hawflau 

Feel free to reopen this if you have any further questions.

**Closed by xazhao** 2021-08-16 04:16 UTC
Labels: stage/needs-investigation, stage/pm-review

**Comment by GeeWee** [comment] 2023-11-01 12:27
@hawflau I think I've encountered a variation of this same issue running `sam sync` - my VPC seems to be arbitrarily removed from my lambda. I cannot set `Mode` as that does not seem to be a property on `AWS::Serverless::Function`

I've added the VPC manually via the UI, and running `sam sync` seems to arbitrarily remove it.
