### ISSUE TITLE
Bug: sam build - TypeError

### ISSUE THREAD

**Issue by fortivi002** [aws/aws-sam-cli#5247] opened 2023-06-02 13:35 UTC
### Description:

When trying to build with `sam build --use-container`  or ` sam build ` I have an error. I tried it with several python version for the hello_world template project. Everything that I tried to build or run locally seems to give me the same error. Also I have the same error with the following command `sam --info`. I tried installing various version of python but I always seem to have this error. 
 

### Steps to reproduce:

I followed the steps of the Sam Workshop  of this link : [https://catalog.workshops.aws/complete-aws-sam/en-US/module-1-sam-setup](url). The only difference is that I am using the Image version as I don't have the right python installed for it. 

`sam init`

```

You can preselect a particular runtime or package type when using the `sam init` experience.
Call `sam init --help` to learn more.

Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 1

Choose an AWS Quick Start application template
        1 - Hello World Example
        2 - Data processing
        3 - Hello World Example with Powertools for AWS Lambda
        4 - Multi-step workflow
        5 - Scheduled task
        6 - Standalone function
        7 - Serverless API
        8 - Infrastructure event management
        9 - Lambda Response Streaming
        10 - Serverless Connector Hello World Example
        11 - Multi-step workflow with Connectors
        12 - Lambda EFS example
        13 - DynamoDB Example
        14 - Machine Learning
Template: 1

Use the most popular runtime and package type? (Python and zip) [y/N]: n

Which runtime would you like to use?
        1 - aot.dotnet7 (provided.al2)
        2 - dotnet6
        3 - go1.x
        4 - go (provided.al2)
        5 - graalvm.java11 (provided.al2)
        6 - graalvm.java17 (provided.al2)
        7 - java17
        8 - java11
        9 - java8.al2
        10 - java8
        11 - nodejs18.x
        12 - nodejs16.x
        13 - nodejs14.x
        14 - nodejs12.x
        15 - python3.9
        16 - python3.8
        17 - python3.7
        18 - python3.10
        19 - ruby2.7
        20 - rust (provided.al2)
Runtime: 17

What package type would you like to use?
        1 - Zip
        2 - Image
Package type: 2

Based on your selections, the only dependency manager available is pip.
We will proceed copying the template using pip.

Would you like to enable X-Ray tracing on the function(s) in your application?  [y/N]: n

Would you like to enable monitoring using CloudWatch Application Insights?
For more info, please view https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-application-insights.html [y/N]: n

Project name [sam-app]:

    -----------------------
    Generating application:
    -----------------------
    Name: sam-app
    Base Image: amazon/python3.7-base
    Architectures: x86_64
    Dependency Manager: pip
    Output Directory: .
    Configuration file: sam-app\samconfig.toml

    Next steps can be found in the README file at sam-app\README.md


Commands you can use next
=========================
[*] Create pipeline: cd sam-app && sam pipeline init --bootstrap
[*] Validate SAM template: cd sam-app && sam validate
[*] Test Function in the Cloud: cd sam-app && sam sync --stack-name {stack-name} --watch
```
Once it's done creating the project i'm trying to build in local with my docker open with the command `sam build --use-container`.

### Observed result:

```

2023-06-02 09:20:43,639 | Config file location: C:\Users\vince\Documents\Git\Serverless\sam-app\samconfig.toml
2023-06-02 09:20:43,639 | Loading configuration values from [default.['build'].parameters] (env.command_name.section) in
config file at 'C:\Users\vince\Documents\Git\Serverless\sam-app\samconfig.toml'...
2023-06-02 09:20:43,639 | Configuration values successfully loaded.
2023-06-02 09:20:43,655 | Configuration values are: {'stack_name': 'sam-app', 'parallel': True}
2023-06-02 09:20:43,655 | Using SAM Template at C:\Users\vince\Documents\Git\Serverless\sam-app\template.yaml
2023-06-02 09:20:43,670 | Using config file: samconfig.toml, config environment: default
2023-06-02 09:20:43,670 | Expand command line arguments to:
2023-06-02 09:20:43,670 | --template_file=C:\Users\vince\Documents\Git\Serverless\sam-app\template.yaml --use_container
--parallel --mount_with=READ --build_dir=.aws-sam\build --cache_dir=.aws-sam\cache
2023-06-02 09:20:44,155 | 'build' command is called
2023-06-02 09:20:44,170 | Starting Build inside a container
2023-06-02 09:20:44,170 | No Parameters detected in the template
2023-06-02 09:20:44,186 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we
will use the resource logical id as the resource id
2023-06-02 09:20:44,202 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will
use the resource logical id as the resource id
2023-06-02 09:20:44,202 | 0 stacks found in the template
2023-06-02 09:20:44,202 | No Parameters detected in the template
2023-06-02 09:20:44,217 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we
will use the resource logical id as the resource id
2023-06-02 09:20:44,217 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will
use the resource logical id as the resource id
2023-06-02 09:20:44,217 | 2 resources found in the stack
2023-06-02 09:20:44,217 | Found Serverless function with name='HelloWorldFunction' and ImageUri='None'
2023-06-02 09:20:44,217 | --base-dir is not presented, adjusting uri ./hello_world relative to
C:\Users\vince\Documents\Git\Serverless\sam-app\template.yaml
2023-06-02 09:20:44,217 | --base-dir is not presented, adjusting uri . relative to
C:\Users\vince\Documents\Git\Serverless\sam-app\template.yaml
2023-06-02 09:20:44,217 | 2 resources found in the stack
2023-06-02 09:20:44,217 | Found Serverless function with name='HelloWorldFunction' and ImageUri='None'
2023-06-02 09:20:44,233 | Error occurred while trying to track an event: Event 'BuildFunctionRuntime' does not accept
value 'None'.
2023-06-02 09:20:44,233 | Instantiating build definitions
2023-06-02 09:20:44,233 | Unique function build definition found, adding as new (Function Build Definition:
BuildDefinition(None, C:\Users\vince\Documents\Git\Serverless\sam-app, Image, , 2c9fcff0-1a2d-474d-a6c5-d3fe02f02eec,
{'DockerTag': 'python3.7-v1', 'DockerContext': 'C:\\Users\\vince\\Documents\\Git\\Serverless\\sam-app\\hello_world',
'Dockerfile': 'Dockerfile'}, {}, x86_64, []), Function: Function(function_id='HelloWorldFunction',
name='HelloWorldFunction', functionname='HelloWorldFunction', runtime=None, memory=128, timeout=3, handler=None,
imageuri=None, packagetype='Image', imageconfig=None, codeuri='C:\\Users\\vince\\Documents\\Git\\Serverless\\sam-app',
environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello',
'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'DockerTag': 'python3.7-v1', 'DockerContext':
'C:\\Users\\vince\\Documents\\Git\\Serverless\\sam-app\\hello_world', 'Dockerfile': 'Dockerfile', 'SamResourceId':
'HelloWorldFunction'}, inlinecode=None, codesign_config_arn=None, architectures=None, function_url_config=None,
stack_path='', runtime_management_config=None))
2023-06-02 09:20:44,248 | Async execution started
2023-06-02 09:20:44,248 | Invoking function functools.partial(<bound method
ParallelBuildStrategy.build_single_function_definition of <samcli.lib.build.build_strategy.ParallelBuildStrategy object
at 0x00000179EF786C70>>, <samcli.lib.build.build_graph.FunctionBuildDefinition object at 0x00000179EF786250>)
2023-06-02 09:20:44,248 | Building codeuri: C:\Users\vince\Documents\Git\Serverless\sam-app runtime: None metadata:
{'DockerTag': 'python3.7-v1', 'DockerContext': 'C:\\Users\\vince\\Documents\\Git\\Serverless\\sam-app\\hello_world',
'Dockerfile': 'Dockerfile'} architecture: x86_64 functions: HelloWorldFunction
2023-06-02 09:20:44,248 | Waiting for async results
2023-06-02 09:20:44,248 | Building to following folder
C:\Users\vince\Documents\Git\Serverless\sam-app\.aws-sam\build\HelloWorldFunction
2023-06-02 09:20:44,248 | Building image for HelloWorldFunction function
2023-06-02 09:20:44,248 | Exception raised during the execution
2023-06-02 09:20:44,264 | Telemetry endpoint configured to be
https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-06-02 09:20:44,380 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId':
'fa5bf1e5-f3ec-43a6-b93a-f544a1386119', 'installationId': '7daaae3f-0ce4-418b-87aa-be6af87977f9', 'sessionId':
'e821f707-1970-42b0-aebe-7b628d58519c', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8',
'samcliVersion': '1.85.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam
build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName':
'593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3', 'initialCommit': None}, 'duration': 587,
'exitReason': 'TypeError', 'exitCode': 255}}]}
2023-06-02 09:20:44,733 | Telemetry response: 200

Error: request() got an unexpected keyword argument 'chunked'
Traceback:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 184, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 149, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 275, in do_cli
    ctx.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 279, in run
    self._build_result = builder.build()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 214, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 394, in build
    return super().build()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 81, in build
    result.update(self._build_functions(self._build_graph))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 400, in _build_functions
    return self._run_builds_async(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 416, in _run_builds_async
    async_results = async_context.run_async()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\async_utils.py", line 131, in run_async
    return run_given_tasks_async(self._async_tasks, event_loop)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\async_utils.py", line 90, in run_given_tasks_async
    return event_loop.run_until_complete(_run_given_tasks_async(tasks, event_loop, executor))
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\async_utils.py", line 58, in _run_given_tasks_async
    raise result
  File "concurrent\futures\thread.py", line 57, in run
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 427, in build_single_function_definition
    return self._delegate_build_strategy.build_single_function_definition(build_definition)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 164, in build_single_function_definition
    result = self._build_function(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 634, in _build_function
    return self._build_lambda_image(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 394, in _build_lambda_image
    if not is_docker_reachable(self._docker_client):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\utils.py", line 90, in is_docker_reachable
    docker_client.ping()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 187, in ping
    return self.api.ping(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\daemon.py", line 166, in ping
    return self._result(self._get(self._url('/_ping'))) == 'OK'
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\utils\decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(

An unexpected error was encountered while executing "sam build".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20build%20-%20TypeError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20build%20-%20TypeError

```

### Expected result:

I was expecting to be able to build on my docker so I could test the project. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 Pro Version 21H2 Build: 19044.2965
2. `sam --version`: SAM CLI, version 1.85.0
3. AWS region: us-east-1
4. AWS CLI : aws-cli/2.11.24 Python/3.11.3 Windows/10 exe/AMD64 prompt/off
5. Docker : v4.20.0 (WSL2). 
6. Python : 3.11.3
```
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 58, in print_info
    "additional_dependencies": gather_additional_dependencies_info(),
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\system_info.py", line 37, in gather_additional_dependencies_info
    "docker_engine": _gather_docker_info(),
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\system_info.py", line 60, in _gather_docker_info
    if is_docker_reachable(client):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\utils.py", line 90, in is_docker_reachable
    docker_client.ping()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 187, in ping
    return self.api.ping(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\daemon.py", line 166, in ping
    return self._result(self._get(self._url('/_ping'))) == 'OK'
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\utils\decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: request() got an unexpected keyword argument 'chunked'

```

`Add --debug flag to command you are running`

**Comment by jfuss** [comment] 2023-06-02 14:08
Duplicate of #5243

**Closed by jfuss** 2023-06-02 14:08 UTC
Labels: stage/needs-triage
