### ISSUE TITLE
HttpApi: wrong capitalisation of properties in the headers object

### ISSUE THREAD

**Issue by mastazi** [aws/aws-sam-cli#3083] opened 2021-07-20 03:12 UTC
### Description:

I have this function:
```
fakeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/handlers.fake
      Description: A Lambda function.
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /my-path/
            Method: get
```
if I send a header called “Myheader” in the request, then when running `sam local start-api`, the function will be able to access its value in `event.headers.Myheader` - note that `Myheader` is capitalised. But after deployment, API Gateway will store the value in `event.headers.myheader`. So, in order to have my code work both in SAM and in the cloud, I have to do something like (assuming the function is in Node.js):

```
let myvar = '';
if (process.env.AWS_SAM_LOCAL) {
    myvar  = event.headers.Myheader;
} else {
    myvar = event.headers.myheader;
}
```

### Steps to reproduce:

1. Create a function with an HttpApi Path.
2. In the response, return `event.headers`, see code snippet below.
2. Build and then start local api with `sam local start-api`
3. Call the function from an http client, and send some arbitrarily named headers with the request, e.g. `Foo: bar, Baz: bar`.

```
    const response = {
        statusCode: 200,
        body: JSON.stringify(event.headers),
    };
    return response;
```

### Observed result:

In the response, you will see those headers will be capitalised:
```
{
  "Foo": "bar",
  "Baz": "bar"
}
```

### Expected result:

The expected result is that the headers should be not capitalised, which is the same behaviour that AWS Api Gateway has in production:

```
{
  "foo": "bar",
  "baz": "bar"
}
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 1.23.0
3. AWS region: ap-southeast-2

**Comment by FieryCod** [comment] 2021-07-21 14:17
This is true for Java rapid runtime as well, which makes the development pain, unfortunately.

**Comment by jfuss** [comment] 2021-07-22 02:31
Please see previous issue about this: https://github.com/aws/aws-sam-cli/issues/1860#issuecomment-801243951

This is known difference and something we are not looking to address. Headers are case insensitive and should be handled in the function code. This is also being caused by Flask (what we are using locally to build the service). https://github.com/aws/aws-sam-cli/issues/1860#issuecomment-628076065 has more info and links to other issues explain it deeper.

Closing as won't fix.

**Closed by jfuss** 2021-07-22 02:31 UTC

**Comment by mastazi** [comment] 2021-07-25 02:52
Hi @jfuss thank you for your comment and sorry for inadvertently opening a duplicate (I had searched for it but couldn't find #1860 the other day).

Just one note though:

[here](https://github.com/aws/aws-sam-cli/issues/1860#issuecomment-628076065} you said: 

> Do note that headers are case-insensitive so handling this in your function code is a reasonable expectation.

I have to disagree on this one, if the docs tell me that headers are case insensitive, my initial instinct when reading that, is that I'm not going to worry about normalising capitalisation (which is what I ended up doing), because "headers are case-insensitive" sounds like the simulator would do it for me.

So, if this inconsistency is not easily fixable, I think the documentation should be updated. Is it possible to file an issue related to AWS SAM docs? Do you know if there is a repo for that?

**Comment by mastazi** [comment] 2021-07-25 03:05
One more thing @jfuss I want to clarify:

API Gateway also makes headers case-insensitive. So, I'm not asking for headers to be case sensitive.

In API Gateway, both raw headers `Myheader` and `myheader` will result in `headers.myheader`.

But in SAM they both result in `headers.Myheader`. What I was asking is **for the dictionary to have lowercase properties**, so it matches API Gateway. **I was not asking for the headers to be case sensitive.**

**Comment by mastazi** [comment] 2021-07-25 04:24
Update: submitted PR https://github.com/aws/aws-sam-cli/pull/3114

**Comment by FieryCod** [comment] 2021-07-25 05:08
This will hardly ever be accepted do to the breakage it brings to the users. 

I'm really sorry your situation, cause I was in the same. You would have to lowercase all the headers from event in your code unfortunately.

**Comment by mastazi** [comment] 2021-07-25 05:27
@FieryCod Yes it will bring disruption to some users, however I expect most users are jus converting to lowercase and in that instance, nothing will break. The only instance in which it will break is if users are using if-else check, and retrieve capitalised headers if they are in localhost.

**Comment by mastazi** [comment] 2021-07-26 03:31
updated: closed previous pr and reopened as #3117 due to previous PR having issues with linter.

**Comment by jfuss** [comment] 2021-07-27 15:57
@mastazi We cannot just `lower()` all headers and API Gateway does not just lower all headers. See: https://github.com/aws/aws-sam-cli/issues/1860#issuecomment-628576313, the concrete example is `Authorization` which remains that same casing. 

API Gateway does not document how they determine casing, so whatever we do is going to be heuristics. Headers are case-insensitive and therefore you cannot guarantee how API Gateway will process them.

As @FieryCod mentioned, this change will break customers. A function that runs today, will break existing customers. We are willing to accept changes like this but they will need to match API Gateway. Just lowering all headers doesn't match API Gateway and will break customers. If your willing to go down a huge testing flow and add all the heuristics to make this SAM match API Gateway, we can look at that. However, we have done this in the past, and Flask does not have a way to get the raw requests. More details: https://github.com/aws/aws-sam-cli/issues/1860#issuecomment-628076065

I will comment the same on the PR but currently, I don't think we can accept just `.lower()` on all headers.

**Comment by mastazi** [comment] 2021-07-29 04:49
Thank you @jfuss I missed that comment about Authorization, now I understand what you meant in your comment in #1860 where you said that API Gateway does not document how they do it.

Thanks for correcting my wrong assumption, closing #3117 

> If your willing to go down a huge testing flow and add all the heuristics to make this SAM match API Gateway, we can look at that.

I'm still getting used to the codebase, if I get to a point where I feel ready for that, I will try.

> However, we have done this in the past, and Flask does not have a way to get the raw requests.

Yes, I see what you mean, however there is a (remote) possibility that the rules that API Gateway is using, could be re-implemented without accessing raw headers, however we don't know that yet.
