### ISSUE TITLE
Support for custom authorizer in Swagger definition

### ISSUE THREAD

**Issue by sapessi** [aws/aws-sam-cli#223] opened 2017-12-06 22:00 UTC
Implement support for the execution of custom authorizers when defined in the API swagger template. The implementation should at least run the authorizer function, capture the output template, and verify that the request is allowed. Context variables returned by the authorizer should be injected in the context.

**Comment by ericofusco** [comment] 2019-01-25 16:40
@sapessi Anyone actively working on that? Any help needed?

**Comment by jfuss** [comment] 2019-01-25 16:48
@ericofusco I am not aware of anyone working on this currently. Contributions are always welcome. :)

Calling the cloud function could difficult currently. SAM CLI does not yet resolve Fn:Sub intrinsic functions. We may be able to extract the function name and assume we are in the account and region specified but full ARNs won't be possible to support yet. This issue was originally created before SAM supported Custom Authorizers, so it's worth considering starting from local execution first and then expand to the cloud if needed. 

The best place to start would be to do a quick write up, full design isn't probably needed. This will help orient/align us before getting deep into code. Happy to talk more on the #samdev channel as well.

**Comment by ericofusco** [comment] 2019-02-04 12:17
Thanks @jfuss. I'll reach out on #samdev to get this started.

**Comment by krazykhris875** [comment] 2019-10-02 11:56
So is it currently impossible to execute an API Gateway locally with authorizer and lambda proxy integration?

**Comment by NightWatchman** [comment] 2020-02-14 18:36
> So is it currently impossible to execute an API Gateway locally with authorizer and lambda proxy integration?

I am unclear as to whether this is an issue with API's defined in a cloudformation template and no swagger, but it doesn't work for me so I'm guessing it's not currently possible.

**Comment by LennyDuan** [comment] 2020-05-12 17:52
SAM doesn't support custom authorizers when you run locally. So you can't test it.

But it supports in SAM YAML template and you can sue SAM CLI to build and deploy it to you AWS cloud and it can work if your config it correctly.

**Comment by jfuss** [comment] 2022-12-20 20:39
This is a duplicate of https://github.com/aws/aws-sam-cli/issues/137.

Closing

**Closed by jfuss** 2022-12-20 20:39 UTC
Labels: priority/3-long-term, type/feature, area/api-integration, stage/pm-review, maintainer/need-followup
