### ISSUE TITLE
When debugging go Lambdas, a lot of `could not find abstract origin of inlined call` messages are printed on startup

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-sam-cli#2685] opened 2021-03-04 22:44 UTC
### Description:
When starting the Go debugger, lots of lines of `could not find abstract origin` are printed (about 400). Attaching to the debugger works fine, but it's very distracting.

### Steps to reproduce:
```
"C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" local invoke HelloWorldFunction --template C:\Users\bryceito\GolandProjects\untitled\.aws-sam\build\template.yaml --event "C:\Users\bryceito\AppData\Local\Temp\[Local] HelloWorldFunction-event3.json" --debugger-path C:\Users\bryceito\AppData\Local\Temp\goDebugger4750947064236825613 --debug-args -delveAPI=2 --debug-port 57687
```

### Observed result:

```
Invoking hello-world (go1.x)
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-go1.x:rapid-1.18.2.
 
Mounting C:\Users\bryceito\GolandProjects\untitled\.aws-sam\build\HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: d32bb276-e1aa-4880-9364-3972e31a7851 Version: $LATEST
API server listening at: [::]:57687
2021-03-04T22:34:08Z info layer=debugger launching process with args: [/var/task/hello-world]
2021-03-04T22:34:09Z warning layer=debugger reading debug_info: could not find abstract origin (0xcef66) of inlined call at 0x96b26
2021-03-04T22:34:09Z warning layer=debugger reading debug_info: could not find abstract origin (0xcef66) of inlined call at 0x96b41
2021-03-04T22:34:09Z warning layer=debugger reading debug_info: could not find abstract origin (0xcef66) of inlined call at 0x96b5c
```

### Expected result:

Not to have 400 lines output

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows/OSX
2. `sam --version`: 1.18.1
3. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by aahung** [comment] 2021-03-05 22:39
Hi @hunterwerlla, did this happen before #2462 (e.g., in v1.12)?

**Comment by hunterwerlla** [comment] 2021-03-05 22:51
Yes this happened on earlier versions. This is with the sam go 1.x hello world template with nothing changed.

**Comment by aahung** [comment] 2021-03-05 22:54
> Yes this happened on earlier versions. This is with the sam go 1.x hello world template with nothing changed.

if you try to use the compiler flags in the stackoverflow answer I posted above, will it disappear?

**Comment by hunterwerlla** [comment] 2021-03-17 15:28
@aahung this is built using `sam build` is there even a way to pass compiler flags into it for go?

**Comment by jfuss** [comment] 2023-04-13 03:25
SAM CLi will auto add the right flags for debugging: https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/go_modules/builder.py#L64-L66 but you need to pass/set [`SAM_BUILD_MODE=debug`](https://github.com/aws/aws-sam-cli/blob/401ea3329ce8066bb9dff4a7d26f2157c08b2f3b/samcli/commands/build/command.py#L178) when running `sam build`.

The AWS Toolkits will take care of this for you.

Closing as this seems to be caused by not compiling the binary correctly and the issue is very old at this point. If I got something wrong, please open a new issue and happy to look into it further.

**Closed by jfuss** 2023-04-13 03:25 UTC
Labels: area/debugging, stage/needs-investigation, maintainer/need-followup
