### ISSUE TITLE
Bug: BasePath is ignored in templates when running local 

### ISSUE THREAD

**Issue by BenPela** [aws/aws-sam-cli#5164] opened 2023-05-12 23:40 UTC
### Description:
Running running locally adding a BasePath to the Domain configuration for you api will be ignored. This is especially important when using nested stacks. 

Our API has outgrown a single Cloudformation stack and must be nested as suggest [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-nested-applications.html)

Due to this bug, I've been unable to find any way of running multiple APIs using the same domain, supporting local development on AWS SAM.

### Steps to reproduce:
Clone https://github.com/BenPela/aws-local-example
`sam build`
`sam local start-api`

### Observed result:
Base Path is ignored, resulting in V1 of my functions not being available at all, locally. 

```Mounting V2 at http://127.0.0.1:3000/users [GET, OPTIONS]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI if you update your AWS SAM template
2023-05-11 17:31:19  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
```

### Expected result:
Base Path is not ignored 
```
Mounting V1 at http://127.0.0.1:3000/v1/users [GET, OPTIONS]
Mounting V2 at http://127.0.0.1:3000/v2/users [GET, OPTIONS]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI if you update your AWS SAM template
2023-05-11 17:31:19  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
{
  "version": "1.73.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.3.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.23",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

**Comment by hawflau** [comment] 2023-05-18 22:26
Hi @BenPela thanks for raising the issue. Currently `sam local start-api` does not support multiple APIs in the same stack or in nested stack. It also does not consume the `Domain.BasePath` porperty. I'm closing this issue as it's a duplicate of #3306. However, we shall consider the `BasePath` use case when we design this feature. 

Meanwhile, as a workaround, you can run two `sam local start-api` concurrently:
```
(in one terminal session)
sam local start-api -t v1/template.yaml -p 3000

(in another terminal session)
sam local start-api -t v2/template.yaml -p 3001
```

**Closed by hawflau** 2023-05-18 22:26 UTC
Labels: type/duplicate, area/local/start-api
