### ISSUE TITLE
1.36 throwing strange validation error

### ISSUE THREAD

**Issue by amancevice** [aws/aws-sam-cli#3493] opened 2021-11-24 16:26 UTC
### Description:
`sam validate` is throwing s very odd error for SAM v1.36 — looks like its interpreting a string message as an array

### Steps to reproduce:

Create the following template:

```yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Description: Serverless trashy
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApiKey:
    Type: AWS::SSM::Parameter::Value<String>
    Description: My Api Key
    Default: <some-ssm-param>

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          API_KEY: !Ref ApiKey
      Handler: handler
      InlineCode: |-
        require 'json'

        def handler(event:nil, context:nil)
          { ok: true }
        end
      Runtime: ruby2.7
```

Run `sam validate` on the template

### Observed result:

```
2021-11-24 11:22:18 Template schema validation reported the following errors: [, P, a, r, a, m, e, t, e, r, s, ., A, p, i, K, e, y, ., T, y, p, e, ],  , ', A, W, S, :, :, S, S, M, :, :, P, a, r, a, m, e, t, e, r, :, :, V, a, l, u, e, <, S, t, r, i, n, g, >, ',  , i, s,  , n, o, t,  , o, n, e,  , o, f,  , [, ', S, t, r, i, n, g, ', ,,  , ', N, u, m, b, e, r, ', ,,  , ', L, i, s, t, <, N, u, m, b, e, r, >, ', ,,  , ', C, o, m, m, a, D, e, l, i, m, i, t, e, d, L, i, s, t, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, A, v, a, i, l, a, b, i, l, i, t, y, Z, o, n, e, :, :, N, a, m, e, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, I, m, a, g, e, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, I, n, s, t, a, n, c, e, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, K, e, y, P, a, i, r, :, :, K, e, y, N, a, m, e, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, S, e, c, u, r, i, t, y, G, r, o, u, p, :, :, G, r, o, u, p, N, a, m, e, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, S, e, c, u, r, i, t, y, G, r, o, u, p, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, S, u, b, n, e, t, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, V, o, l, u, m, e, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, V, P, C, :, :, I, d, ', ,,  , ', A, W, S, :, :, R, o, u, t, e, 5, 3, :, :, H, o, s, t, e, d, Z, o, n, e, :, :, I, d, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, A, v, a, i, l, a, b, i, l, i, t, y, Z, o, n, e, :, :, N, a, m, e, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, I, m, a, g, e, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, I, n, s, t, a, n, c, e, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, S, e, c, u, r, i, t, y, G, r, o, u, p, :, :, G, r, o, u, p, N, a, m, e, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, S, e, c, u, r, i, t, y, G, r, o, u, p, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, S, u, b, n, e, t, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, V, o, l, u, m, e, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, V, P, C, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, R, o, u, t, e, 5, 3, :, :, H, o, s, t, e, d, Z, o, n, e, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, S, t, r, i, n, g, >, ', ]
```

### Expected result:
`sam validate` should not print such an error. Reverting to v1.35 resolves the issue

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.6.1
2. `sam --version`: 1.36
3. AWS region: us-east-1

**Comment by torresxb1** [comment] 2021-11-24 21:41
I was able to reproduce this. We've identified the issue and are working on a fix. Thank you for bringing this to our attention!

**Comment by torresxb1** [comment] 2021-11-24 22:05
I should add that this bug doesn't break the CLI, it's just a bug with the error message itself.

**Comment by torresxb1** [comment] 2021-11-30 22:30
PR has been merged and should be included in the next release, so I'm closing this issue. Thanks again for raising this up!

**Closed by torresxb1** 2021-11-30 22:30 UTC
Labels: type/bug, area/validate, stage/pr

**Comment by cifvts** [comment] 2022-01-06 07:36
I have just tested the same template with the latest version and the problem is still present.
```
[templates]$ sam validate --profile test -t template.test.yml 
2022-01-06 08:31:31 Loading policies from IAM...
2022-01-06 08:31:33 Finished loading policies from IAM.
2022-01-06 08:31:33 Template schema validation reported the following errors: [, P, a, r, a, m, e, t, e, r, s, ., A, p, i, K, e, y, ., T, y, p, e, ],  , ', A, W, S, :, :, S, S, M, :, :, P, a, r, a, m, e, t, e, r, :, :, V, a, l, u, e, <, S, t, r, i, n, g, >, ',  , i, s,  , n, o, t,  , o, n, e,  , o, f,  , [, ', S, t, r, i, n, g, ', ,,  , ', N, u, m, b, e, r, ', ,,  , ', L, i, s, t, <, N, u, m, b, e, r, >, ', ,,  , ', C, o, m, m, a, D, e, l, i, m, i, t, e, d, L, i, s, t, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, A, v, a, i, l, a, b, i, l, i, t, y, Z, o, n, e, :, :, N, a, m, e, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, I, m, a, g, e, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, I, n, s, t, a, n, c, e, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, K, e, y, P, a, i, r, :, :, K, e, y, N, a, m, e, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, S, e, c, u, r, i, t, y, G, r, o, u, p, :, :, G, r, o, u, p, N, a, m, e, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, S, e, c, u, r, i, t, y, G, r, o, u, p, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, S, u, b, n, e, t, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, V, o, l, u, m, e, :, :, I, d, ', ,,  , ', A, W, S, :, :, E, C, 2, :, :, V, P, C, :, :, I, d, ', ,,  , ', A, W, S, :, :, R, o, u, t, e, 5, 3, :, :, H, o, s, t, e, d, Z, o, n, e, :, :, I, d, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, A, v, a, i, l, a, b, i, l, i, t, y, Z, o, n, e, :, :, N, a, m, e, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, I, m, a, g, e, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, I, n, s, t, a, n, c, e, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, S, e, c, u, r, i, t, y, G, r, o, u, p, :, :, G, r, o, u, p, N, a, m, e, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, S, e, c, u, r, i, t, y, G, r, o, u, p, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, S, u, b, n, e, t, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, V, o, l, u, m, e, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, E, C, 2, :, :, V, P, C, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, A, W, S, :, :, R, o, u, t, e, 5, 3, :, :, H, o, s, t, e, d, Z, o, n, e, :, :, I, d, >, ', ,,  , ', L, i, s, t, <, S, t, r, i, n, g, >, ', ]
/home/user/Downloads/templates/template.test.yml is a valid SAM Template
2022-01-06 08:31:34 There are unpublished metrics. Please make sure you call publish after you record all metrics.
2022-01-06 08:31:34 There are unpublished metrics. Please make sure you call publish after you record all metrics.

[templates]$ sam --version
SAM CLI, version 1.37.0
```

**Comment by torresxb1** [comment] 2022-01-06 18:12
Hi @cifvts, the fix was done in the https://github.com/aws/serverless-application-model/ repo, which hasn't been released yet.
